### ISSUE TITLE
/__heartbeat__ doesn't work with GCS storage

### ISSUE THREAD

**Issue by jbuck** [mozilla/send#1011]
If you visit http://send.firefox.com/__heartbeat__ you'll get an ISE now. This only started happening once I switched over to GCS, so I guess something to do with the ping functionality isn't working? The service itself is fine though.

**Comment by dannycoates** [comment]
we get a `... does not have storage.buckets.get access ...` running `bucket.exists()` so we can either add that permission or change the call we use to ping

**Comment by dannycoates** [comment]
fixed in prod
