### ISSUE TITLE
The elements from the page can wrongly be uploaded using drag and drop functionality

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/send#1013]
**[Affected versions]:**
- Firefox 63.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.

**[Steps to reproduce]:**
1. Open the new Firefox profile and navigate to "https://vnext.send.nonprod.cloudops.mozgcp.net/" page.
2. Drag and drop an element from the page (eg. "the flying page icon"). 
3. Observe the "DROP FILES HERE" section.

**[Expected result]:**
- Nothing happens. 

**[Actual result]:**
- The "Ready to send" option is displayed, but with no content to send.

**[Notes]:**
- The drag and drop functionality it doesn't work anymore if the "Ready to send" button is clicked.
- If the page is refreshed after the "Ready to send" button is clicked, the "Link has expired" page is briefly displayed then you are redirected to the "Something went wrong" page.
- Attached is a screen recording of the issue: 
![drag drop](https://user-images.githubusercontent.com/40061643/48715734-55f39180-ec1e-11e8-9c90-a60d48579baa.gif)

**Comment by dannycoates** [comment]
fixed in 74d8a12c0726c0082480548914e48e78803662df

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible with the latest fixes. Tested on Windows 10x64, Mac 10.13 and Arch Linux 4.16.6 x64.
