### ISSUE TITLE
The "Cancel" button wrongly performs another download instead of canceling the download process

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/send#1015]
**[Affected versions]:**
- Firefox 63.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have a file created for upload.

**[Steps to reproduce]:**
1. Open the new Firefox profile and navigate to "https://vnext.send.nonprod.cloudops.mozgcp.net/" page.
2. Drag and drop the file from prerequisites.
3. Select the "Expiry" option for 2 downloads or more and click the "Ready to Send" button.  
4. Click the "Copy to clipboard" button and open a New Tab.
5. Right click in the "Search bar" and chose the "Paste & Go" option.
6. Click the "Download" button and then the "Cancel" button.
7. Observe the behavior.

**[Expected result]:**
- The download process is canceled.

**[Actual result]:**
- The download process is not canceled and one more download of the file is performed.

**[Additional Note]:**
- Attached is a screen recording of the issue: 
![cancel](https://user-images.githubusercontent.com/40061643/48721952-9279ba00-ec2b-11e8-86a2-edca0d2f9019.gif)

**Comment by dannycoates** [comment]
fixed in c99697caae8bf80bc76315d287a7a556f279fc87

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest fixes. Tested on Windows 10x64, Mac 10.13 and Arch Linux 4.16.6 x64.
