### ISSUE TITLE
[Send v2] The remaining number of downloads is wrongly displayed after uploading a file

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1017]
[Affected Versions]:
- Firefox 63.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to https://vnext.send.nonprod.cloudops.mozgcp.net/
2. Drag and drop a file in the "Drop files here" section.
3. From the "1 download" dropdown select the "2 downloads" option.
4. Navigate to the "Send" homepage and observe the description of the uploaded file. 

[Expected result]:
- The "Expires after 2 downloads or 23h 59m" description is displayed.

[Actual result]:
- The "Expires after 1 download or 23h 59m" description is displayed.

[Notes]:
- This issue is also reproducible with all other settings except "1 download".
- After refreshing the page the number of downloadable times for a document is correctly displayed. 
- Attached a screen recording of the issue: 

![rec of the issue - after nr of downloads](https://user-images.githubusercontent.com/37875464/48762173-26db2f80-ecb3-11e8-9c6c-5f8f7870290c.gif)

**Comment by dannycoates** [comment]
I forget when i fixed this but i did

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Firefox 64 and up, on Windows 10 x64, Arch Linux 4.14.3, and Mac 10.13.3.
