### ISSUE TITLE
[Send v2] "Add file(s)", "Ready to Send", "Copy to clipboard" and "Ok" buttons don't have a hover effect

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1018]
[Affected Versions]:
- Firefox 63.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to https://vnext.send.nonprod.cloudops.mozgcp.net/
2. Hover the "Add file(s)" button.
3. Observe the behavior of the button.

[Expected result]:
- The button has a darker blue color and a specific tooltip.

[Actual result]:
- The color of the button remains the same.

[Notes]:
- Attached a screen recording of the issue: 

![rec of the issue - hover effect](https://user-images.githubusercontent.com/37875464/48762717-4a52aa00-ecb4-11e8-8d62-5a7e918e35ed.gif)

**Comment by dannycoates** [comment]
fixed in #1088

**Comment by dannycoates** [comment]
oops. hover isn't on all of them. I'll make a component for it https://tailwindcss.com/docs/extracting-components

**Comment by dannycoates** [comment]
hovers added in #1102 except for 'ok' which idk if it should?

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org/ website on Mac 10.13.3 and Windows 10 x64 and Arch Linux.
