### ISSUE TITLE
[Send v2] Files can not be uploaded using Chrome, Opera or Safari browsers

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/send#1019]
**[Affected versions]:**
- Firefox 63.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have Chrome, Opera or Safari installed on your PC.
- Have a file created for upload.

**[Steps to reproduce]:**
1. Open the new Firefox profile and navigate to "https://vnext.send.nonprod.cloudops.mozgcp.net/" page.
2. Drag and drop the file from prerequisites.
3. Click the "Ready to send" button and observe the behavior

**[Expected result]:**
- The upload process starts and finishes.

**[Actual result]:**
- The upload process is blocked at "0%".

**[Notes]:**
- On Safari , after clicking the "Ready to send" button, the upload process is briefly displayed and after that you are redirected to the "Something went wrong" page.
- Also, after the upload process is displayed, the "Cancel upload" button is no longer actionable. 
- The download functionality is working as expected.
- Attached is a screen recording of the issue: 
![upload](https://user-images.githubusercontent.com/40061643/48772128-13888e00-eccc-11e8-8d63-68c9261fc48c.gif)

**Comment by dannycoates** [comment]
we should use https://send2.dev.lcip.org instead of https://vnext.send.nonprod.cloudops.mozgcp.net/ from now on. closing as 'works now'

**Comment by Softvision-RemusDranca** [comment]
I have tested this issue using the "https://send2.dev.lcip.org/" website and the issue is not reproducible.
Also, considering that the issue is still reproducible on "https://vnext.send.nonprod.cloudops.mozgcp.net/" website  I will mark this issue as "wontfix".
Tested on Windows 10 x64, Mac 10.13.6 and Arch Linux 4.14.3.
