### ISSUE TITLE
[Send v2] The description and the "Try Firefox Send" hyperlink wrongly exceed the card on the expired link page on other browsers

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1025]
**[Affected Versions]:**
- Chrome Version 70.0.3538.110
- Opera Version 56.0.3051.104
- Microsoft Edge 42.17134.1.0
- Safari 11.0.3

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open a different browser from Firefox and maximize it.
2. Navigate to https://vnext.send.nonprod.cloudops.mozgcp.net/404
3. Observe the page.
4. Resize the browser vertically to ~70% and observe the page. 

**[Expected result]:**
3 & 4. The description and the "Try Firefox Send" hyperlink are inside the card.

**[Actual results]:**
3. The description and the "Try Firefox Send" hyperlink exceed the card. 
4. The "Try Firefox Send" hyperlink is not displayed.
 
 **[Notes]:**
- On 13 inch screens the "Try Firefox Send" hyperlink is not visible even if its maximized.
- Attached a screenshot and screen recording of the issue:

![chrome maximized](https://user-images.githubusercontent.com/37875464/48942912-12549c80-ef2a-11e8-8ad7-99529b37dda8.png)

![rec of the issue - resize](https://user-images.githubusercontent.com/37875464/48942916-15e82380-ef2a-11e8-845a-ae1bc5603f76.gif)

**Comment by dannycoates** [comment]
fixed in 4e0425ad7e19e0ba75b3e6267fcbe865d8e920d3

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the "https://send2.dev.lcip.org/404" page on Windows 10x64, Arch Linux and Mac 10.13.3.
