### ISSUE TITLE
[Send v2][Edge][Safari] The password field is not displayed on the download file page

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1026]
**[Affected Versions]:**
- Microsoft Edge 42.17134.1.0
- Safari 11.0.3

**[Affected Platforms]:**
- All Windows
- All Mac

**[Prerequisite]:**
- Have a link to an uploaded file protected with a password.

**[Steps to reproduce]:**
1. Open the Microsoft Edge browser and navigate to the link from the prerequisites.
2. Observe the left part of the card from the center of the page.

**[Expected result]:**
- The password field is displayed.

**[Actual results]:**
- No elements are displayed.
 
 **[Notes]:**
- This issue is not reproducible on Firefox, Google Chrome, Opera browsers.
- Attached a screenshot of the issue:

![no password field](https://user-images.githubusercontent.com/37875464/48948027-dcb8af00-ef3b-11e8-8744-60e12a340ba3.png)

**Comment by dannycoates** [comment]
works now in safari. edge is still globally broken. Closing this and we'll track the edge half in #1065

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on Safari 11.0.3, on Mac 10.13.3.
