### ISSUE TITLE
The "Something went wrong!" page is wrongly displayed after first sign-in attempt

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1033]
**[Affected Versions]:**
- Firefox 63.0. and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://vnext.send.nonprod.cloudops.mozgcp.net/
2. Click the "Sign in/up" button.
3. Sign in with a valid account.
4. Observe the displayed page.

**[Expected result]:**
- The send v2 homepage is displayed.

**[Actual result]:**
- You are redirected to the  "https://send2.dev.lcip.org" website and the "Something went wrong" page is displayed.

**[Notes]:**
- On the "https://send2.dev.lcip.org" website the login is successful with valid credentials.
- Attached a screen recording of the issue:

![rec of the issue - log in2](https://user-images.githubusercontent.com/37875464/49453649-3e0a3900-f7ec-11e8-8a8c-a605f27855c2.gif)

**Comment by dannycoates** [comment]
FxA won't ever work with https://vnext.send.nonprod.cloudops.mozgcp.net because our registered redirect url is for send2.dev.lcip.org. We shouldn't use the former for testing.
