### ISSUE TITLE
The uploaded files are no longer displayed after signing out

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1034]
**[Affected Versions]:**
-Firefox 63.0. and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org.
2. Upload at least one file and then sign in.
3. Sign out and observe the uploaded files section.

**[Expected result]:**
- The uploaded file is displayed.

**[Actual result]:**
- The uploaded file is no longer displayed.

**[Notes]:**
- Attached a screen recording of the issue:

![rec of the issue - send](https://user-images.githubusercontent.com/37875464/49454104-25e6e980-f7ed-11e8-8bea-2cdf50ca28c6.gif)

**Comment by dannycoates** [comment]
This is intentional behavior. Logging out clears the list. Logging back in should restore the list. Any items uploaded before logging in get "adopted" by the account once logged in.

**Comment by clouserw** [comment]
closing due to previous comment
