### ISSUE TITLE
Update Docker image to Node 10 & switch off Alpine

### ISSUE THREAD

**Issue by jbuck** [mozilla/send#1035]
Node 8 is leaving LTS earlier than expected on 2019-01-01. I'd like to switch to Node 10 and do a deploy before we leave for the holidays. On a separate but related note, the security team has asked that we migrate away from Alpine-based images. The reasoning is that the Alpine team doesn't have as strong a security reporting/fixing process as Debian.

**Comment by dannycoates** [comment]
@jbuck care to port #1042 to vnext?

**Comment by jbuck** [comment]
@dannycoates Yep, I can do this. It looks like you've applied some of the changes from this patch already, do you want me to just apply the Dockerfile change, or do you want me to remove webpack-dev-server as well?

**Comment by dannycoates** [comment]
@jbuck, thanks! vnext is on webpack 4 so we ought to be able to keep the dev-server. If applying the dockerfile is all we need that'd be great.

**Comment by jbuck** [comment]
Okay, pushed #1072
