### ISSUE TITLE
[Android] Tapping the "Back" button after opening the file selection menu crashes the application

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/send#1037]
[Affected Platforms]:
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

[Prerequisites]:
- The sendandroid apk is installed.

[Steps to reproduce]:
1. Open the Send application and tap the "Add file" button.
2. Tap the "Back" button and observe the behavior.

[Expected result]:
- The file selection menu is closed and the main page is displayed.

[Actual result]:
- The application crashes.

[Notes]:
- Attached a screen recording of the issue:
![crash](https://user-images.githubusercontent.com/40393891/49948370-fc6c4300-fefb-11e8-8037-f3263d8a4ab9.gif)

**Comment by clouserw** [comment]
Is this still reproducible?

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is still reproducible using send-android-12-20-18-signed.apk on Android 8.0.0 (Google Pixel and Samsung Galaxy S8).

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-02-06-signed.apk) on Samsung S8 and Google Pixel.
