### ISSUE TITLE
[Android] The "With a free Firefox Account..." message is wrongly displayed when selecting an option with over 20 downloads while being logged into FxA

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1039]
**[Affected Platforms]:**
- Google Pixel [Android 8.0]
- Samsung S8 [Android 8.0]

**[Prerequisites]:**
- Have the [Send android app](https://drive.google.com/open?id=1STazCrRV5TKD4Q7br-TTYnFQ1nqHIU7Y) installed.

**[Steps to reproduce]:**
1. Open the Send application.
2. Log into a valid Firefox account.
3. Add a file and tap the "1 download" option.
4. Tap the "50 downloads" option.
5. Observe the displayed screen.

**[Expected result]:**
- The uploaded file has a set limit of 50 downloads.

**[Actual results]:**
- The "With a free Firefox Account..." message is displayed.
 
 **[Notes]:**
- This issue is reproducible with the following options: "50 downloads", "100 downloads" and "200 downloads" options.
- This issue is not reproducible with the [Send V2 website](https://send2.dev.lcip.org/).
- Attached a screen recording of the issue:

![rec of the issue - error while logged in](https://user-images.githubusercontent.com/37875464/50010489-4a4b7e80-ffc2-11e8-8211-7a0d8bd22106.gif)

**Comment by dannycoates** [comment]
fixed in #1075

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the[ latest Send Android build](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig) on Samsung S8, Google Pixel and Huawei P20 Lite.
