### ISSUE TITLE
[Android] The "7 days" option can wrongly be set while not being logged into FxA

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1040]
**[Affected Platforms]:**
- Google Pixel [Android 8.0]
- Samsung S8 [Android 8.0]

**[Prerequisites]:**
- Have the [Send android app](https://drive.google.com/open?id=1STazCrRV5TKD4Q7br-TTYnFQ1nqHIU7Y) installed.

**[Steps to reproduce]:**
1. Open the Send application.
3. Add a file and tap the "1 day" option.
4. Tap the "7 days" option.
5. Observe the displayed screen.

**[Expected result]:**
- The "With a free Firefox Account..." message is displayed.

**[Actual results]:**
- The uploaded file has a set expiration time of 7 days.

 
 **[Notes]:**
- On [Send V2 website](https://send2.dev.lcip.org/) the "With a free Firefox Account..." message is displayed when selecting the “7 days” option while you are not logged into FxA.
- Attached a screenshot of the issue:

![rec of the issue - 7 days](https://user-images.githubusercontent.com/37875464/50010756-ea090c80-ffc2-11e8-96ee-028aa8890c5e.gif)

**Comment by dannycoates** [comment]
fixed in #1075

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android [build](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig) on Samsung S8 and Pixel.
