### ISSUE TITLE
[Android] The “Sorry, an error occurred” message is displayed when uploading a file with the expiration time of 7 days

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1041]
**[Affected Platforms]:**
- Google Pixel [Android 8.0]
- Samsung S8 [Android 8.0]

**[Prerequisites]:**
- Have the [Send android app](https://drive.google.com/open?id=1STazCrRV5TKD4Q7br-TTYnFQ1nqHIU7Y) installed.

**[Steps to reproduce]:**
1. Open the Send application.
2. Log into the Firefox account.
3. Tap the “Add” button from the bottom right of the screen and tap a file.
4. Tap the “1 day” option and then tap the "7 days" option.
5. Tap the “Ready to Send” button.

**[Expected result]:**
- The file uploads.

**[Actual results]:**
-  The “Sorry, an error occurred” message is displayed

 **[Notes]:**
- This issue is not reproducible with the [Send V2 website](https://send2.dev.lcip.org/).
- Attached a screenshot of the issue:

![rec of the issue - an error occurred](https://user-images.githubusercontent.com/37875464/50010877-3e13f100-ffc3-11e8-8ca2-3ef0fc3b8a52.gif)

**Comment by dannycoates** [comment]
this is directly related to #1040

**Comment by dannycoates** [comment]
fixed in #1075

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) on Samsung S8 and Google Pixel.
