### ISSUE TITLE
[Android] The "Expires after" buttons and "Protect with password" checkbox are displayed too close to the left margin of the screen

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/send#1044]
[Affected Platforms]:
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

[Prerequisites]:
- The sendandroid.apk is installed.

[Steps to reproduce]:
1. Open the Send application and tap the "Add file" button.
2. Observe the "Expires after" buttons and the "Protect with password" checkbox.

[Expected result]:
- The buttons and checkbox are aligned to the left.

[Actual result]:
- The buttons and checkbox are displayed too close to the left margin of the screen.

[Notes]:
- Attached a screenshot of the issue:
![screenshot_20181217-173150](https://user-images.githubusercontent.com/40393891/50097241-1a9ab180-0222-11e9-98bd-863361739945.png)

**Comment by clouserw** [comment]
this is fixed

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using send-android-12-20-18-signed.apk on Android 8.0.0 (Google Pixel and Samsung Galaxy S8).
Considering this I will mark this issue as verified fixed.
