### ISSUE TITLE
[Android] Several elements are wrongly selectable

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/send#1047]
[Affected Platforms]:
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

[Prerequisites]:
- The [sendandroid.apk](https://drive.google.com/file/d/1STazCrRV5TKD4Q7br-TTYnFQ1nqHIU7Y/view) is installed.

[Steps to reproduce]:
1. Open the Send application.
2. Tap and hold the "Sign in/up" button and observe the behavior.

[Expected result]:
- The button is not selectable.

[Actual result]:
- The button is selected and the context menu is opened.

[Notes]:
- The following elements are selectable:
  - The "Sing in/up" button, Background image and strings from the main page.
  - The "Add file(s)", "Ready to Send" and "Copy to clipboard" buttons from the file upload page.
  - The "Copy to URL" button from the uploaded files page.
- Attached a screen recording of the issue:
![select](https://user-images.githubusercontent.com/40393891/50155507-eb914800-02d4-11e9-8cc4-9dd34fe0c211.gif)

**Comment by johngruen** [comment]
@fzzzy can you make a new build for QA to verify

**Comment by dannycoates** [comment]
fixed in #1088

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) on Samsung S8 and Google Pixel.
