### ISSUE TITLE
[Android] The "uploading file" card's width is wrongly scaled according to the file's name length

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/send#1051]
[Affected Platforms]:
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

[Prerequisites]:
- The [sendandroid.apk](https://drive.google.com/file/d/1STazCrRV5TKD4Q7br-TTYnFQ1nqHIU7Y/view) is installed.

[Steps to reproduce]:
1. Open the Send application and tap the "Add file" button.
2. Upload a file with a few number of characters in the name.
3. Observe the "uploading file" card's width.

[Expected result]:
- The "uploading file" card's width is displayed across the entire screen.

[Actual result]:
- The "uploading file" card's width is smaller.

[Notes]:
- The "Your upload has finished" message and the "uploaded file" card are also wrongly scaled.
- Attached a screen recording of the issue:
![width](https://user-images.githubusercontent.com/40393891/50231019-8150d400-03b6-11e9-8b17-588fac8766da.gif)

**Comment by clouserw** [comment]
This is fixed.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using send-android-12-20-18-signed.apk on Android 8.0.0 (Google Pixel and Samsung Galaxy S8).
Considering this I will mark this issue as verified fixed.
