### ISSUE TITLE
[Send v2][Android] No warning message is displayed when clicking the "Sign in/up" button from the "With a free Firefox Account..." overlay while the "Email" field is empty or an incomplete email is entered

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1056]
**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux
- Android 8.0 [Samsung S8; Pixel 8]

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/.
2. Click the "Add file(s)" button and add one file.  
3. Click the "20 downloads" and then select the "50 downloads" option.
4. Click the "Sign in/up" button.

**[Expected result]:**
- The "Email" field is highlighted and a warning message is displayed.

**[Actual results]:**
- Nothing happens.
 
 **[Notes]:**
- This issue is also reproducible on the "Send" Android application ([send-android-12.20.2018](https://drive.google.com/open?id=1h8jJa0kBaOFkslWqay39laVI_oRQZ6Ek)). 
- Issue is also reproducible with an incomplete email (without domain, e.g.: abc@).  
- Clicking the "Sign in/up" button while an incomplete email (without domain, e.g.: abc@) is entered in the "Email" field, the email is cleared.
- Attached a screen recording of the issue:

![rec of the issue - no warning message](https://user-images.githubusercontent.com/37875464/50343605-38248f80-0530-11e9-8d1f-f4e398bfa726.gif)

**Comment by dannycoates** [comment]
Since the email here is just a hint to the fxa server of which ui to show, if the user leaves it blank or fills in an invalid email we should just direct those to fxa without the hint. Its less friction for the user and easier for us. I made this change in a79400f99ff9736baf23b41ce21413b7198b6632
