### ISSUE TITLE
[Android] You are wrongly redirected to the “Webpage not available” page when clicking the "Firefox Send" icon while uploading a file

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1059]
**[Affected Platforms]:**
- Android 8.0 [Samsung S8, Huawei P20 Lite]

**[Prerequisites]:**
- Have the "Send" Android application ([send-android-12-20-18-signed](https://drive.google.com/open?id=1h8jJa0kBaOFkslWqay39laVI_oRQZ6Ek)) installed.

**[Steps to reproduce]:**
1. Open the "Send" application.
2. Tap the "Add" button from the bottom right of the screen and add a file.
3. Tap the "Upload" button.
4. Tap the "Firefox Send" icon and text and observe the behavior of the application.

**[Expected result]:**
- Nothing happens, the file continues to upload.

**[Actual results]:**
- The upload is interrupted and you are redirected to the "Webpage not available" page.
 
 **[Notes]:**
- This issue is not reproducible when clicking the "Firefox Send" icon and text while in the main screen or after the file is uploaded.
- Attached a screen recording of the issue:

![rec of the issue - webpage not available](https://user-images.githubusercontent.com/37875464/50399289-0c4f1700-0787-11e9-8ee2-8024e5ba52cb.gif)

**Comment by clouserw** [comment]
Let's remove the URL link entirely

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) on Samsung S8 and Google Pixel.
