### ISSUE TITLE
[Send v2][Edge] Files can not be added or downloaded and the "Sign up/in" button is not displayed

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1065]
**[Notes]:**
- Clicking inside the "Drop files here" card does not open the "Add files" systems pop-up.
- If you navigate to a link of an uploaded file, the uploaded file section is blank and the "Sign up/in" button is not displayed.  

**[Affected Versions]:**
- Microsoft Edge 42.17134.1.0

**[Affected Platforms]:**
- Windows 10 x64

**[Steps to reproduce]:**
1. Open the Microsoft Edge browser and navigate to https://send2.dev.lcip.org/.
2. Click the "Add file(s)" button.
3. Select a file and click the "Open" button.
4. Observe the left part of the center of the page.

**[Expected result]:**
- The selected file was added and is ready to be uploaded.

**[Actual result]:**
- Nothing changes, the file is not added.

**[Additional Notes]:**
- Attached a screen recording with the issue:

![rec of the issue - edge](https://user-images.githubusercontent.com/37875464/50691180-8a89a400-1038-11e9-8f10-33ed246f95fe.gif)

**Comment by dannycoates** [comment]
Caused by `testpilot-ga` using the `browser` object. We'll likely be removing that dep soon anyway.

**Comment by adamopenweb** [comment]
Our friends at Microsoft reached out about this issue. Passing along the message:
>We investigated and it appears the JS on the page is querying for the existence of window.browser to infer the existence of window.browser.runtime.getBrowserInfo.
>Although we have a partial implementation of window.browser, we don’t support it through to getBrowserInfo.
>We believe changing this check to window.browser.runtime should “just work” across browsers.

**Comment by dannycoates** [comment]
we're still broken in vnext after fixing the `browser.runtime` issue. more work to do. might just be a transpilation issue

**Comment by dannycoates** [comment]
accounts are still not working with edge so i've disable them for now but the rest should work as of 694e05f

**Comment by dannycoates** [comment]
some ui issues remain but Edge should be fully functional as of cccc1a5

**Comment by Softvision-PatriciuPop** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org website, on Windows 10 x64.
