### ISSUE TITLE
[Send v2] Uploads taking longer than ~65 seconds hang

### ISSUE THREAD

**Issue by AlexandruTrif** [mozilla/send#1077]
**[Affected Versions]:**
- Firefox 64 and up
- Safari Version 11.0.3
- Chrome Version 71.0.3578.98
- Opera Version 57.0.3098.106

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a file of 250MB or bigger.

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/ 
2. Click “Add files(s)” and select a file larger than 250MB.
3. Click “Open” and upload the file.
4. Observe the behavior.

**[Expected result]:**
- The file is uploaded.

**[Actual result]:**
- Upload process stops before reaching 100% without a warning.

**[Notes]:**
- This issue is not reproducible if we build the website from the vnext branch and run it on localhost.
- If the file reaches 100% the process stops without actually uploading the file.
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=1lvScGCGD1_B8go4uxioeyL26OzXJ1bR-)

**Comment by dannycoates** [comment]
This looks like a timeout issue after ~60 seconds as opposed to a size issue. This happened before with the load balancer which we fixed and I verified. According to what I can see that LB setting is still set ok at 86400s. @jbuck any ideas? It seems weird that something else would be timing out. Production is using almost the same setup aside from the websocket without issue.

**Comment by johngruen** [comment]
@clouserw also

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is also reproducible with the Send Android build. However, the upload does not always hang after approx. 65 seconds like on the website, it stops after a period of time between approx. 30 and 180 seconds.

**Comment by jbuck** [comment]
#1134 is a patch in-progress that might help solve GCS timeout issues and https://github.com/mozilla-services/cloudops-infra/pull/544 fixes the websocket timeout issue. Both need to be fixed to resolve this issue

**Comment by dannycoates** [comment]
This should be fixed on the dev site as of cd8ab540f2c8514bdc9d6434d54ddd6c52c77698

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org/ website.
