### ISSUE TITLE
Consider a fullpage layout for our download UI

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#1079]
Right now when I get a download URL i see this: 

**With Password**
<img width="1312" alt="screen shot 2019-01-10 at 9 29 20 am" src="https://user-images.githubusercontent.com/3323249/50955902-95ba5500-14ba-11e9-9c85-bbc4d6352a2e.png">

**Without Password**
<img width="1312" alt="screen shot 2019-01-10 at 9 29 52 am" src="https://user-images.githubusercontent.com/3323249/50955903-95ba5500-14ba-11e9-9b4a-89cf2ec11427.png">

It seems like we should have a one-column center aligned layout similar to the copy to clipboard overlay

<img width="1312" alt="screen shot 2019-01-10 at 9 34 02 am" src="https://user-images.githubusercontent.com/3323249/50956006-e336c200-14ba-11e9-8ef8-7f6ed4f8c333.png">

**Comment by youwenliang** [comment]
We can do something like this: (similar to what we have for Send V1)
![send_share download new password](https://user-images.githubusercontent.com/8919308/51099352-1eaef480-180b-11e9-9358-96cf7e6139a4.png)
![send_share download new](https://user-images.githubusercontent.com/8919308/51099353-1eaef480-180b-11e9-951a-ad8738a96e20.png)

**Comment by johngruen** [comment]
Looks great!

**Comment by youwenliang** [comment]
Here's the measurements:
https://mozilla.github.io/testpilot-assets/Send/Firefox_Send_Download/

**Comment by dannycoates** [comment]
FYI, I can't display the filename/size before the password is entered because it's private info and encrypted by the password, but I'll do what I can
