### ISSUE TITLE
Service doesn't notice that copy to clipboard is disabled and that the copy failed

### ISSUE THREAD

**Issue by fmarier** [mozilla/send#108]
Steps:

1. go into `about:config`
2. set `dom.allow_cut_copy` to `false`

Expected:

The "copy" button turns to "failed." or is grayed out.

Actual:

The "copy" button changes to an enthusiastic (but wrong) "copied!".

**Comment by kritisingh1** [comment]
hi @fmarier i would like to work on this issue. can you confirm its status whether its open?

**Comment by ericawright** [comment]
Hi @kritisingh1, the bug is open and good to take. if you run into any issues with the code you can message me and for guidance.
