### ISSUE TITLE
On uploaded bundle cards, time and count is janky

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#1080]
If i set a custom expiry on an uploaded bundle, there's a text flash on the little card ui that starts with default time and count and goes to current. Can we render some kind of loading box there until we have the actual count? and maybe make it a bit more prominent?

**Comment by dannycoates** [comment]
jank fixed in 4a633c8930851379e30362d2560ba83db1f13932

**Comment by dannycoates** [comment]
there's still some a flash of the og count after dls. i can fix it
