### ISSUE TITLE
Add a download button to upload bundle cards

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#1081]
Supports first party downloading for fxa connected users with multiple devices

**Comment by youwenliang** [comment]
Something like this:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/8919308/51025502-5a19ab00-15e0-11e9-9f78-2ae8c2e2dd83.png">

**Comment by dannycoates** [comment]
done as of d159825b27cfaf848d3148de1b237b9daff41730 though size and position may need tweaking
