### ISSUE TITLE
[Android] The file card expands too much when previewing a small number of uploaded files

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/send#1083]
[Affected Platforms]:
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

[Prerequisites]:
- The sendandroid.apk is installed.

[Steps to reproduce]:
1. Open the Send application and tap the "Add file" button.
2. Add 2 files and tap the "Upload" button and wait for the upload to finish.
3. Tap the "Ok" button.
4. Tap the "2 files" button and observe the behavior.

[Expected result]:
- The file card expands and the 2 files are displayed.

[Actual result]:
- The file card expands too much.

[Notes]:
- Attached a screen recording of the issue:
![expand](https://user-images.githubusercontent.com/40393891/50976677-3b8cb480-14f9-11e9-9384-2453f8eb3029.gif)

**Comment by dannycoates** [comment]
this should be fixed as of c1df061669cf2c565b90cfbe818ae004a5d5adc7

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest build (org.mozilla.sendandroid-2019-02-20-release-signed.apk) on Samsung S8, Huawei P20 Lite and Google Pixel(Android 8.0)
