### ISSUE TITLE
[Send v2] The uploaded files while you are logged in are no longer displayed after reconnecting with the same account

### ISSUE THREAD

**Issue by AlexandruTrif** [mozilla/send#1084]
**[Notes]:**
- This issue is not reproducible on Firefox 65 Beta and Nightly 66.0a1. Considering this, using mozregression tool I have found the issue that fixed this in Beta and Nightly. Here is the pushlog: https://tinyurl.com/y97pz33w
- From the provided pushlog it seems that [bug 1389628](https://bugzilla.mozilla.org/show_bug.cgi?id=1389628) fixed this issue in Beta and Nightly.

**[Affected Versions]:**
- Firefox 64

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a valid account with at least one file uploaded.

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/.
2. Log out from the FxA account.
3. Click the sign in button and log in again with the account from the prerequisites.
4. Observe the right part of the center of the page.

**[Expected result]:**
- The previously uploaded files are displayed.

**[Actual result]:**
- No files are displayed.

**[Additional Notes]:**
- This issue is not reproducible on Chrome, Opera and Safari browsers.
- The issue is again reproducible with “javascript.options.streams” set to “false”.
- Attached a screen recording of the issue: https://tinyurl.com/y9ae2o6w

**Comment by dannycoates** [comment]
it should be fixed by 8e8570c357ca252bde5252ee2bd298ac3c3249f3

**Comment by AlexandruTrif** [comment]
I have verified this issue and is no longer reproducible on the "https://send2.dev.lcip.org/" page on Windows 10x64, Ubuntu 18.04.1 and Mac 10.13.3.
