### ISSUE TITLE
[Android] The "Add File" button is not grayed out during an upload

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/send#1089]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

**[Prerequisites]:**
- Have the latest version of the "Firefox Send" application (app-release-signed) from 12/20/2018 installed.
- Have at least two files saved on your device.

**[Steps to reproduce]:**
1. Open the Send application.
2. Tap the "Add File" button and select a file from prerequisites. 
3. Tap the "Upload" button and tap the "Add File" button again.
4. Observe the behavior

**[Expected result]:**
- Nothing happens, the "Add File" button is grayed out.

**[Actual result]:**
- The "File Selection" screen is opened.

**[Notes]:**
- If after following the steps from above, you will select a file, the file will be not added to the upload list.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/51037480-03e54180-15b9-11e9-904d-b94d37b12679.gif)

**Comment by johngruen** [comment]
We should make it go away while upload is happening
