### ISSUE TITLE
Files can no longer be uploaded if you cancel the "Sign In" window displayed after selecting an expire method that requires log in

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/send#1090]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

**[Prerequisites]:**
- Have the latest version of the "Firefox Send" application (app-release-signed) from 12/20/2018 installed.
- Have at least a file saved on your device.

**[Steps to reproduce]:**
1. Open the Send application.
2. Tap the "Add File" button and select a file from prerequisites. 
3. Go to the "Expires after" section and tap the "1 download" button.
4. Choose an option equal or over 50 downloads and tap the "Sign In" window's "Cancel" button.
5. Tap the "Upload" button and observe the behavior.

**[Expected result]:**
- The file is uploaded.

**[Actual result]:**
- An error occurs at upload.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/51044816-b70a6680-15ca-11e9-983f-c138da5d4518.gif)

**Comment by fzzzy** [comment]
@Softvision-MariusComan This seems to have been fixed, can you verify? If I choose over 50 downloads and then cancel the sign in window, it goes back to 20, and if I choose over 1 day and then cancel it goes back to 1 day.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Send" application (firefox-send-signed-jan-17-2019-2) installed. Verified on Samsung S8 (Android 8.0.0) and Pixel (Android 8.0.0).
