### ISSUE TITLE
[Send v2] The “Sign in/up” button on download page doesn’t work

### ISSUE THREAD

**Issue by AlexandruTrif** [mozilla/send#1093]
**[Affected Versions]:**
- Firefox 66.0a1
- Chrome 71.0.3578.98
- Opera 57.0.3098.116

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a download link from a previously uploaded file.

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to download link from prerequisites.
2. Click the “Sign in/up” button and observe the behavior. 
3. Click “Firefox Send” and observe the behavior. 

**[Expected result]:**
- Step 2: The Sign in/up overlay is displayed.
- Step 3: You are redirected to the homepage. 

**[Actual result]:**
- Step 2: Nothing happens. 
- Step 3: The Sign in/up overlay is displayed.

**[Notes]:**
- The issue is also reproducible on the “https://send2.dev.lcip.org/404” page.
- Attached a screen recording of the issue:
![no signin](https://user-images.githubusercontent.com/46520844/51115638-7f413000-1811-11e9-955c-7a6f158927c7.gif)

**Comment by dannycoates** [comment]
fixed in 5eb24065b6f88bdd228bdc46479ba0dca1d071d3
