### ISSUE TITLE
[Send v2] Previously added files are no longer displayed after signing into FxA

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1095]
**[Affected Versions]:**
- Firefox 64 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/.
2. Click the "Add file(s)" button.
3. Select a file and click the "Open" button.
4. Change the "1 day" option to the "7 days" option.
5. Sign in and then observe the section of the added files.

**[Expected result]:**
- The previously added files are displayed.

**[Actual result]:**
- No files are displayed.

**[Notes]:**
- This issue is also reproducible if we build the website from the vnext branch and run it on localhost.
- This issue is also reproducible when the login is made through the "Sign in/up" button while having added files.
- This issue is also reproducible when the login is made through the "Sign in/up" overlay while having added files.
- Attached a screen recording with the issue:

![rec of the issue - added files](https://user-images.githubusercontent.com/37875464/51187270-22fb1080-18e4-11e9-8cbc-7a7d2c9b79f5.gif)

**Comment by dannycoates** [comment]
Unfortunately, it isn't possible to save the list of pending files across page reloads. We need the file handles to do the upload but that requires a user action (file picker or d&d)
