### ISSUE TITLE
[Send v2] Several buttons do not have hover effects

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1103]
**[Notes]:**
- This issue is reproducible with the following buttons:
  -  All “Delete” buttons: for added, uploaded files.
  - “Legal”, “Terms”, “Cookies”, Report IP Infringement” and “GitHub” links from the footer of the page.
  - “Cancel” button from the Sign in/up overlay.

**[Affected Versions]:**
- Firefox 64 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/.
2. Click the "Add file(s)" button.
3. Select a file and click the "Open" button.
4. Hover the added files “X” button and observe its behavior.

**[Expected result]:**
- The button has a hover effect.

**[Actual result]:**
- The button remains the same. 

**[Additional Notes]:**
- Attached a screen recording with the issue:

![rec of issue - hover effect button](https://user-images.githubusercontent.com/37875464/51329113-718fe280-1a7d-11e9-8786-f84d88e78afd.gif)

**Comment by johngruen** [comment]
maybe we just `text-decoration:underline` for links, but i don't think icons need anything but `cursor:pointer`

**Comment by dannycoates** [comment]
i tried the underline and _meh_. The text now gets darker on hover but it's subtle. I think it looks fine.

**Comment by Softvision-PatriciuPop** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org website, on Windows 10 x64, Mac 10.14 and Ubuntu 18.04.
