### ISSUE TITLE
[Send v2] Several buttons do not have tooltips

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1104]
**[Notes]:**
- This issue is reproducible with the following buttons:
  -  All “Delete” buttons: for added, uploaded files.
  - “Cancel upload” button.
  - “Sign in/up” button from the overlay.
  - “Copy to clipboard” and “Ok” buttons from the “Your upload has finished” overlay

**[Affected Versions]:**
- Firefox 64 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/.
2. Click the "Add file(s)" button.
3. Select a file and click the "Open" button.
4. Hover the “Delete” button of the file and observe its behavior.

**[Expected result]:**
- The button has a tooltip.

**[Actual result]:**
- No tooltip is displayed. 

**[Additional Notes]:**
- Attached a screen recording with the issue:

![rec of issue - tooltips](https://user-images.githubusercontent.com/37875464/51329186-a308ae00-1a7d-11e9-8757-5168cdcdd4c3.gif)

**Comment by dannycoates** [comment]
fixed in f0a60d8c8e70ad7855ec64979d4388a556cd2367

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org website, on Windows 10 x64, Mac 10.14 and Arch Linux.
