### ISSUE TITLE
[Send v2] Several buttons can not be focused with the keyboard

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1105]
**[Notes]:**
- This issue is reproducible with the following buttons:
  - The “Ok” from the “Your upload has finished” overlay
  - The “Sign in/up” button from the overlay
  - The “Add file(s)” button
- The hover effect is wrongly used instead of the focus effect when focusing the buttons with the keyboard, according to the Photon Design System.
- Although the “Delete” buttons can be focused with the keyboard because they don’t have a hover effect, the focus is not visible. 
    
**[Affected Versions]:**
- Firefox 64 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/.
2. Press the “Tab” key until the “Sign in/up” button is focused.
3. Press the “Tab” key once and observe the behavior.

**[Expected result]:**
- The “Add file(s)” button is focused.

**[Actual result]:**
- The “moz://a” button is focused. 

**[Additional Notes]:**
- Attached a screen recording with the issue:

![rec of issue - accessibility](https://user-images.githubusercontent.com/37875464/51329256-d0edf280-1a7d-11e9-8c21-499977a106ae.gif)

**Comment by dannycoates** [comment]
fixed as of 2169a49d4cc05bfe317e59abc8470faf1f3d0656

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org website, on Windows 10 x64, Mac 10.14 and Arch Linux.
