### ISSUE TITLE
[Send v2] Inactive vertical scroll bars are wrongly displayed in the right part of added/uploaded files

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1107]
**[Affected Versions]:**
- Firefox 64 and up
- Chrome 71.0.3
- Opera 57.0.3
- Safari 11.0.3

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org/.
2. Click the "Add file(s)" button.
3. Select a file and click the "Open" button.
4. Observe the added files section. 

**[Expected result]:**
- Only the added file and the “Add file(s)” button are displayed.

**[Actual result]:**
-  An inactive vertical scroll bar is displayed in the right part of the added files section.

**[Notes]:**
- Inactive scroll bars are also displayed in the right part of the uploaded files, and the uploaded files section.
- On Firefox: If you have several uploaded files and their list is displayed, after you click the “Copy URL” button the vertical scroll bar becomes active. 
- On Chrome and Opera: If you have several uploaded files and their list is displayed an extra horizontal active scroll bar is displayed below.
- Attached a screen recording with the issue:

![rec of issue - scroll bar](https://user-images.githubusercontent.com/37875464/51394606-6a330c80-1b43-11e9-8212-498045238ef2.gif)

**Comment by dannycoates** [comment]
should be fixed in c0d8300a8eda94411e7c5761ad32c0cd55732df1

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the "https://send2.dev.lcip.org/" page on Windows 10x64, Arch Linux and Mac 10.14.2.
