### ISSUE TITLE
[Android] The text and the “Cancel” button from the “Sign in/up” overlay are not fully visible while the keyboard is displayed.

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1108]
**[Affected Platforms]:**
- HTC 10
- Samsung S8
- Google Pixel 

**[Prerequisites]**
- Have the Send Android latest build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed. 

**[Steps to reproduce]:**
1. Open the “Send” application.
2. Add one file and then change the 1 day expiration time option to 7 days.
3. Observe the displayed overlay.

**[Expected result]:**
- The text from the overlay and the buttons are fully visible. 

**[Actual result]:**
-  The first line of the text and the “Cancel” button are not displayed.

**[Notes]:**
- The displayed elements from the “Sign in/up” overlay are influenced by the size of the device’s display and screen’s resolution:
   - On Google Pixel (5” Display, Screen resolution: 1080x1920 pixels) the first line of the text and the “Cancel” button are not displayed. Also when scrolling down the “Upload” button is displayed. 

   - Attached a screen recording:
   - ![rec of issue -google pixel](https://user-images.githubusercontent.com/37875464/51396802-808f9700-1b48-11e9-9eea-faff57763ce1.gif)

   - On HTC 10 (5.2” Display, Screen resolution: 1440x2560 pixels)  the first line of the text, the “Sign in/up” button and the “Cancel” button are not displayed.  Also when scrolling down the “Upload” button is displayed.

   - Attached a screen recording:

   - ![rec of issue - htc 10](https://user-images.githubusercontent.com/37875464/51396818-87b6a500-1b48-11e9-8d7c-884e0177da10.gif)

   - On Samsung S8 (5.8” Display, Screen resolution: 1440x2960 pixels) the text is correctly displayed but only the top part of the “Cancel” button is displayed. The view can not be scrolled while the keyboard is displayed.

   - Attached a screen recording:

   - ![rec of issue - samsung s8](https://user-images.githubusercontent.com/37875464/51396830-8eddb300-1b48-11e9-803f-08668b875b2f.gif)

**Comment by dannycoates** [comment]
fixed in #1140

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-02-11.apk), tested on Samsung S8, Huawei P20 Lite and Google Pixel (Android 8.0)
