### ISSUE TITLE
[Android] Previously uploaded files from an account are not displayed after reconnecting with the same account

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1110]
**[Affected Platforms]:**
- Samsung S8
- Google Pixel
- Huawei P20 Lite

**[Prerequisites]**
- Have the Send Android latest build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed. 
- Have a FxA account with one or more uploaded file.

**[Steps to reproduce]:**
1. Open the “Send” application.
2. Sign in with the account from prerequisites.
3. Observe the page's content.

**[Expected result]:**
- The previously uploaded files are displayed.

**[Actual result]:**
-  No files are displayed.

**[Notes]:**
- The previously uploaded files are redisplayed after you upload another file while logged into the same account.
- This issue is not reproducible on the [Send V2 website](https://send2.dev.lcip.org/).
- Attached a screen recording: [Link](https://drive.google.com/open?id=1N0l-XhpT11RWuK7f8nW1c0vsoxDJhcil).

**Comment by dannycoates** [comment]
fixed in #1142

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-02-11.apk), tested on Samsung S8, Huawei P20 Lite and Google Pixel (Android 8)
