### ISSUE TITLE
A corrupted file is created when trying to share an already uploaded file with the "Send" application

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/send#1113]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

**[Prerequisites]:**
- Have the Send Android latest build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed. 
- Have at least a file saved on your device.

**[Steps to reproduce]:**
1. Open the Send application.
2. Tap the "Add File" button and select the file from prerequisites. 
3. Tap the "Upload" button and choose the "Ok" option.
4. Tap the "Share" button from the previously uploaded file.
5. Choose the "Send" application from the list and tap the "Ok" button after the upload is finished.
6. Observe the behavior.

**[Expected result]:**
- Only the uploaded file is displayed.

**[Actual result]:**
- A corrupted file that cannot be deleted is also created.

**[Notes]:**
- The corrupted files are still displayed even if the "Send" application is restarted.
- If you are connected with a FxA account, the corrupted files cannot be deleted even if you will try to delete them from the web version of the "Send" application.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/51537291-ca34f600-1e56-11e9-9ef3-46713593662d.gif)

**Comment by dannycoates** [comment]
The second "file" is the share link. Can we prevent the share dialog from including us when we are the source?

**Comment by dannycoates** [comment]
we removed Send from the list of share targets when triggered by us

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-02-06-signed.apk) on Samsung S8 and Google Pixel. The Send application is no longer displayed in the Share list
