### ISSUE TITLE
[Android] The email address added in the “Sign in/up” overlay is not displayed on the FxA sign in page at first sign in

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1114]
**[Notes]:**
- If you were previously signed in with one account and you are adding a second account in the “Email” field and tap the “Sign in/up” button, the first email will be displayed on the FxA page. 
- This issue is similar to [#937](https://github.com/mozilla/send/issues/937).

**[Affected Platforms]:**
- Samsung S8
- Google Pixel
- Huawei P20 Lite

**[Prerequisites]**
- Have the Send Android latest build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed. 
- Have no previous sign in on the Send application.
- Have a valid FxA.

**[Steps to reproduce]:**
1. Open the “Send” application.
2. Tap the “Sign in/up” button and fill the “Email” field with the email from the prerequisites.
3. Tap the “Sign in/up” button from the overlay and observe the “Email” field content.

**[Expected result]:**
- The email added to the “Email” field from the “Sign up/in” overlay is displayed. 

**[Actual result]:**
-  The field is empty.

**[Additional Notes]:**
- This issue is not reproducible on the [Send v2 website](https://send2.dev.lcip.org/)
- Attached a screen recording with the issue: [Link](https://drive.google.com/open?id=1pZsPHeRB7Zj_X6ASX2BTvRReMAQqaDF5)

**Comment by dannycoates** [comment]
fixed in #1140

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-02-11.apk), the email field is no longer displayed on the "Sign in/up" overlay. Tested on Samsung S8, Huawei P20 Lite and Google Pixel (Android 8)
