### ISSUE TITLE
A "Log In" window is wrongly opened for each time the "Sign in/up" button is tapped

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/send#1115]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

**[Prerequisites]:**
- Have the Send Android latest build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed. 

**[Steps to reproduce]:**
1. Open the Send application.
2. Tap the "Sign in/up" button from the top right part of the screen. 
3. Tap the "Sign in/up" button for multiple times and observe the behavior.

**[Expected result]:**
- Only one "Log In" window is opened.

**[Actual result]:**
- A "Log In" window is wrongly opened for each time the "Sign in/up" button was tapped.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/51541161-cdcd7a80-1e60-11e9-8bc6-0bf84c7548a0.gif)

**Comment by dannycoates** [comment]
fixed in #1140

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-02-11.apk), tested on Samsung S8, Huawei P20 Lite and Google Pixel (Android 8)
