### ISSUE TITLE
[Android] The main view of the “Send” application can wrongly be swiped up

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1116]
**[Affected Platforms]:**
- Samsung S8
- Google Pixel
- Huawei P20 Lite

**[Prerequisites]**
- Have the Send Android latest build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed. 

**[Steps to reproduce]:**
1. Open the “Send” application.
2. Swipe up the view and observe the behavior.

**[Expected result]:**
- Nothing happens. 

**[Actual result]:**
-  The view is swiped up and a light blue background is displayed at the bottom of the screen.

**[Additional Notes]:**
- Attached a screen recording with the issue:

![rec of issue - swipe](https://user-images.githubusercontent.com/37875464/51543831-2738a800-1e67-11e9-89c0-522a30cfd4e4.gif)

**Comment by johngruen** [comment]
We need to knock out the margin-bottom on that main box

**Comment by fzzzy** [comment]
This seems to be fixed now, @Softvision-AndreeaCupsa can you verify?

**Comment by Softvision-AndreeaCupsa** [comment]
Yes, this is now fixed. I have verified this issue with the latest Send Android build (org.mozilla.sendandroid-2019-02-06-signed.apk) on Samsung S8, Google Pixel, and Huawei P20Lite.
