### ISSUE TITLE
You are not logged in if the "Send" app is sent to the background or the phone screen is locked, right after the "Log in" window is closed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/send#1117]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)

**[Prerequisites]:**
- Have the Send Android latest build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed. 
- Have valid FxA credentials.

**[Steps to reproduce]:**
1. Open the Send application.
2. Tap the "Sign in/up" button from the top right part of the screen. 
3. Enter the email from prerequisites and tap the "Sign in/up" button.
4. Enter your password and tap the "Sign in" button.
5. Lock the phone screen right after the "Sign In" window is closed.
6. Unlock the phone and observe the login status.

**[Expected result]:**
- You are successfully logged in.

**[Actual result]:**
- You are not connected to your account.

**[Notes]:**
- This issue is also reproducible if the application is sent to background, you switch to another application and back or if the internet connection is lost.
- This issue is still reproducible after the application is restarted.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/51543977-85fe2180-1e67-11e9-991c-33c1ee5b0b5e.gif)

**Comment by fzzzy** [comment]
Unfortunately I don't think there is anything we can do about this. It's just the way mobile platforms kill background apps. If there is a way to request from android that the app continue running in the background please let me know.
