### ISSUE TITLE
[Send v2] You can not paste text in the “Email” field from the “Sign in/up” overlay

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1120]
**[Affected Versions]:**
- Firefox 64 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux 

**[Prerequisites]:**
- Have a string copied to clipboard.

**[Steps to reproduce]:**
1. Open the Firefox Browser and navigate to https://send2.dev.lcip.org/
2. Click the “Sign In/Up” button.
2. Paste the string inside the “Email” field and observe the behavior.

**[Expected result]:**
- The text is pasted in the “Email” field.

**[Actual result]:**
- The “Email” field is empty and a file named “pasted.txt” is added to the added file section.

**[Additional Notes]:**
- This is not reproducible with the “Password” fields.
- Attached a screen recording with the issue:

![rec of issue - email field](https://user-images.githubusercontent.com/37875464/51616628-2c632900-1f33-11e9-9085-b6a55d17f570.gif)

**Comment by johngruen** [comment]
Lame

**Comment by dannycoates** [comment]
fixed in 87a517a169f54c834a95d14ec2c9879c8e12b46f

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the "https://send2.dev.lcip.org/" page on Windows 10x64, Arch Linux and Mac 10.14.2.

**Comment by Fanolian** [comment]
I cannot paste my email on the field on either https://send2.dev.lcip.org/ or https://send.firefox.com/ using Nightly 2019-03-12 (new profile) or Chrome 72 (guest account). Edge on Win1809 is not affected though.

**Comment by dannycoates** [comment]
Thanks @Fanolian. This will be fixed in our next release.
