### ISSUE TITLE
[Send v2] Text can wrongly be pasted in the add file section and uploaded

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1121]
**[Affected Versions]:**
- Firefox 64 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux 

**[Prerequisites]:**
- Have a string copied to clipboard.

**[Steps to reproduce]:**
1. Open the Firefox Browser and navigate to https://send2.dev.lcip.org/
2. Press the “Ctrl” + “V” keys and observe the behavior.

**[Expected result]:**
-  Nothing happens.

**[Actual result]:**
- A file named “pasted.txt” is added.

**[Notes]:**
- The “pasted.txt” file can also be uploaded.
- Trying to paste in the “Email” field from the “Sign In/Up” overlay will also add a file name “pasted.txt” in the added files section. See issue: #1120 
- Attached a screen recording with the issue:

![rec of issue - paste](https://user-images.githubusercontent.com/37875464/51616766-7815d280-1f33-11e9-9291-678766fa1d81.gif)

**Comment by dannycoates** [comment]
This is intentional

**Comment by johngruen** [comment]
Easter egg!
