### ISSUE TITLE
[Integration-Test] [Send-v2] Test uploaded file size matches download

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/send#1130]
## Test overview
* This test should check that the downloaded file size matches the uploaded file size.

### Test Steps
Action | Result
------------ | -------------
 Navigate to Send Homepage | Send homepage loads
Upload a file and click the "Upload" button | File is Uploaded
Navigate to file download URL and download file | File downloads
Check file size on disk | File size matches uploaded file

The file size should be checked on disk for both the uploaded and downloaded file, not using the size displayed via the UI. This test should probably exist within the ```download-tests.js``` file.

**Comment by mgalicer** [comment]
Hey there! @KarthikNayak and I are picking this up.
