### ISSUE TITLE
Different icons are used for the default user in the Android app and the Send v2 website

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1136]
**[Affected Versions]:**
- Firefox 64 and up
- Android 8.0

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Send Android build ([firefox-send-signed-jan-17-2019-2](https://drive.google.com/open?id=1XvhcNO1iGdPOf6uX8vxPTCkYVO7vfeig)) installed.
- Have a Firefox account with no profile avatar set and be logged in with it on on the Android application and on the website. 

**[Steps to reproduce]:**
1. Open the Firefox Browser and navigate to https://send2.dev.lcip.org/.
2. Observe the icon from the right part of the header. 
3. Open the Send application and observe the right part of the header.

**[Expected result]:**
Step 2 & 3. Either the default user icon or the Firefox icon is displayed for both.

**[Actual result]:**
Step 2. The Firefox icon is displayed.
Step 3. The default user icon is displayed.

**[Notes]:**
- Attached screenshots with the issue:

Android:
![android](https://user-images.githubusercontent.com/37875464/52332796-583ae000-2a04-11e9-8898-691510374104.jpg)

Website:
![send v2 website](https://user-images.githubusercontent.com/37875464/52332808-5c66fd80-2a04-11e9-8e6d-f24ae18d2b61.png)

**Comment by dannycoates** [comment]
we'll use the default avatar on the web instead of the ff logo.
fixed in 6b33192a55dc3e1410e691d9bc360f459b135869

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible. Now the default user icon is displayed when the user doesn't have set a profile avatar on both the Send Android application and the Send v2 website.
