### ISSUE TITLE
Progress bar doesn't fill up in microsoft edge

### ISSUE THREAD

**Issue by abhinadduri** [mozilla/send#114]
<img width="1680" alt="screen shot 2017-06-22 at 10 08 07 am" src="https://user-images.githubusercontent.com/4949139/27446688-60c2c5b2-5733-11e7-8cea-e544aee2f45c.png">

**Comment by dnarcese** [comment]
IE and Edge do not support CSS variables... but this progress bar will likely change with new UI anyways.
