### ISSUE TITLE
Application stuck in blank screen when returning from file selector after signing in

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/send#1145]
**[Affected Platforms]:**
- Android 8.0 (Samsung S8)
- Android 8.0 (Google Pixel) Huawei P20 Lite

**[Prerequisites]:**
- Have the latest Send Android build (org.mozilla.sendandroid-2019-02-06-signed.apk)
- You are not logged in.
- Have valid FxA credentials.

**[Steps to reproduce]:**
1. Open the Send Android application.
2. Tap the “Sign in/up” button and enter the email from prerequisites.
3. Tap the “Sign in/up” button and enter the password from prerequisites.
4. Tap the "Sign in" button and tap the "Add file/s" button.
5. Tap the device's "Back" button "4" times and observe the behavior.

**[Expected result]:**
- Nothing happens or the application is sent to the background.

**[Actual result]:**
- The application remains stuck in blank screen.

**[Notes]:**
- This issue is not reproducible if you were already logged before following the steps.
- This issue is not reproducible on Huawei P20 Lite.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/52491095-f4184780-2bce-11e9-86c0-b1520a392b58.gif)

**Comment by dannycoates** [comment]
fixed in a42cec9

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest build (org.mozilla.sendandroid-2019-02-20-release-signed.apk) on Samsung S8, Huawei P20 Lite and Google Pixel(Android 8.0).
