### ISSUE TITLE
This link has expired or never existed in the first place!

### ISSUE THREAD

**Issue by Szarad** [mozilla/send#1149]
Hi,

I am sorry if it not a right place to write about it.
I was trying to use the send secure tool, but I have problem with uploading the file.
It always redirecting me to notFound page, error in browser : "POST http://localhost:1443/api/info/fc6f2ba2a4 404 (Not Found)"
After some hustle with code (changing port,changing environment-> it would be great if you will update the documentation) I have still had my issue.
Could you gave me some direction, tips what it could be? I don't exactly understand the mechanism, that it stores the file in tmp directory, but for me it is not storing anything, just creating directory, so probably this is the reason that the program cannot find the uploaded filed. 

I would appreciate any help and guide.

Cheers,
Karolina

**Comment by dannycoates** [comment]
I'll need a little more information in order to help. Please run `npm install` and `npm start` from a fresh clone and let me know if you can upload a file on `http://localhost:8080`.

You can specify a file directory with the environment variable `FILE_DIR`, for example `FILE_DIR=/Users/me npm start`.

**Comment by Szarad** [comment]
Hi, Thank you so much for contact!
Ok, I done what you asked me for, but the page is not working.
But in the package.json file, there is a line like: 
` "start": "npm run clean && npm run build && npm run prod"`
and the page is working on 1443, where production is and upload on that port is also not working.

**Comment by jowy** [comment]
I just ran in to this. It appears that the file is being removed immediately after the upload request has complete [here](https://github.com/mozilla/send/blob/befbd8c1c59728ddf868d81de40ddbf4614279dd/server/routes/upload.js#L46). Is this intentional? Should this be a failure mode instead?

**Comment by jowy** [comment]
Just realized this is to catch aborted requests (e.g. cancel button on web ui) but both `close` and `aborted` events always appear to be firing upon successful request. Digging in to this further.

**Comment by jowy** [comment]
This `close` event issue does not seem to affect node `<= v8.15.1`. It appears to start at node `v9`

It appears that specifically the `aborted` event always firing started sometime in `node v11` and was resolved in node `v11.10.1` (https://github.com/nodejs/node/commit/1980a36dd45997e9dee03fe11688319c2f5c3644#diff-e3bc37430eb078ccbafe3aa3b570c91a)[here]. The `close` event still seems to always be firing, which makes sense, however this is not actually an `http.ClientRequest` event per the docs, then again nor is `aborted` (`abort` is, but it doesn't seem to do anything).

Anyhow, using the `aborted` event appears to work for `< v11` and `>= v11.10.1`.

Should I make a pull request?

**Comment by johngruen** [comment]
We believe this is fixed...please re-open if not
