### ISSUE TITLE
Different file limitations are displayed in the Android app and the Send v2 website

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1150]
**[Affected Platforms]:**
- Android 8.0 (Samsung S8, Google Pixel, Huawei P20 Lite)
- Firefox 65 and up

**[Prerequisites]:**
- Have the latest Send Android build (org.mozilla.sendandroid-2019-02-11.apk) installed on the device.

**[Steps to reproduce]:**
1. Open the Firefox Browser and navigate to https://send2.dev.lcip.org/.
2. Click the “Add file(s)” button and select over 64 files.
3. Click the “Open” button and observe the displayed message.
4. Open the Send application and tap the “Add file(s)” button.
5. Select over 32 files and tap the “Open” button. 
6. Observe the displayed message.

**[Expected result]:**
Step 3&6. The same error message is displayed for both.

**[Actual result]:**
Step 3. The “Only 64 files can be uploaded at a time” error message is displayed.
Step 6. The “Only 32 files can be uploaded at a time” error message is displayed.

**[Notes]:**
- Attached screenshots with the issue:

Android
![screenshot_20190213-104301_20190213_145523033](https://user-images.githubusercontent.com/37875464/52713296-9a819580-2f9f-11e9-967d-a8cc1ef210f1.jpg)

Website 
![website](https://user-images.githubusercontent.com/37875464/52713303-9e151c80-2f9f-11e9-93e2-5b3b76f278c5.png)

**Comment by dannycoates** [comment]
fixed in fd3caa3

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible, now both the Send Android application and the https://send2.dev.lcip.org website have the same file limitation.
