### ISSUE TITLE
[Send v2][Chrome][Opera] The user is not immediately signed out when clicking the “Sign Out” button

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1151]
**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Affected Versions]:**
- Chrome (Version 72.0.3626.109)
- Opera (Version:58.0.3135.65)

**[Prerequisites]:**
- Have a valid Firefox Account and be logged in on the https://send2.dev.lcip.org/ website. 

**[Steps to reproduce]:**
1. Open the browser from the prerequisites and navigate to https://send2.dev.lcip.org/.
2. Click the user icon and click the “Sign Out” button.  
3. Observe the behavior.

**[Expected result]:**
- The user is signed out, the user icon changes into the “Sign In/Up” button.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- This issue is not reproducible on Firefox 65 and up, and on Safari. 
- After refreshing the page or adding a file, the user is signed out. 
- Attached a screen recording with the issue:

![rec of issue - log out](https://user-images.githubusercontent.com/37875464/52864817-b02fc000-3143-11e9-8ce5-480363e94df8.gif)

**Comment by dannycoates** [comment]
fixed in 8eaacfea18545fcb3537f2e5466acf1032f89d35

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org on Google Chrome and Opera.
