### ISSUE TITLE
Update dev+stage URLs in README and contribute.json

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#1161]
Looks like https://github.com/mozilla/send#testing and the [/public/contribute.json](https://github.com/mozilla/send/blob/d6bfb8b1fdf6d758764c00422c72b2b63162ed05/public/contribute.json#L16-L20) point to some old mozaws.net URLs that were 404ing when I clicked on them.

https://github.com/mozilla/send/blob/d6bfb8b1fdf6d758764c00422c72b2b63162ed05/public/contribute.json#L16-L20

**Comment by jatinkumarg** [comment]
Hey, can I update the links?

**Comment by johngruen** [comment]
@jatinkumarg we don't know them yet
