### ISSUE TITLE
[Send 2] The “Download” button from the uploaded card does not have a tooltip

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1163]
**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Affected Versions]:**
- Firefox 65 and up

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to the https://send2.dev.lcip.org website.
2. Upload one file. 
3. Hover the “Download” button from the uploaded card and observe its behavior.

**[Expected result]:**
- The button has a tooltip.

**[Actual result]:**
- No tooltip is displayed.

**[Additional notes]:**
- Attached a screen recording with the issue:

![rec of issue - download tooltip](https://user-images.githubusercontent.com/37875464/53166991-56b21000-35df-11e9-96de-1eaa580074dc.gif)

**Comment by dannycoates** [comment]
fixed in 6fd3019. i missed this on cuz its a link not a button

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org website, on Windows 10 x64, Mac 10.14 and Arch Linux.
