### ISSUE TITLE
Learn More link goes to Test Pilot EOL message

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/send#1169]
The learn more link on send.firefox.com takes visitors to the send page on Test Pilot. However, the send page on Test Pilot redirects to the EOL message for Test Pilot. 

The learn more link should link to information that helps visitors learn more about Send.

**Comment by dannycoates** [comment]
Thanks for the report. We'll be releasing a new version that'll remove the link to Test Pilot soon.
