### ISSUE TITLE
[Android] White spaces are wrongly displayed in the bottom corners of the screen

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1171]
**[Affected Platforms]:**
- Android 8 [Samsung S8, Huawei P20 Lite, Google Pixel]

**[Prerequisites]:**
- Have the latest Send Android application (org.mozilla.sendandroid-2019-02-20-release-signed.apk) installed on the device.

**[Steps to reproduce]:**
1. Open the Send Android application.
2. Tap the “Add file(s)” button and select one file.
3. Observe the “Upload” button.

**[Expected result]:**
- The “Upload” button is not as wide as the screen.
or 
- The button has no border-radius. 

**[Actual result]:**
- White spaces are displayed in the bottom corners of the screen.

**[Notes]:**
- Attached a screenshot with the issue:

![1551184192325](https://user-images.githubusercontent.com/37875464/53413175-f7377400-39d3-11e9-9d0c-26ec24dbecc1.JPEG)

**Comment by johngruen** [comment]
@Softvision-AndreeaCupsa can you verify and close?

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-03-01-release-signed.apk) on Samsung S8, Google Pixel, and Huawei P20 Lite.

Considering this I will close this issue.
