### ISSUE TITLE
To add an ability to copy link by clicking on the text box

### ISSUE THREAD

**Issue by stealthanthrax** [mozilla/send#1187]
To add an ability to copy the link by clicking on the text-box

<img width="1096" alt="screenshot 2019-03-05 at 1 52 10 am" src="https://user-images.githubusercontent.com/29942790/53760681-9f27d280-3ee9-11e9-8178-e49e9ac4881c.png">

If the feature request is approved, I would like to work on this.

**Comment by stealthanthrax** [comment]
@dannycoates @abhinadduri , can I implement this feature

**Comment by fzzzy** [comment]
@stealthanthrax Why copy when clicking on the text box and not the copy button? Seems unexpected.

**Comment by stealthanthrax** [comment]
@fzzzy , it is because the text box is almost un-interactive and adding this feature will add value to the text-box. I am not suggesting to remove the copy button, just to add the ability in the textbox as well. Many modern websites have this feature.

**Comment by johngruen** [comment]
I think we've decided not to fix this for the moment
