### ISSUE TITLE
[Send 2] The "Feedback" button wrongly redirects to an incomplete "Feedback" page 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#1189]
[Notes]:
- Probably the survey is not yet finalized, but I have logged this issue for tracking purpose.

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Affected Versions]:**
- Firefox 65 and up

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to "https://send2.dev.lcip.org/" website.
2. Click the "Feedback" button from the footer of the page.
3. Observe the "Feedback" page.

**[Expected result]:**
- The "Feedback" page is displayed and the survey can be completed.

**[Actual result]:**
- The "Thank You" message is displayed and the survey is 100% completed.

**[Additional notes]:**
- Attached a screen recording with the issue:
![send feedback](https://user-images.githubusercontent.com/19226534/53809766-139c5900-3f5e-11e9-870d-b99ce54df142.gif)

**Comment by johngruen** [comment]
fixed

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org website on Windows 10 x64, Arch Linux, Mac 10.14.3
