### ISSUE TITLE
Pass incoming utm parameters through

### ISSUE THREAD

**Issue by clouserw** [mozilla/send#1191]
There's going to be a marketing campaign behind the new Send launch and we'd like to know which ones are successful.  They'll be coming in with utm parameters (eg. a link in an email), and we should pass those incoming utm parameters to amplitude.

**Comment by johngruen** [comment]
Part one is capture UTMs on inbound client visit events
client_visit
event_properties -> 5x UTM params and referrer

Part two is send them to FxA
https://mozilla.github.io/application-services/docs/accounts/metrics.html
to fxa we should send
entry = `send-{something}`
form_type = `email`
5x UTM if avail

**Comment by dannycoates** [comment]
done as of e7b881e9752e989a9348a2c7052eb7f71efd766c
