### ISSUE TITLE
[Send2] Files of exactly 1GB can wrongly be added while you are not logged into FxA

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1193]
**[Notes]:**
- If you try to upload the file, it will remain stuck at 100% progress and you can not cancel the upload.

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Affected Version]:**
- Firefox 65 and up

**[Prerequisites]:**
- Have a file of exactly 1GB saved to your PC.

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://send2.dev.lcip.org.
2. Add the files from the prerequisites and observe the behavior. 

**[Expected result]:**
- The “Create a Firefox Account or sign in to” overlay is displayed.

**[Actual result]:**
- The file is added.

**[Additional notes]:**
- This issue is not reproducible if you are logged into FxA.
- Attached a screen recording with the issue: [Link](https://drive.google.com/open?id=1OH-Olkqbp8NGH4vIgmawXJzU79Tcir6i)

**Comment by dannycoates** [comment]
fixed in 7f9674f

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on the https://send2.dev.lcip.org website on Windows 10 x64, Mac 10.14 and Arch Linux.
