### ISSUE TITLE
[Android] The “Cancel” button is no longer displayed while the file is uploading

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1194]
**[Affected Platforms]:**
- Android 8 [Samsung S8, Huawei P20 Lite, Google Pixel]

**[Prerequisites]:**
- Have the latest Send Android application (org.mozilla.sendandroid-2019-03-01-release-signed.apk) installed on the device.

**[Steps to reproduce]:**
1. Open the Send Android application.
2. Tap the “Add file(s)” button and select a file of minimum 5MB.
3. Tap the “Upload” button and observe the displayed page. 

**[Expected result]:**
- The “Cancel” button is displayed in the bottom right of the uploading file. 

**[Actual result]:**
- No “Cancel” button is displayed. 

**[Notes]:**
- The “Cancel” button was displayed on previous builds.
- This issue is no longer reproducible on the https://send2.dev.lcip.org website. 
- Attached a screenshot with the issue:

![rec of issue - cancel button](https://user-images.githubusercontent.com/37875464/53881285-f75ef180-401b-11e9-8871-adfc4de5a5ff.gif)

**Comment by dannycoates** [comment]
this ought to be fixed on android in the next build

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-03-07-release-signed.apk) on Samsung S8, Google Pixel, and Huawei P20 Lite.

Considering this I will close this issue.
