### ISSUE TITLE
[Android] The password is wrongly kept for the next added file after the previous file was removed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/send#1195]
**[Affected Platforms]:**
- Android 8 [Samsung S8 and Google Pixel]

**[Prerequisites]:**
- Have the latest Send Android application (org.mozilla.sendandroid-2019-03-01-release-signed.apk) installed on the device.
- Have a file added to be uploaded.

**[Steps to reproduce]:**
1. Open the Send Android application with the added file from prerequisites.
2. Tap the "Protect with password" string and insert a password.
3. Tap the "x" button for the added file from prerequisites.
4. Tap the "+" button and add a new file.
5. Observe the protect with password section.

**[Expected result]:**
- The "Protect with password" option is not selected. 

**[Actual result]:**
- The "Protect with password" option is selected and the previously added password remains set. 

**[Notes]:**
- Attached a recording of the issue:
![rec of the issue remus](https://user-images.githubusercontent.com/40061643/53899527-0f963700-4043-11e9-9470-96438d7afed1.gif)

**Comment by dannycoates** [comment]
fixed in fb9f354

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible with the latest build (org.mozilla.sendandroid-2019-03-07-release-signed.apk) on Samsung S8 and Google Pixel (Android 8.0).
