### ISSUE TITLE
[L10N] dragAndDropFiles and orClickWithSize should be a single string

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/send#1196]
In `send.ftl` I have found two strings `dragAndDropFiles` (_Drag and drop files_) and `orClickWithSize` (_or click to send up to { $size }_). Their split is really unfortunate at least for Czech and I believe for some other languages too. To have a meaningful translation, Czech requires to have the size in the first part of the sentence.

Is there any special reason to have the string split at all, which could not be achieved by a HTML tag allowed in FTL or some marker variable inserted in the middle of a single string? Even if the strings need to be split, I would like to know, what is between of them.

/cc @flodolo

**Comment by flodolo** [comment]
I thought the same, but the amount of code around those strings is not irrelevant (they're in 2 different DIVs, it's not just a line break).

Can you give an example of the translation you would ideally have in Czech?

**Comment by MikkCZ** [comment]
The whole sentence would be _Pro nahrání až { $size } velkého souboru zde klepněte myší nebo ho sem přesuňte_.

Or if this is actually not a sentence, but rather visually two distinct texts, I can adjust the strings to look similar to what is currently in production:
_To start upload file click or drag&drop here_
_max. supported size { $size }_

**Comment by dannycoates** [comment]
The english strings can be seen on https://send2.dev.lcip.org

If there's a way to split the sentence that looks ok in that format then it can be split however you choose. Otherwise I'd suggest splitting it something like this:

```
dragAndDropFiles = Drag and drop or click
orClickWithSize = Send files up to { $size }
```

**Comment by johngruen** [comment]
@MikkCZ i think your suggestion to split into multiple segments works. For the time being we can add some more context to the comments in the FTL. We're also working to get the new version up on master so it is visible in pontoon
