### ISSUE TITLE
[Android] You can no longer log into Firefox Accounts on the latest Send for Android build

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1199]
**[Affected Platforms]:**
- Android 8 [Samsung S8, Huawei P20 Lite, Google Pixel]

**[Prerequisites]:**
- Have the latest Send Android application (org.mozilla.sendandroid-2019-03-01-release-signed.apk) installed on the device.

**[Steps to reproduce]:**
1. Open the Send Android application.
2. Tap the “Sign In/Up” button and then tap the “Sign In/Up” from the overlay.
3. Enter a valid Firefox account and password.
4. Tap the “Sign in” button and observe the behavior.

**[Expected result]:**
- The “Send” homepage is displayed, you are logged into Firefox Accounts and the user icon is displayed in the top right part of the screen. 

**[Actual result]:**
- The “Send” homepage is displayed and the “Sign In/Up” button is displayed in the top right part.

**[Notes]:**
- With previous builds (org.mozilla.sendandroid-2019-02-11.apk and org.mozilla.sendandroid-2019-02-20-release-signed.apk) you are logged into Firefox Accounts but the previously uploaded files are not displayed. This was not reproducible before with those builds. 
- Attached a screen recording with the issue:

![rec of issue - sign in](https://user-images.githubusercontent.com/37875464/53956680-f5ad3080-40e4-11e9-8b31-89007a85c3c5.gif)

**Comment by johngruen** [comment]
can repro on latest APK

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest Send Android build (org.mozilla.sendandroid-2019-03-08-release-signed.apk) on Samsung S8, Google Pixel, and Huawei P20 Lite.
