### ISSUE TITLE
Update Launcher Icons

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#1203]
Provided by Stephen Horlander

From email:
I pulled together all of the assets needed for the Launcher icon based on this documentation: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

This includes a foreground (ic_launcher_foreground) and background (ic_launcher_background). The background is just a solid color though, so if we can use a color and not an image it should be: #220033

Attached are different fore and background size

@dannycoates does this work? LMK if there's anything else i can provide here:

https://drive.google.com/file/d/0ByaR4oZsXEGSVm9NbjFSSkxLNkxoNXZEN3lIV0tGX3JDS19B/view?usp=sharing

**Comment by dannycoates** [comment]
done in 7c0f227f
