### ISSUE TITLE
Layout is broken with longer translations

### ISSUE THREAD

**Issue by flodolo** [mozilla/send#1204]
<img width="1049" alt="schermata 2019-03-07 alle 19 06 37" src="https://user-images.githubusercontent.com/3644868/53978710-366c7000-410c-11e9-8fad-80d9e9168450.png">

Italian translation ^^

**Comment by pdehaan** [comment]
Not sure if this would have caught the above issue, but I wrote a quick+dirty Puppeteer scraper for all the current `availableLocales` from the ./package.json file (which I assume is for the **master** branch and not specific to these new V2 strings).

https://github.com/pdehaan/send-puppeteer

But, it did catch a rogue, untranslated `-send-brand` string in the "fr" locale:

![](https://github.com/pdehaan/send-puppeteer/blob/master/shots/home-fr-fc1d2f4.png?raw=true)
Per: https://github.com/pdehaan/send-puppeteer#fr

**Comment by flodolo** [comment]
That's expected, because the string is [translated](https://pontoon.mozilla.org/fr/test-pilot-firefox-send/send.ftl/?string=196265), but the [term](https://pontoon.mozilla.org/fr/test-pilot-firefox-send/send.ftl/?string=196268) is not (yet). Fluent falls back to the ID in case a string is missing.

**Comment by dannycoates** [comment]
@flodolo do terms not fall back to default locale?

**Comment by flodolo** [comment]
No, a missing message would fall back to English, but we don't throw away a translate message because it references another missing message or term (also, not sure that can be done in a decent way performance-wise, but I'm not really a developer).
