### ISSUE TITLE
Make size fully localizable

### ISSUE THREAD

**Issue by flodolo** [mozilla/send#1211]
As noted in the review for vnext, we should assume that `(number)(unit)` without a space would work for all languages. We should make it localizable, and possibly make also the unit localizables.

**Comment by flodolo** [comment]
> possibly make also the unit localizables.

French, for example, would need this.

**Comment by dannycoates** [comment]
something like?
```
# ex. 23.4MB
size = { $num }{ $unit }
# kibibyte abbreviation
kb = KB
# mebibyte abbreviation
mb = MB
# gibibyte abbreviation
gb = GB
```

**Comment by flodolo** [comment]
> something like?

Exactly
