### ISSUE TITLE
Unable to make the project on Ubuntu 18.10

### ISSUE THREAD

**Issue by irfnhm** [mozilla/send#1215]
When I hit run, the following error is thrown.
`Process 'command './buildAssets.sh'' finished with non-zero exit value 1`

**Comment by dannycoates** [comment]
Before you can build the Android app, you'll need to have nodejs v10 and run: `npm install` from the base directory.

**Comment by johngruen** [comment]
@irfnhm we think @dannycoates response is correct feel free to reopen if u need more help

**Comment by irfnhm** [comment]
@johngruen yes.
@dannycoates thank you that worked. I had Node 8 installed that's why I had the problem. :+1:
