### ISSUE TITLE
Horizontal scrollbar on Firefox for Android

### ISSUE THREAD

**Issue by Regaddi** [mozilla/send#1219]
Hey,

the website send.firefox.com seems to have an unintended horizontal scrollbar on my Firefox for Android (Huawei P20 with Android 9).

Video attached.

![ezgif-2-f588bf372239](https://user-images.githubusercontent.com/1336590/54224581-1a950f80-44fa-11e9-82ac-33b2c7e2b5e3.gif)

**Comment by dannycoates** [comment]
Thanks @Regaddi
