### ISSUE TITLE
Upload on Windows to send.firefox.com does not work

### ISSUE THREAD

**Issue by turboscholz** [mozilla/send#1232]
When I drag and drop a jpg from Windows Explorer into the Firefox window where https://send.firefox.com/ is opened, the image is just opened in the same browser tab and the URL is changed, pointing to my local jpg file (file://...) in the browser search bar.

Instead of this I would have expected that the image is uploaded and I would receive the link which I can use to share the image with my peers.

I am using 65.0.2 (64-bit)

I would have opened a new issue on the feedback page, but this is not possible. When I enter the text above and select "Report an issue", the page shows two errors after clicking on "Next":
![image](https://user-images.githubusercontent.com/5513310/54279289-fcc8b880-4594-11e9-85ad-24eed238582d.png)

I am hoping that this issue will be forwarded to the correct people in charge.

Best
Uwe

For the record: The page looks quite empty when opening it in Firefox under Windows7:

![image](https://user-images.githubusercontent.com/5513310/54279820-47970000-4596-11e9-8126-cf4740d790b8.png)

**Comment by dylmye** [comment]
Can't repro on Windows 10 Firefox 66.0b14

**Comment by johngruen** [comment]
@turboscholz can you take a look at #1222. we believe this is causing the white screen issue you are having, and are working on a fix.

**Comment by turboscholz** [comment]
Thanks, @johngruen! Allowing cookies in general fixes this problem. Hope it is fixed permanently with the changes in #1222. :+1:
