### ISSUE TITLE
Make UI customisable and document how-to

### ISSUE THREAD

**Issue by aravindhsampath** [mozilla/send#1233]
Thanks for this open source project, and it looks great! 

I can imagine running this ourselves(in our network & server) dedicated to our in house researchers to get data from collaborators, students and others in the field. But, I could not find an easy way to customise the UI in such a way to differentiate it from the official Mozilla send service. For example, I'd like to take away the signin/Signup button that leads to Mozilla service.. 

I think it would help to make the UI customisable, and adding a few notes in the README about how one would go about doing so. 

If the above suggestion is not in line with the goals of the project, feel free to close this issue. 

Cheers!

**Comment by johngruen** [comment]
Since the code is open you can fork and customize as you wish already!
