### ISSUE TITLE
Cannot change BASE_URL

### ISSUE THREAD

**Issue by phpdave11** [mozilla/send#1238]
When supplying a custom BASE_URL, the link that is generated still starts with http://localhost/

I am starting the server with the following command:
```
BASE_URL="https://my-domain.tld" npm run start 
```

**Comment by dannycoates** [comment]
the generated link comes from the `Host` header of the HTTP request

**Comment by ropable** [comment]
Running send as a Docker image with the BASE_URL environmental variable set (and behind a reverse proxy), it doesn't seem to be making use of BASE_URL. The download links are in the format https://HOST:PORT/download/<HASH>

**Comment by dannycoates** [comment]
as I said, the download links are generated based on the [Host header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host)

BASE_URL is deprecated and will be removed in a future release.

**Comment by phpdave11** [comment]
Thanks, I've mostly got it working by setting the Host header.  Initially I received the error message "Invalid Host header" when I set it, but I was able to fix that by setting "disableHostCheck: true" in webpack.config.js

The only other issue that took a while to figure out is that links say http:// when they should say https:// since I am using SSL in my development environment.  I was able to get it working by running it in production mode and setting NODE_ENV=production after reading your comment in #666.

```
NODE_ENV=production npm run prod
```

**Comment by ropable** [comment]
@phpdave11 Mind dropping a detail about where you're setting the Host header? I was trying to run send behind an Nginx proxy and expected node to receive the header automatically via that request, but it seems not. I'm wondering if need to set it explicitly in node config or elsewhere.

**Comment by phpdave11** [comment]
@ropable I'm also using nginx with a reverse proxy.  Here's my config:

```
server {
    listen 443 ssl;
    server_name send.tld;
    ssl on;
    ssl_certificate /usr/local/etc/nginx/ssl/tld_fullchain.pem;
    ssl_certificate_key /usr/local/etc/nginx/ssl/tld_privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        rewrite ^/(.*)$  /$1  break;
        proxy_set_header Host "$server_name";
        proxy_pass http://localhost:1443/;
    }
    access_log /usr/local/var/log/nginx/default.log combined;
}
```

**Comment by ropable** [comment]
@phpdave11 Thanks for that. The `proxy_set_header Host "$server_name"` directive was the one I needed. I may submit a small PR to improve the documentation to this effect.
