### ISSUE TITLE
But I'm already signed in!

### ISSUE THREAD

**Issue by peterbe** [mozilla/send#1255]
I'm presented with the login window on https://send.firefox.com/ after clicking the "Sign in/up" button (in the upper right-hand corner). 

My first reaction is: but I'm already signed in to Firefox Accounts! Why do I have to sign in again??

Incidentally, if you click the "Sign in/up" form but **leaving the email input field empty**, it takes me to the familiar FxA page at `https://accounts.firefox.com/oauth/?action=email&client_id=1f30e32975ae5112&code_challenge=hsZ2...` where it knows I was already logged in. 

<img width="546" alt="Screen Shot 2019-03-15 at 9 31 38 AM" src="https://user-images.githubusercontent.com/26739/54434810-75e71d80-4705-11e9-9819-77c7332b9e89.png">

I always struggle to remember which email address I use to Sign in to Firefox. Is it my personal or my work/LDAP one or my Gmail addrress?? For that reason I dislike having to type in my email on the sign up form. 

From FxA page I just need to click "Sign in" and I become logged in on send.firefox.com
<img width="572" alt="Screen Shot 2019-03-15 at 9 33 12 AM" src="https://user-images.githubusercontent.com/26739/54434839-86979380-4705-11e9-8176-a5ce4d1de845.png">

**Comment by dannycoates** [comment]
I personally don't care for the email input here either...

**Comment by co16353sidak** [comment]
Hey, @peterbe @dannycoates So shouldn't we just not keep an input option here, and instead have just the sign in/up button and let it redirect to the FxA Page. 
Or is there a specific reason why this happens.

**Comment by babhishek21** [comment]
> Incidentally, if you click the "Sign in/up" form but **leaving the email input field empty**, it takes me to the familiar FxA page at `https://accounts.firefox.com/oauth/?action=email&client_id=1f30e32975ae5112&code_challenge=hsZ2...` where it knows I was already logged in.

This is super non-intuitive.

**Comment by johngruen** [comment]
We'll headscratch on this one for a sec

**Comment by johngruen** [comment]
I think the plan is to get rid of the email box on the original, but we're going to roll this up with some other brand changes
