### ISSUE TITLE
Bug in upload FIle

### ISSUE THREAD

**Issue by jalalkun** [mozilla/send#1256]
after uploading files appears oddities when going to select the expiration date, several variables appear.

[tangkapan layar](https://screenshots.firefox.com/BpApSXAhTgYg7R7d/send.firefox.com)

**Comment by dannycoates** [comment]
This appears to be a bug in `id/send.ftl`

**Comment by flodolo** [comment]
CC @alamanda and @fauzanalfi 
I'm going through the file and fixing, I can spot at least two errors :-\

**Comment by flodolo** [comment]
2 strings with the wrong variable placeholder, 2 strings without the variable in the plural, also approved an extra string that seemed innocent enough for me to approve (size formatting)
https://github.com/mozilla/send/commit/062cbbd1f88e27202cc41203bd44697c5a473dc5#diff-8ea0c1534f1682ec370c446d53ea4076
