### ISSUE TITLE
link webExtension for website send.firefox.com

### ISSUE THREAD

**Issue by hellosct1** [mozilla/send#1257]
Hi

I made the extension for Firefox Desktop and Firefox Android

https://addons.mozilla.org/fr/firefox/addon/send-to-fx/

I think it would be nice to put a link on the website at the bottom of the page at the same level as the Cookies, github buttons...

thank's

Christophe

**Comment by dannycoates** [comment]
Nice work on the extension @hellosct1. Thanks for the suggestion but we can't link to a third-party extension from the official site.
