### ISSUE TITLE
[Enhancement] The estimate time and the download/upload speed should be displayed when uploading/downloading a file

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#126]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://p2p.dev.lcip.org/" page.
2. Upload a large file and observe the area under the progress bar.

[Expected result]:
- An estimated time and the upload speed are displayed.

[Actual results]:
- Only the percentage is displayed. 

[Notes]:
- This behavior is also reproducible when downloading a file.

**Comment by dannycoates** [comment]
Good transfer estimates are difficult and bad ones make the ux even worse than not having it. Transfer rate, meh? I vote to wontfix
