### ISSUE TITLE
Add entrypoint param to fxa

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#1261]
see this: 
```
https://mozilla.github.io/application-services/docs/accounts/metrics.html
```

let's do `entrypoint=send` for now and then if we add more we can segment by `entrypoint=send-{whatever}`

**Comment by dannycoates** [comment]
we do

**Comment by dannycoates** [comment]
actually we do `send-{source}` where source was the trigger. ie button, size, etc

**Comment by johngruen** [comment]
Is it in a PR that's not shipped yet...not seeing it in the query params getting passed in in the FxA URL

**Comment by dannycoates** [comment]
added to `/authorization` in cc9a5d11
