### ISSUE TITLE
3.08 centos 7.6 build failed

### ISSUE THREAD

**Issue by ladybug2fire** [mozilla/send#1265]
node 10.15.3
os centos 7.6
send 3.08
after install run start with a lot of waring about webcrypto-core module. moreover with a error 
in ./node_modules/pvtsutils/dist/pvtsutils.es.js
module build failed (from (webpack)-unassert-loader/index.js)
Error line 167: Unexpected token

**Comment by dannycoates** [comment]
possibly related https://github.com/mozilla/send/issues/1221#issuecomment-474449798

**Comment by ladybug2fire** [comment]
@dannycoates exactly alike，thanks 🙏 , i'll try later 😊

**Comment by dannycoates** [comment]
closing, feel free to reopen if there's more trouble
