### ISSUE TITLE
The File Share page is wrongly rendered and upload/download functionality is not working on IE and Edge

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#127]
[Affected versions]:
- Internet Explorer 11.0.9600.18697
- Edge 25.10586.672.0

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the IE/Edge browser navigate to "https://p2p.dev.lcip.org/" page.
2. Observe the page and verify if the upload/download functionality is working.

[Expected result]:
- The page is correctly rendered and the upload/download functionality is working as expected.

[Actual results]:
- The page is wrongly rendered and the upload/download is not working.

[Notes]:
- This issue is also reproducible on the stage page (https://fileshare.stage.mozaws.net). 
- Here is a screen shot with the issue:
Sender:
![sneder](https://user-images.githubusercontent.com/19226534/27484783-2d061c50-5833-11e7-83ad-115e4a3b657b.png)

Receiver:
![reciver](https://user-images.githubusercontent.com/19226534/27484776-27bf9e10-5833-11e7-8c8f-824453192306.png)

**Comment by wresuolc** [comment]
This will probably be fixed with new designs

**Comment by dannycoates** [comment]
The page seems to render fine now. The extremely slow crypto performance is another issue...

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on multiple versions of Windows 10 and it looks that on older versions of Edge, the website is not correctly rendered. However, all tested Edge versions do not display the "Send" background image.

Here are the results:
- Windows 10 Creators Edition with Microsoft Edge v.40.15063.0.0
The website is **correctly rendered**
- Windows 10 Anniversary Edition with Microsoft Edge v.38.14393.1066.0 
The website is **correctly rendered**
- Windows 10 November Edition with Microsoft Edge v.25.10586.672.0 
The website is **wrongly rendered**. Here are two screenshots with the issue:
1. https://goo.gl/cb1RZv
2. https://goo.gl/qiUW2q

Also, on **Internet Explorer** the website is **wrongly rendered** on all versions of Windows.

**Comment by ericawright** [comment]
perhaps for launch at least we exclude internet explorer?

**Comment by dannycoates** [comment]
We're considering IE as unsupported for now. Edge is working in v1.1.0
