### ISSUE TITLE
Android app: PDF uploading causes error

### ISSUE THREAD

**Issue by gvanwaelvelde** [mozilla/send#1275]
Whenever I try to upload a PDF file through the Android app, it says "Error Sorry, an error has occurred.". 
Other filetypes can be uploaded without problems.

Steps to reproduce:
1) Open the Firefox Send app
2) Press +
3) Select a PDF file
4) Press "Upload"
5) It shows error message

**Comment by gvanwaelvelde** [comment]
My device is a Samsung J7 running Android 8.1.0.

**Comment by johngruen** [comment]
@gvanwaelvelde we are unable to reproduce this issue...how big was your PDF?

**Comment by gvanwaelvelde** [comment]
The file was about 5Mb. I tried with both smaller and bigger files as well. It didn't make any difference.

I just tried again and now it's working fine, I can't reproduce it anymore myself.
I'll close the issue. Thanks a lot for investigating!
