### ISSUE TITLE
1-Download links are expired when emailed

### ISSUE THREAD

**Issue by groovecoder** [mozilla/send#1276]
I sent someone a 1-time download link from my Gmail account.

They replied that the link was already expired.

I suspect either Gmail or their email provider tried to scan/GET the link, causing it to expire?

**Comment by johngruen** [comment]
hmmm, this is definitely a case we've tested in the past. @groovecoder were u using your work email or personal?

**Comment by groovecoder** [comment]
I sent from my personal gmail account. I'm not sure what email service the recipient may have been using.

**Comment by dannycoates** [comment]
It isn't likely to be anything in between triggering a download. The link takes you to a landing page, js needs to run an xhr for metadata, and a `<button>` triggers the download. One cause I've seen in the past is the link url being incomplete, like a character missing from the key portion. Without the correct key any link will look like a 404.

**Comment by groovecoder** [comment]
Ah, that sounds more likely what happened. Thanks for the info.
