### ISSUE TITLE
Add to F Droid

### ISSUE THREAD

**Issue by MarionMoseby** [mozilla/send#1277]
Inclusion on the main f droid repo is being discussed here:

https://gitlab.com/fdroid/rfp/issues/936

Are you ok with that?

**Comment by clouserw** [comment]
Hi @MarionMoseby .  Can you explain more about what you're asking from us here?  I'm not familiar with F-Droid, but I glanced around and saw your inclusion policy.  Adding the Firefox Send app to a list of software you maintain would be fine, but modifying the Firefox Send app and shipping it as Firefox Send would not.  I wasn't clear if "We cannot build apps using proprietary tracking/analytic dependencies..." would conflict with the use of Amplitude.

So...what specifically are you asking for?  Thanks

**Comment by MarionMoseby** [comment]
Hi! Im not officially affiliated with f droid or sth, so maybe itd be better to ask on gitlab :)

I just know that for an app to be included there the app owner has to be notified and support inclussion, which might mean, if necesary, modifying the app to eliminate proprietary analytics and/or changing the name.

Cheers!

-------- Mensaje original --------

**Comment by clouserw** [comment]
I think my comment above sums up the notified/support question.  We aren't going to eliminate analytics from the code.  So, I'm going to close this.  Please comment if there is more we can do.  Thanks.

**Comment by mvgorcum** [comment]
Just for reference: F-droid has no policy against analytics in general (though your app will get labeled with a 'tracking' anti-feature). The only limitation is that the apps have to be fully build from open source software.

**Comment by fdroidiordf** [comment]
If Firefox Send can’t be included into F-Droid, if

1. it has the name “Firefox Send” and
2. the app got changed (removing proprietary analytics)

and the problem could not be solved by removing part 2., why don’t remove part 1. and make a FLOSS fork rebranded to “Fennec Send” as the F-Droid community also has done with “Firefox”->“Fennec F-Droid”?
In the description of the app, we could call it an “Firefox Send compatible app” or something like that so it is clear that it is an app for the Firefox Send service.

**Comment by rfc2822** [comment]
Is there an official APK that can be downloaded from Github (like for other Mozilla builds)? In this case, Firefox Send could at least be added to the https://gitlab.com/rfc2822/fdroid-firefox repo.
