### ISSUE TITLE
encryptKeyPromise declared but not used

### ISSUE THREAD

**Issue by ocavue** [mozilla/send#1278]
*This issue is a **bug report***

[The docs](https://github.com/mozilla/send/blob/bb4fa0a75cd36030ea66df696fa28a6087fc2eb6/docs/encryption.md) says: 

> The secret key is used to derive 3 more keys via HKDF SHA-256
>    - an encryption key for the file (AES-GCM)
>    - an encryption key for the file metadata (AES-GCM)
>    - a signing key for request authentication (HMAC SHA-256)

It seems that [encryptKeyPromise](https://github.com/mozilla/send/blob/bb4fa0a75c/app/keychain.js#L21) should be the "encryption key for the file" based on the code structure, but I didn't find out where this attribute is being used.

![image](https://user-images.githubusercontent.com/24715727/54884871-f568af80-4eb0-11e9-9720-a6eb8cb5e3b9.png) 

update:

I guess that what encryptKeyPromise did has been replaced by [these codes](https://github.com/mozilla/send/blob/bb4fa0a75cd36030ea66df696fa28a6087fc2eb6/app/ece.js#L39-L53). But I'm not sure.

**Comment by dannycoates** [comment]
Thanks @ocavue,

This key has been replaced by ECE. It'll be removed add the docs fixed in the next release.
