### ISSUE TITLE
Set protected status on production branch

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/send#1279]
Hello! This is your neighborhood secops team looking out for you!

The production branch on this repository is not protected against force pushes. This setting is recommended as part of [Mozilla's Guidelines][guidelines_url] for a Sensitive Repository.

**Anyone with admin permissions for this repository can correct the setting using [this URL][protect_url].**

If you have any questions, or believe this issue was opened in error, please contact [us][email] and mention SOGH001-0 and this repository.

Thank you for your prompt attention to this issue.
--Firefox Operations Security team

[guidelines_url]: https://wiki.mozilla.org/GitHub/Repository_Security
[protect_url]: https://github.com/mozilla/send/settings/branches
[email]: <mailto:secops+gh001@mozilla.com?subject=SOGH001-0+Question+re+mozilla/send>

**Comment by johngruen** [comment]
@clouserw

**Comment by johngruen** [comment]
@clouserw we think this might be hard b/c of pontoon integration

**Comment by dannycoates** [comment]
I restricted the accounts that can push to master, but signed commits is blocked on pontoon.

<img width="598" alt="Screen Shot 2019-03-28 at 9 38 13 AM" src="https://user-images.githubusercontent.com/87619/55175860-573d4980-513d-11e9-995a-692ad382eebb.png">

**Comment by hwine** [comment]
FYI, signed commits are not (yet) being required, as they need some tooling to support.

The primary compliance we're looking for is the basis "protect from forced pushes". Anything beyond is gravy.

**Comment by moz-hwine** [comment]
Looks good
