### ISSUE TITLE
When you upload/download a large file, there is a noticeable delay until the progress bar is displayed 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#128]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://send.dev.mozaws.net" page.
2. Upload a large file (eg: 1.0 Gb) and observe the behavior.

[Expected result]:
- The progress bar is displayed even if the upload didn't start.
Or
- A loading spinner appears until the progress bar is displayed.

[Actual results]:
- There is a noticeable delay (depends on how large is the file) until the progress bar is displayed.

[Notes]:
- The user probably think that the download/upload is not working.
- The issue is also reproducible when downloading a large file.
- This issue is also reproducible on the stage page (https://send.stage.mozaws.net). 
- Here is a screen recording with the issue:
![delay until progres bar](https://user-images.githubusercontent.com/19226534/27484914-934cc0ae-5833-11e7-8746-af4c4ce1b440.gif)

**Comment by wresuolc** [comment]
We can fix this when we have the new designs.  @sevaan let's connect at the all hands to talk about this

**Comment by dannycoates** [comment]
There's a few discrete steps that happen before the upload begins. Each can take a noticeable amount of time for large files.

1. Loading the file from disk into Firefox
2. Hashing the file (not in master yet)
3. Encrypting the file

We know when each of these steps starts and ends, but we can't get progress on any of them.

**Comment by ekr** [comment]
On Fri, Jun 23, 2017 at 4:13 PM, Danny Coates <notifications@github.com>
wrote:

> There's a few discrete steps that happen before the upload begins. Each
> can take a noticeable amount of time for large files.
>
>    1. Loading the file from disk into Firefox
>    2. Hashing the file (not in master yet)
>    3. Encrypting the file
>
> We know when each of these steps starts and ends, but we can't get
> progress on any of them.
>
You could probably stream all of these.... Is that something you want to
look at?

**Comment by dannycoates** [comment]
> You could probably stream all of these.... Is that something you want to
> look at?

Yes. We'll be working on this in v2.

@abhinadduri in the meantime lets emit an event for each phase in `fileSender` and `fileReceiver` so the ui can show a label.

**Comment by abhinadduri** [comment]
@dannycoates Do you want to emit separate events for hashing and encrypting? Right now both of those are in the same "Promise.all" so adding in code to emit separately for those two phases would need some refactoring.

**Comment by dannycoates** [comment]
@abhinadduri a single event for both is fine

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page. There no longer is any delay until the progress bar appears 🎉 .
Marking as verified.
