### ISSUE TITLE
[ iPhone/iPad ] Where can I find the files which have been downloaded ?

### ISSUE THREAD

**Issue by jiaqiangwjq** [mozilla/send#1281]
It works well on my PC, however, when I use my phone or ipad to download from _Firefox Send_, once the downloading finishes, I don't know where I can find my files downloaded. Could you give me some suggestions ? I'll appreciated it, sincerely.

**Comment by johngruen** [comment]
Thanks for the report @jiaqiangwjq ... can you tell us which browser you are using on your iphone?

**Comment by jiaqiangwjq** [comment]
> Thanks for the report @jiaqiangwjq ... can you tell us which browser you are using on your iphone?

Safari.
And sorry for my belated reply.😭

**Comment by fzzzy** [comment]
@jiaqiangwjq When using Safari, a gray screen will appear with the file icon after it has finished downloading. There will be an option to open the file with the default application, and a "More..." link. Tap More..., then look for the "Save to Files" option. Choose where to save it and press save. Then, you can find it in the "Files" application which is now part of iOS.

Hope this helps. If not, feel free to reopen this bug and ask for more help.

**Comment by jiaqiangwjq** [comment]
> @jiaqiangwjq When using Safari, a gray screen will appear with the file icon after it has finished downloading. There will be an option to open the file with the default application, and a "More..." link. Tap More..., then look for the "Save to Files" option. Choose where to save it and press save. Then, you can find it in the "Files" application which is now part of iOS.
> 
> Hope this helps. If not, feel free to reopen this bug and ask for more help.

Thanks for the help !
