### ISSUE TITLE
Sign out (option not visible)

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/send#1282]
I signed in without difficulty. 

I see no way to sign out: 

![image](https://user-images.githubusercontent.com/192271/55069769-b6875500-507c-11e9-9226-f5a187cd27da.png)

Waterfox ~56.2.7.1 on FreeBSD-CURRENT. 

Reproducible with ad blocking etc. disabled. 

I wondered whether the absence of sign out is by design, but the screen recording at (unrelated) `https://github.com/mozilla/send/issues/1151#issue-410809167` shows a circular user icon that presents a menu when clicked.

**Comment by grahamperrin** [comment]
The same with Firefox, after signing in: 

![image](https://user-images.githubusercontent.com/192271/55071423-7cb84d80-5080-11e9-8890-37bb64023734.png)

Screen recording available on request.

**Comment by dannycoates** [comment]
Thanks for the report @grahamperrin 

You are supposed to see your Firefox Account picture in the upper right corner or a default profile picture if you don't have one set. You are certainly not seeing what's expected.

Could you share a screenshot of the web console `Ctrl+Shift+K` after refreshing the page?

**Comment by johngruen** [comment]
Moving to backlog now. we can retriage when we can see the console. This could be happening because of a content blocking add-on since we load avatars from Firefox Accounts.

**Comment by grahamperrin** [comment]
> … could be happening because of a content blocking add-on … 

I think not. From the opening post: 

>> Reproducible with ad blocking etc. disabled.

– and it's reproducible with Firefox in safe mode: 

![image](https://user-images.githubusercontent.com/192271/55292233-1c0e7500-53e0-11e9-8880-902aafa0e288.png)

> Content Security Policy: The page’s settings blocked the loading of a resource at https://secure.gravatar.com/avatar/0c02caffb6b5bb7c900b09203e783b28?s=600 (“img-src”).

I relaxed content blocking to _Standard_, <kbd>Shift</kbd>-reloaded the page, the CSP blockage persists.

**Comment by dannycoates** [comment]
Thanks @grahamperrin, this will be fixed in the next release.
