### ISSUE TITLE
Redis connection in broken state

### ISSUE THREAD

**Issue by hbaier** [mozilla/send#1292]
I'm using Firefox Send from [Docker Hub](https://hub.docker.com/r/mozilla/send/) (tag v3.0.9) as a Kubernetes deployment. When my redis server (also a Kubernetes deployment) goes away

`{"Timestamp":1554728954088000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"Error: Redis connection in broken state: connection timeout exceeded.","stack":"\n    at RedisClient.connection_gone (/app/node_modules/redis/index.js:649:19)\n    at Socket.<anonymous> (/app/node_modules/redis/index.js:259:18)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at Socket._onTimeout (net.js:440:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}}`

`{"Timestamp":1554729005971000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"AbortError: HSET can't be processed. The connection is already closed.","stack":"\n    at handle_offline_command (/app/node_modules/redis/index.js:851:15)\n    at RedisClient.internal_send_command (/app/node_modules/redis/index.js:885:9)\n    at RedisClient.hset (/app/node_modules/redis/lib/commands.js:58:25)\n    at DB.set (/app/server/storage/index.js:54:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}}`

`{"Timestamp":1554729005972000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"AbortError: HMSET can't be processed. The connection is already closed.","stack":"\n    at handle_offline_command (/app/node_modules/redis/index.js:851:15)\n    at RedisClient.internal_send_command (/app/node_modules/redis/index.js:885:9)\n    at RedisClient.hmset (/app/node_modules/redis/lib/individualCommands.js:352:17)\n    at DB.set (/app/server/storage/index.js:56:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}}`

`{"Timestamp":1554729005972000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"AbortError: EXPIRE can't be processed. The connection is already closed.","stack":"\n    at handle_offline_command (/app/node_modules/redis/index.js:851:15)\n    at RedisClient.internal_send_command (/app/node_modules/redis/index.js:885:9)\n    at RedisClient.expire (/app/node_modules/redis/lib/commands.js:58:25)\n    at DB.set (/app/server/storage/index.js:58:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}}`

is written in the log.

However no new connection will be established with redis. When I try to download files "This link has expired" will be displayed.

**Comment by dannycoates** [comment]
We should add a [retry_strategy](https://github.com/NodeRedis/node_redis#rediscreateclient) here https://github.com/mozilla/send/blob/master/server/storage/redis.js#L13

**Comment by dannycoates** [comment]
We should add a [retry_strategy](https://github.com/NodeRedis/node_redis#rediscreateclient) here https://github.com/mozilla/send/blob/master/server/storage/redis.js#L13

**Comment by TwizzyDizzy** [comment]
Just ran into this because I did not have `redis-server.service` as unit dependency in my systemd unit file for send, hence `send.service` started before `redis-erver.service` which lead to the same outcome: expired links. I fixed my unit file to circumvent this, but I agree: retrying should be the way to go here.

My fixed unit file for anyone running into this:

```
# /etc/systemd/system/send.service
[Unit]
Description=Mozilla send
After=syslog.target network.target redis-server.service

[Service]
Type=simple
User=send
Group=send
ExecStart=/opt/nodejs8/bin/npm run prod
Environment=PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/nodejs8/bin
PrivateTmp=yes
WorkingDirectory=/opt/send

[Install]
WantedBy=multi-user.target
```

Cheers
Thomas

**Comment by hugomiguelabreu** [comment]
> We should add a [retry_strategy](https://github.com/NodeRedis/node_redis#rediscreateclient) here https://github.com/mozilla/send/blob/master/server/storage/redis.js#L13

What would be the best strategy to implement? I can take this one.

**Comment by dannycoates** [comment]
Thanks @hugomiguelabreu 

I think a `total_retry_time` of 10 seconds with a 500ms delay is enough

**Comment by hugomiguelabreu** [comment]
Couldn't replicate this issue on my machines even using redis container. Tested the connection strategy and it was working. Regarding this specific issue I hope to have some feedback of @hbaier.
