### ISSUE TITLE
[Question] Environment config.js 

### ISSUE THREAD

**Issue by raymondpittman** [mozilla/send#1297]
For testing the master branch and possibly contributing, the environment file config.js. For setting other storage methods such as S3 and GCS, are we supposed to set a string for our bucket address? What is the format for other storage method setup, possibly provide a template so I can test contribute.

How do we run prod version with S3 for storage.

**Comment by dannycoates** [comment]
`S3_BUCKET` is the same value you'd use for an api request https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property
