### ISSUE TITLE
[Question] How secret keys transport between devices.

### ISSUE THREAD

**Issue by ocavue** [mozilla/send#1298]
I have logined on 2 devices with the same firefox account. After uploading a file from one device, I can download this file from another device without copy download URL. The secret key is on the fragment of download URL's, which means that the secret key has been upload to the Mozilla server and any device who login to my account can get this secret key. 

My file is uploaded to Mozilla server after encrypted with a random secret key and ECE, which is good, but the secret key itself is uploaded to Mozilla server too. That makes me worry. 

My question is *How was the secret key been encrypted, uploaded and downloaded*. More specifically, is anyone other than me (including Mozilla employee) can get my secret keys?

I didn't find the related code in mozilla/send by myself. Hope someone will explain my doubts.

**Comment by dannycoates** [comment]
Hi @ocavue, good question. Firefox accounts provides and end-to-end encryption key feature that we use to encrypt your list of uploads that gets synced to other browsers you log into. That key is derived from your account password which we (Mozilla) don't have access to.

Here's a brief [overview](https://mozilla.github.io/application-services/docs/accounts/end-to-end-encryption.html), and the code is implemented in https://github.com/mozilla/send/blob/master/app/fxa.js and https://github.com/mozilla/send/blob/master/app/user.js.
