### ISSUE TITLE
conduct a survey after users send a file

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#1307]
We should run a short survey to help catalogue and rank feature concepts for Send.

## Requirements
* This survey should run for a set amount of time (2-4 weeks) 
* The survey should be accessible from a prompt triggered for users after they have cleared the "Copy to clipboard" modal after a successful upload.
* If the user elects to take the survey, they should no longer see the survey prompt
* The survey should be shown a maximum of 2 times over the duration of the survey
* The survey will not be localized, so it should only be shown for EN users
* The survey should include `activeCount` and `anonymous` user props passed in as query parameters
* The survey should be shown only to web users

![Send Survey](https://user-images.githubusercontent.com/3323249/56797040-16a41f00-6814-11e9-98f7-056df5644f8c.png)

## An inspect-able comp can be found here

https://share.goabstract.com/d4c314cd-ecbe-431c-b077-97a6adece6b2

**Comment by dannycoates** [comment]
just need a survey url

**Comment by johngruen** [comment]
Cool, I'll have it by our stand up
