### ISSUE TITLE
No firefox download button on the site with a non Firefox browser

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/send#1308]
We don't propose  a Firefox download button on localized pages.
Tested on Chrome and Edge on Windows 10 and Linux, French locale.

STR:
1/ Visit send.firefox.com with a non-mozilla browser with http accept-lang headers that don't have English set as the default language

ER:
Get the site with a banner at the top proposing to download Firefox

AR:
No banner.

**Comment by pascalchevrel** [comment]
The promo is restricted to English here:
https://github.com/mozilla/send/blob/master/app/ui/body.js#L13

The source is at:
https://github.com/mozilla/send/blob/master/app/ui/promo.js

If we don't get a proper  localization process for the promo in place, I would suggest to at least do a similar hardcoded banner for a few top locales like French, German and Spanish to boost acquisition.

**Comment by johngruen** [comment]
@pascalchevrel yeah we should...this button actually converts really well in english. I think we did it as an experiment and then got distracted!

**Comment by dannycoates** [comment]
done in e7964c03eda121f61bc96072b1254bf93e6a3e23

**Comment by pascalchevrel** [comment]
Thanks!
