### ISSUE TITLE
Uploads are very, very slow for Firefox Send

### ISSUE THREAD

**Issue by CoderExt** [mozilla/send#1312]
The speed of downloads are good, but a 28 mg files took a few minutes.  My Internet speed is 60 mbps and I am using Windows 10.

**Comment by dannycoates** [comment]
Upload speeds vary by service provider. It's common for some providers to limit uploads to be much slower than downloads. You may have 60mbps down but < 1mbps up. We do not have any rate limiting on our end.

**Comment by CoderExt** [comment]
I understand your point, however, the uploads a much faster using Hightail.  When I have time, I will provide you with some stats.

 

 

Jeff Stiegler

The PC Solution

(805) 975-9643

 

CONFIDENTIALITY NOTICE: the Electronic Communications Privacy Act, Title 18, United States Code, §§ 2510-22, 2701-11, and is intended to be read only by the named individuals or entities to which it has been addressed.  If you are reading this message and are not the intended recipient, you are hereby on notice that you may not use, disclose, copy, store, or distribute to anyone, any information contained in the message.  Misuse or unauthorized disclosure of any identifying information contained in this message, including copying, storage, or distribution by any means is strictly prohibited and may subject you to civil and/or criminal penalties.  This message may be exempt from disclosure under applicable law, including the Health Insurance Portability and Accountability Act (HIPAA).  If you have received this transmission in error, we apologize.  Please contact the sender immediately by replying to this message and delete or destroy any instance or likeness of this message from all computers and other electronic storage mediums.  All emails will be returned within 24 hours unless otherwise specified.

**Comment by CoderExt** [comment]
Here are some more information.  

 

Download speed:  70 MBPS

Upload speed:  9 MBPS

 

File size: 28 MB

 

Hightail: 1 second

 

Firefox Send: 43 seconds

 

Firefox Send is significantly slower.

 

Jeff

**Comment by fzzzy** [comment]
What device, operating system, and browser are you using?

**Comment by CoderExt** [comment]
Computer, Windows 10, Firefox (current version).

 

Hope this helps.

**Comment by kemenaran** [comment]
Same here. A ~30 Mo upload that takes around 5 seconds using WeTransfer takes around 10 minutes (!) using Firefox Send.

- Macbook Pro mid-2013
- macOS 10.14
- Firefox 70.0b12

**Comment by staus** [comment]
Wouldn't consider this issue closed at all.
I have the same problem using the Android app on Samsung S7. I have speeding fast uploads on other services, but a 300mb file takes 1hr with Firefox Send. Pretty unusable to be able to upload 2.5gb if it takes a day.

**Comment by fzzzy** [comment]
@staus The Android app being slow is a known issue. There is a known fix available, porting it to GeckoView, but there are a few blockers in bugzilla that are currently preventing this from being completed.

Sorry about that.
