### ISSUE TITLE
Error when signing in

### ISSUE THREAD

**Issue by CoderExt** [mozilla/send#1318]
Get this error message when logging in.  Using computer, windows 10 and Firefox browser.
![image](https://user-images.githubusercontent.com/38814853/56983665-0d2ef580-6b39-11e9-85cb-68d73bf924d2.png)

**Comment by clouserw** [comment]
This was probably a transient error when we updated the servers to new code.  We haven't had any other reports so closing this.  Try again?  Thanks.
