### ISSUE TITLE
Anroid and IoS save on the server's disk

### ISSUE THREAD

**Issue by saydulk** [mozilla/send#1331]

**Comment by saydulk** [comment]
@julen @lmorchard @chuckharmston Anroid and IoS save on the server's disk not working but send works fine from Desktop

**Comment by saydulk** [comment]
The problem as follows:

We have installed send at our server (centos 7, local storage) and Uploading files using IOS browser is not working, tested with Safari and Chrome.

**Comment by clouserw** [comment]
There aren't enough details here to diagnose the problem.  Try updating to the latest code if you haven't.
