### ISSUE TITLE
Upload Via Python Application

### ISSUE THREAD

**Issue by AmitThakkar** [mozilla/send#1334]
Hello,

We are building the python application, and from python application, we are sending upload file request to our local "SEND" application, but getting 400 Bad Request. I think this is because of authorization header is not present.

With "SEND" client application it works very well. I tried to look into the code but not able to understand how to upload files from different applications. And I also tried to search for examples but not able to.

Please share some code snippet/example for upload file to "SEND".

Thanks

**Comment by clouserw** [comment]
Hi Amit.  I'm not sure what the problem is, but it looks like https://github.com/nneonneo/ffsend is a python script that uses Send.  Maybe they have some code you could use.  Good luck! 👍
