### ISSUE TITLE
Add trailhead topbar

### ISSUE THREAD

**Issue by clouserw** [mozilla/send#1340]
Send has a bar that advertises Firefox to Chrome users.  We want to repurpose that bar.

* **Deployed on June 3rd**
* This shows up for all visitors (not just Chrome).  This includes logged-in users.
* Logo should be replaced with masterbrand
* Text is changed to "There is a way to protect your privacy.  Join Firefox.  Learn more."
* Link goes to www.mozilla.org/firefox/accounts/?utm_source=send.firefox.com&utm_medium=banner&utm_campaign=trailhead&utm_content=protect-your-privacy

See details @ https://docs.google.com/document/d/13oZSkp5TndxFLGi80fcE6QBMGf1LOI6c9trNopDcsaQ/edit?ts=5ce36825

**Comment by marniepw** [comment]
Also, please use masterbrand here:
<img width="1230" alt="Screen Shot 2019-05-28 at 11 45 25 AM" src="https://user-images.githubusercontent.com/33703387/58503796-2928b580-813e-11e9-9d6c-958f62d82f10.png">
