### ISSUE TITLE
[Trailhead] Several UI elements of the banner are different comparing to the specifications

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#1342]
**[Affected versions]:**
- Firefox Release 67 and up
- Google Chrome  74.0.3729.169 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the browser and navigate to the https://send2.dev.lcip.org website.
2. Press Ctrl+Shift+K keys.
3. Click the "Pick an element from the page" button.
4. Click the banner's text.
5. Observe the font size value from the second column of the Web Console.
6. Observe the color code for the text.

**[Expected result]:**
Step 5 - The font size value is 16px.
Step 6 - The color code for the text is 0C0C0D.

**[Actual result]:**
Step 5 - The font size value is .875rem (14px).
Step 6 - The color code for the text is #4a4a4f.

**[Notes]:**
- Several other properties are also different comparing them to the [Invision document](https://mozilla.invisionapp.com/share/ASS7BZ9GUYP#/screens/365354398):
-> the background color of the banner is #DAE1E7 instead of #FFFFFF
-> the color of the "Learn more" link is #0a84ff instead of #0060DF
-> the font size of the "Learn more" link is .875rem (14px) instead of 16px.
- Attached a screen recording of the issue:

![differences UI](https://user-images.githubusercontent.com/26000308/58640304-72753280-8301-11e9-879a-83a3127022b7.gif)

**Comment by dannycoates** [comment]
fixed in #1344

**Comment by SoftVision-CarmenFat** [comment]
Tested this issue again and it seems that the color code for the plain text remained the same #4a4a4f instead of being changed to 0C0C0D. The rest of the elements were updated correctly and verified.
