### ISSUE TITLE
[Trailhead] The banner promoting the new Firefox Accounts is not displayed on mobile devices

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#1343]
**[Affected versions]:**
- Firefox Release 67 and up
- Google Chrome 74.0.3729.157

**[Affected Platforms]:**
- Android 8.0 (Samsung S8, Google Pixel)
- Android 6.0 (Huawei P8)

**[Steps to reproduce]:**
1. Open the browser and navigate to the https://send2.dev.lcip.org website.
2. Observe the top area of the website.

**[Expected result]:**
- The Trailhead banner is displayed.

**[Actual result]:**
- The Trailhead banner is not displayed.

**Comment by dannycoates** [comment]
fixed in #1344
