### ISSUE TITLE
Customize Appearance

### ISSUE THREAD

**Issue by heywoodlh** [mozilla/send#1345]
Is there any way to customize the appearance of Firefox Send? Our organization is looking to roll it out potentially for some use cases we think we would be useful.

Specifically, can I:
1. Remove ads for Firefox?
2. Change the background, favicon, icon, etc?

If not, then no worries. I love Firefox Send and our organization will probably use it even if we can't change these things. But it would be very nice if I could tweak these things.

I looked through documentation and other issues to find anything that addressed modifying the appearance of Firefox Send but I couldn't find anything. 

Thanks for any suggestions or help provided!

**Comment by clouserw** [comment]
Thanks for getting in touch with us.  You're welcome to modify the source of any deployments you do.  We're not going to support configuration variables for assets in the master branch.

**Comment by heywoodlh** [comment]
That's completely understandable. Thanks for the response @clouserw
