### ISSUE TITLE
Upload does not work on IOS (self-host)

### ISSUE THREAD

**Issue by JorgeGNL** [mozilla/send#1346]
We have installed SEND at our server Centos 7, after trying to upload a pic or video using IOS (any browser) the upload fails.

Is there an especial server configuration to allow uploads from IOS?

Thanks.

Centos 7 / local storage / Iphone X / IOS 12.3 / Any browser

![19-06-03 11-33-16 3740](https://user-images.githubusercontent.com/35146278/58792390-5d93ea00-85f4-11e9-9ef7-6bb976ccf22d.png)

**Comment by clouserw** [comment]
I tried this with Firefox release on iOS 12.4 and it worked as expected on send.f.c.  There are no special settings for iOS uploads so this might have been transitory or a misconfiguration.
