### ISSUE TITLE
[Trailhead] The banner doesn't correspond to the specifications on mobile devices 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#1347]
[Affected versions]:
- Firefox Release 67 and up

[Affected Platforms]:
- Android 8.0 (Google Pixel)
- Android 6.0 (Huawei P8)

[Steps to reproduce]:
1. Open the browser and navigate to the https://send2.dev.lcip.org website.
2. Observe the way the text is displayed inside the banner.

[Expected result]:
- The "Join Firefox. Learn more" string is displayed on the left side, on the second row.

[Actual result]:
- The "Join Firefox. Learn more" string is displayed on the first row.

[Notes]:
- Here are the [mock-ups](https://mozilla.invisionapp.com/share/ASS7BZ9GUYP#/screens/365354398) describing the banner in mobile view.
- Attached a screenshot of the issue:

![62222727_700036217120581_4389644988137340928_n](https://user-images.githubusercontent.com/26000308/58809512-c2673880-8624-11e9-8106-eeeb755d2654.jpg)

**Comment by dannycoates** [comment]
wontfix
