### ISSUE TITLE
[Send2] The elements from “Sign in” button are slightly moved or wrongly resized when hovering/ unhovering the button

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1350]
**[Regression range]:**
- This issue is not reproducible on Firefox 68 Beta and Firefox 69 Nightly. Considering this, using mozregression tool I have found the [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1535507) that fixed this in Beta and Nightly. Here is the [pushlog](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=365ff23dd4c93ef26743e3fa339b5fac3bf15b66&tochange=2bf6bddf9a8a5c52222273ee787bfca7e6c97394).

**[Affected versions]:**
- Firefox Beta 67.0.1

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the browser and navigate to the “https://send2.dev.lcip.org” website.
2. Hover the “Sign in” button.
3. Observe the “Sign in” button.

**[Expected result]:**
- The buttons hover effect is correctly displayed.

**[Actual result]:**
- Depending on the UI of the button, the elements are slightly moved or wrongly resized one additional time 

**[Notes]:**
- This issue is reproducible with all the UIs of the “Sign in” button. 
- This issue is not reproducible on other browsers.
- Attached a screen recording of the issue:

![rec of issue -  Send2 -  Sign in button](https://user-images.githubusercontent.com/37875464/59348334-7e102280-8d1f-11e9-885a-51806d95f599.gif)

**Comment by clouserw** [comment]
Thanks for filing.  Closing as Fx69 was just released which makes this a couple versions back.
