### ISSUE TITLE
Download file bigger than 1 Go doesn't work - Windows 10 - Firefox / Chrome / Opera 

### ISSUE THREAD

**Issue by MoiMiph** [mozilla/send#1351]
I just begin to user this service with my account to upload 2 zip files (950 Mb and 1,2 Gb).
"Fire fox Send" made me a single file Send-Archive.zip on the server.
Things worked great for the upload, but now I 'm not able to dowload my "Send-Archive.zip" because the download fail on about 47 % (1 Gb of data).

I tried to download from different web browsers (Firefox 67.01, Chrome, Opera) and from différent OS / devices (ubuntu, Windows 10, Android) with the same result.
Did some one got the same problem?
How can I resolve this issue?

Thanks.

**Comment by havardge** [comment]
Same issue. Download stops at 1GB.

**Comment by sebpuetz** [comment]
Same for me, get up to 50% of a 2GB archive, then the download stops.

**Comment by clouserw** [comment]
Is this still reproducible?  If so, could you send me the URL you have problems with?  Email to wclouser at mozilla dot com would be great.  Thanks
