### ISSUE TITLE
Please Provide Apache Reverse Proxy Config

### ISSUE THREAD

**Issue by SaulMoonves** [mozilla/send#1358]
I took a whack at it and came up with: enabling mod_wstunnel; and then a VirtualHost containing (at least):

```
Requestheader set X-Forwarded-Proto https

ProxyPreserveHost On
ProxyPass "/" "http://127.0.0.1:1443/"
ProxyPassReverse "/" "http://127.0.0.1:1443/"

<Location ~ "/api/ws">
        ProxyPass "ws://127.0.0.1:1443/api/ws"
        ProxyPassReverse "ws://127.0.0.1:1443/api/ws"
</Location>
```

However, I do not know how correct this is. Would like some confirmation.

*edit - now this config works.

**Comment by clouserw** [comment]
Looks like this is available at https://github.com/mozilla/send/blob/master/docs/deployment.md#apache-webserver
