### ISSUE TITLE
Can we limit the display of the promo banner to only non-firefox userAgents?

### ISSUE THREAD

**Issue by oliver-dvorski** [mozilla/send#1360]
It's just a thought. Personally, I'm super annoyed by the thing but that isn't really relevant. I'd just like to know if this is a design decision or not.

Sorry if I'm posting in the wrong place, I don't see a forum anywhere so... here we are

**Comment by clouserw** [comment]
The design decision was to repurpose the "Download Firefox" bar with a "Join Firefox" link -- which is something that may interest Firefox users as well.  This was done in #1340 so I'm closing this.
