### ISSUE TITLE
Add a 'deploy to Heroku' button

### ISSUE THREAD

**Issue by aurora-of-earth** [mozilla/send#1361]
Add a one-click 'deploy to heroku' button to easily  host a private instance.

**Comment by yogishb608** [comment]
@aurora-of-earth Hi I would like to take this. Let me know where to add.

**Comment by fzzzy** [comment]
I would recommend putting it in the README file.

**Comment by yogishb608** [comment]
@fzzzy I need little more clarity on this. Like on click where to redirect?

**Comment by aurora-of-earth** [comment]
@yogishb608 @fzzzy something like <a href="https://github.com/Rudloff/alltube#on-heroku">this</a>.

**Comment by yogishb608** [comment]
@aurora-of-earth Got it. will do it. Thanks a lot :).

**Comment by yogishb608** [comment]
[#1365 ](https://github.com/mozilla/send/pull/1365)

**Comment by clouserw** [comment]
Closing based on #1365
