### ISSUE TITLE
Wrong password when downloading in Google Chrome !?

### ISSUE THREAD

**Issue by DominicDesbiens** [mozilla/send#1367]
Hi,

I've just sent a file to a friend. Set a password for it. When open the download link in Firefox, the password for the file is OK, but in Google Chrome, it says wrong password !

No space in the password, only numbers, letters and a special char « ! ».

Please fix this...

**Comment by clouserw** [comment]
Thanks for filing this.  We tried to reproduce this with uploading in Firefox Nightly and downloading in Chrome 76.  I tried a password of `test!123` and it worked as expected.  If you have more steps to reproduce we can look again, but as of now I'll close this.
