### ISSUE TITLE
can you open source the landing page ?

### ISSUE THREAD

**Issue by lucasverra** [mozilla/send#1373]
Looks gorgeous :)

**Comment by theREALaltoid** [comment]
I'll be willing to scrape the code if mozilla will give me permission.

**Comment by lucasverra** [comment]
@theREALaltoid 

![image](https://user-images.githubusercontent.com/11323803/61701359-5066c200-ad3e-11e9-9fa2-1b7ac74a2930.png)

normally they should

**Comment by luciusmagn** [comment]
Howdy,
I am not really well versed in the arts of Firefox Send, but we are running
our own fork of Send in our friends group and I made changes in the landing
page, so I am pretty sure it is opensourced and in the repository as well.
it's templates, but you should still be able to pick it off and do
something with it.

**Comment by clouserw** [comment]
Everything is already in this repository.  If you're talking about the UI on send.firefox.com look at https://github.com/mozilla/send/tree/master/app/ui
