### ISSUE TITLE
Investigate failed uploads / downloads

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#1377]
There's been some mention of hanging uploads and downloads on the web. This for example: https://old.reddit.com/r/firefox/comments/cjpmhm/real_world_review_for_firefox_send/

I may have reproduced it and got this error in the browser:
<img width="561" alt="Screen Shot 2019-07-31 at 9 26 56 AM" src="https://user-images.githubusercontent.com/87619/62229886-8b3bac00-b375-11e9-92be-fc9c7dfb9063.png">

Note: Send currently isn't staffed. Add a 👍 if this issue affects you.

**Comment by LoneFenris** [comment]
#1280 potentially related on the download side.

**Comment by aakay** [comment]
Hi @dannycoates , thanks for the investigation and the ticket.

I'm the author of the post. If there's something I can help, please don't hesitate to contact me.

**Comment by dannycoates** [comment]
@aakay thanks for your patience. Our next release will hopefully fix most upload issues and provide us better error reporting to help identify any others. If you're interested I welcome you to try it out before release on our testing site https://send2.dev.lcip.org

**Comment by aakay** [comment]
Hey @dennycoates, thanks a lot for the fix. I’d love to help whenever I can. Sure, I’ll try it when I need to send a file, as I’ve done till now :).

**Comment by dannycoates** [comment]
v3.0.16 was released yesterday. Early data suggests our internal connection issue is fixed but "regular" connection issues between the device and us can still be improved with a more robust retry mechanism. I'm closing this in favor of #1380
