### ISSUE TITLE
Changes to config handling in 3.0.16

### ISSUE THREAD

**Issue by TwizzyDizzy** [mozilla/send#1379]
Hi @dannycoates,

in https://github.com/mozilla/send/commit/f0407f9beb942d4d5dbb69e221fb225fb9dc2b0a you seem to have changed the handling of configuration files.

I dug a bit into https://github.com/dannycoates/configstore which suggested that the config file needs to be stored in `~/.config/configstore/[some-identifier].json` so I moved my config to `~/.config/configstore/send.json`. That didn't work unfortunately.

I think the "Configuration" section in README.md should be modified in order to reflect those changes. Depending on how to get things working, it may also make sense to document how `/server/config.js` and `~/.config/configstore/[some-identifier].json` intertwine.

What do you think? Am I missing something?

Cheers & Thanks
Thomas

**Comment by TwizzyDizzy** [comment]
Ah well... it seems it's not in real use, yet?

**Comment by dannycoates** [comment]
@TwizzyDizzy the configstore is only used by our `@google-cloud/node-storage` dependency for resumable uploads. The config for Send itself hasn't changed.
