### ISSUE TITLE
Error when uploading files

### ISSUE THREAD

**Issue by hiCasper** [mozilla/send#1383]
When I set NODE_ENV=production then upload the file from Chrome, the browser will warn:

> Refused to connect to 'ws://sxnat.server.hicasper.com:18001/api/ws' because it violates the following Content Security Policy directive: "connect-src 'self' wss://*.dev.lcip.org wss://*.send.nonprod.cloudops.mozgcp.net wss://send.firefox.com https://*.dev.lcip.org https://accounts.firefox.com https://*.accounts.firefox.com https://sentry.prod.mozaws.net".

But it won't happen if I use dev mode. How can I fix it without using an FXA server?
If an FXA server is required: Can we use the one from Mozilla and - if yes - how can we obtain a client id?

**Comment by clouserw** [comment]
You're running into a CSP policy.  You'll need to add the domain name you want to connect to to the `connectSrc` list at https://github.com/mozilla/send/blob/master/server/routes/index.js#L38
