### ISSUE TITLE
web client issue on loading : blanck screen 

### ISSUE THREAD

**Issue by lucasverra** [mozilla/send#1391]
here it is on latest firefox macOs

![image](https://user-images.githubusercontent.com/11323803/64416443-7bf7fe80-d097-11e9-871a-a8166ea34795.png)

**Comment by NoUsername** [comment]
Same on Windows 10 with Firefox Developer Edition 70.0b3 (64-bit)

**Comment by lucasverra** [comment]
seems fixed now but will let contributors to close

**Comment by gcp** [comment]
I guess this might be the same as https://github.com/mozilla/send/issues/1392.

**Comment by gcp** [comment]
And probably #1390

**Comment by dannycoates** [comment]
Thanks for the reports everyone. closing as a duplicate of #1390
