### ISSUE TITLE
Unable to upload files; fails at 98% or 100%

### ISSUE THREAD

**Issue by arunsathiya** [mozilla/send#1395]
I am on the latest version of the [Firefox Android app](https://play.google.com/store/apps/details?id=org.mozilla.firefoxsend). Version 1.0.

Uploading 5-6 JPG files fails with no error. The upload goes through 98% or 100% and does not respond.

**Comment by 805bluebell** [comment]
It's working like charm. Get's a link for a zip file for 5-6 images.

**Comment by arunsathiya** [comment]
Thanks for testing! This does not seem to be an issue anymore. Closing.
