### ISSUE TITLE
Unable to cancel ongoing uploads

### ISSUE THREAD

**Issue by arunsathiya** [mozilla/send#1396]
When flagging up https://github.com/mozilla/send/issues/1395, I noticed that canceling any ongoing uploads does not work. The `Cancel` button simply does not respond.

**Comment by clouserw** [comment]
Is this a duplicate of #1316?

**Comment by arunsathiya** [comment]
This does not seem to be an issue anymore. I am able to cancel uploads as expected. Closing.
