### ISSUE TITLE
Storage folder question

### ISSUE THREAD

**Issue by MKdent** [mozilla/send#1403]
Hi, I finally could run mozilla send on my server. But where is the location of the storage folder? In config I see adjustment for amazon aws, but local storage?
I don't find my uploaded files.... Is storage on own server possible? Maybe someone can give me a hint. Thanks!

**Comment by dannycoates** [comment]
Hi @MKdent. You can set the `FILE_DIR` environment variable to the path you'd like to store files. It defaults to a system temp directory. You can find all config options define in https://github.com/mozilla/send/blob/master/server/config.js#L131

**Comment by MKdent** [comment]
Have not seen it:-) Thank you @dannycoates!

**Comment by MarwaAbdallah** [comment]
I mean, example of env variable set as well as parameters modified in cionfig.js, say,for when running in prod mode
