### ISSUE TITLE
New locales not available in dev server

### ISSUE THREAD

**Issue by flodolo** [mozilla/send#1414]
A new locale started translating Firefox Send (`trs`), but the locale doesn't show up on the dev server:

1. Change `intl.accept_languages` and set `trs` as first language
2. Visit https://dev.send.nonprod.cloudops.mozgcp.net/

CC @dannycoates @guerojeff

**Comment by flodolo** [comment]
Am I missing something obvious, e.g. the locale needs to be added somewhere even for the dev server? Do we have some issues with code?

Note that this is not limited to one locale, e.g. `ppl` is another one affected. Content has been committed by Pontoon to the repository
https://github.com/mozilla/send/tree/master/public/locales

**Comment by dannycoates** [comment]
Confirmed. However, it works in local dev so this is either a build or config issue

**Comment by fzzzy** [comment]
The tests have been failing recently, I think, so that may be blocking dev from getting deployed.

**Comment by dannycoates** [comment]
fixed on http://send2.dev.lcip.org

**Comment by flodolo** [comment]
Thanks. Looks like we have 3 new locales at 100%, and one at almost 80%. I'll test them in the coming days and get a PR to add them to prod list.
