### ISSUE TITLE
Download always breaks at 61% 

### ISSUE THREAD

**Issue by ShalokShalom** [mozilla/send#1426]
Tried with 4 different devices, 2 phones and 2 desktops. Windows, KaOS and Android. Different browsers as well.

Also, there is no proper error message. It simply says "An error has occurred."

https://send.firefox.com/download/732ee822fcf08f36/#11K83-NOFSoGL6YRcZDTZw

**Comment by timvisee** [comment]
I'm wondering wether the same happens with:

- the same file uploaded another time
- with another file having the same size
- with another file having a larger size

Have you tried any of those things?

**Comment by ShalokShalom** [comment]
It works now. thanks :hugs:
