### ISSUE TITLE
中国区下载速度怎么样

### ISSUE THREAD

**Issue by usbcdrom** [mozilla/send#1433]
中国区下载速度怎么样

**Comment by Lin-Buo-Ren** [comment]
Friendly translation: How is the download speed in China region.

**Comment by usbcdrom** [comment]
> 友善翻译：中国地区的下载速度如何？

你好我已经测试了，中国区下载速度不错

**Comment by Lin-Buo-Ren** [comment]
> > 友善翻译：中国地区的下载速度如何？
> 
> 你好我已经测试了，中国区下载速度不错

Hello, as the problem is resolved, can you close this issue?

**Comment by xiaopangju** [comment]
这个问题已经解决了，请问你能关闭这个issue吗

**Comment by SoftVision-CiprianMuresan** [comment]
Closing this issue as Resolved based on the above comments.
