### ISSUE TITLE
Mozilla Send login does not require MFA

### ISSUE THREAD

**Issue by napcode** [mozilla/send#1444]
I noticed that I'm not being asked for my 2nd factor when logging into [send.firefox.com](send.firefox.com). I wonder whether this is intentional and whether this can be abused somehow?

**Comment by WesleyBranton** [comment]
Do you have 2FA enabled on your Firefox Account? If you do, it's not surprising that you need to do 2FA when logging into that account.

**Comment by napcode** [comment]
Yes, I have 2FA enabled on my Firefox Account. I'm surprised that I'm **not** being asked when logging into Firefox Send. Is this intentional?

**Comment by WesleyBranton** [comment]
Oh! Sorry, I misread that.

To the best of my knowledge, you should get the 2FA in Firefox Send, unless you are already signed into your Firefox Account on the browser somewhere else (like Firefox Sync, etc).

**Comment by napcode** [comment]
Indeed! Just tried a private session in a different browser and voila: it works as expected. Thanks for the clarification.
