### ISSUE TITLE
Don't show "There is a way to protect your privacy. Join Firefox." when signed into Firefox Account

### ISSUE THREAD

**Issue by yoasif** [mozilla/send#1446]
From: https://www.reddit.com/r/firefox/comments/fdg7pj/its_quite_annoying_to_continue_to_see_this_header/

Hide the header "There is a way to protect your privacy. Join Firefox." when signed into Firefox Account - I tested this, and this header remains.

![image](https://user-images.githubusercontent.com/152493/75908057-6cbff680-5e17-11ea-9793-449c826973cf.png)

**Comment by dannycoates** [comment]
we no longer have this promo, there's a new one though...
