### ISSUE TITLE
After saving the password for a password-protected file, all future uploads are unexpectedly protected by the same password

### ISSUE THREAD

**Issue by groovecoder** [mozilla/send#1449]
STR: 

1. Upload a file
2. Check "Protect with password"
3. Use Firefox password generation to generate the password
4. Click "Upload"
   * Firefox automatically saves the generated password
5. Upload another file
   * "Protect with password" in NOT checked
   * But, the hidden password field is auto-filled by Firefox
6. Send link to recipient

Expected Results:
Recipient doesn't need a password to download the 2nd file

Actual Results:
Because the hidden password field was auto-populated by Firefox saved password, the upload is protected by the saved password

**Comment by dannycoates** [comment]
_should_ be fixed here 55df0615672bb3b9f2eaaf84d257e2f630943c49
