### ISSUE TITLE
A couple "Content Security Policy" errors/warnings

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#145]
Found in https://fileshare.stage.mozaws.net/__version__ (a7fcb1a):

```json
{
  "commit": "a7fcb1a",
  "source": "https://github.com/mozilla/something-awesome/",
  "version": "0.1.2"
}
```

---

> Content Security Policy: Couldn’t process unknown directive ‘default-src:’
> Content Security Policy: Couldn’t process unknown directive ‘report_uri’

<img width="719" alt="firefox_fileshare" src="https://user-images.githubusercontent.com/557895/27550630-432787de-5a55-11e7-8ede-eb4f458f5793.png">

**Comment by dannycoates** [comment]
I don't know where those headers are coming from. Not the app.

Anyway, it prompted me to add some...

**Comment by dannycoates** [comment]
It's still there after adding a csp header in the app. @relud is this an nginx thing?

**Comment by relud** [comment]
yes, nginx is doing the following:
<pre>
add_header Content-Security-Policy "default-src: 'none'; report_uri /__cspreport__";
add_header Public-Key-Pins 'max-age=86400; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=";';
</pre>
these are standard cloudops headers, and there wasn't a CSP or HPKP header in the app yet, so i enabled them.

**Comment by dannycoates** [comment]
> there wasn't a CSP or HPKP header in the app yet, so i enabled them.

ok, cool. Can we remove the CSP one now that the app is doing it?

Also just FYI, `default-src: 'none'; report_uri /__cspreport__` has syntax errors. It should be `default-src 'none'; report-uri /__cspreport__` (no colon after default-src and - for report-uri)

**Comment by relud** [comment]
done. i'll trigger a jenkins build to get the update out
