### ISSUE TITLE
Is redis optional?

### ISSUE THREAD

**Issue by cyphunk** [mozilla/send#1457]
The README says "Redis server (optional for development)" but in issue #1263 for docker it is said one has to supply the REDIS_HOST value. There is some confusion. Could someone clarify if redis is optional or not?

Many thanks

**Comment by micah** [comment]
It seems you *need* redis if you are going to use the Dockerfile here, but without docker, I don't know.

**Comment by dannycoates** [comment]
Yes, with the docker image redis is required.
