### ISSUE TITLE
"Something went wrong" when I try to login in Private Mode

### ISSUE THREAD

**Issue by lealceldeiro** [mozilla/send#1464]
Whenever I try to login so I can have the ability to share files larger that 1GB I get the message "Something went wrong". For what is worth, I have 2FA activated.

Flow: Login > input password > input 2FA code > "Something went wrong" (refer to below image)

Possible duplicate https://github.com/mozilla/send/issues/1429, but I'm not sure, though. I'm navigating in private mode, and even after adding the domain to the exceptions as described in the linked ticket the error continues happening.

![firefox-send-error](https://user-images.githubusercontent.com/15990580/79691794-2ceb8c00-826a-11ea-9661-ed9bab534028.gif)

**Comment by leoc59** [comment]
same

**Comment by gmixer** [comment]
Same

**Comment by flodolo** [comment]
It works fine for me. Is there anything out of the ordinary in your installation, e.g. using container, changed specific privacy settings? Does it work in a clean profile?

**Comment by lealceldeiro** [comment]
> It works fine for me. Is there anything out of the ordinary in your installation, e.g. using container, changed specific privacy settings? Does it work in a clean profile?

Built-in installation that comes with Linux mint, updated as per updates from the Linux repositories.
However I have some  custom settings (including privacy ones). Is there anyway I can share safely my configuration with you so you can try to reproduce it?

**Comment by flodolo** [comment]
> However I have some custom settings (including privacy ones) and I'm browsing in private mode. Is there anyway I can share safely my configuration with you so you can try to reproduce it?

Not that I can think of. I think the easiest solution would be to try a new profile, and change settings one at a time.

P.S. non really a developer, just a user.

**Comment by lealceldeiro** [comment]
> > However I have some custom settings (including privacy ones) and I'm browsing in private mode. Is there anyway I can share safely my configuration with you so you can try to reproduce it?
> 
> Not that I can think of. I think the easiest solution would be to try a new profile, and change settings one at a time.
> 
> P.S. non really a developer, just a user.

I'll try your recommendation and see if I can find out anything. I'll post my findings here as soon as I get something.

**Comment by gmixer** [comment]
I've tried a new private tab, and it works.

I believe it may be this plugin:

https://gitlab.com/smart-referer

**Comment by lealceldeiro** [comment]
> > However I have some custom settings (including privacy ones) and I'm browsing in private mode. Is there anyway I can share safely my configuration with you so you can try to reproduce it?
> 
> Not that I can think of. I think the easiest solution would be to try a new profile, and change settings one at a time.
> 
> P.S. non really a developer, just a user.

@flodolo I followed your suggestion and started with a new profile.

Without changing any configuration and browsing as a regular user it works.

Without changing any configuration and browsing in **private mode** it **does NOT work**.

So, it seems we identified the root cause (maybe).

**Comment by suicidesky92** [comment]
The same thing, but works after authorization. Firefox Quantum 66.0.1 (64-bit)

**Comment by wls** [comment]
Is this related to [issue 1267](https://github.com/mozilla/send/issues/1267)?

That issue is closed, but I just posted a comment with error logs, code, settings, and extensions that may be helpful.  Happens in Firefox 77.0 (64-bit) Mac.

**Comment by lealceldeiro** [comment]
> Is this related to [issue 1267](https://github.com/mozilla/send/issues/1267)?
> 
> That issue is closed, but I just posted a comment with error logs, code, settings, and extensions that may be helpful. Happens in Firefox 77.0 (64-bit) Mac.

Yes, @wls , it is related to that one, but the cause may be different... [I tried with a fresh new profile](https://github.com/mozilla/send/issues/1464#issuecomment-622951606) (using defaults) and it works until I switch to *private mode*.

**Comment by fzzzy** [comment]
It's a known issue that Send doesn't work in Private Browsing. Service Workers are not available in Private Browsing and the Send implementation heavily depends on them.
