### ISSUE TITLE
Drag & drop feature doesn't work on some web pages

### ISSUE THREAD

**Issue by helperman** [mozilla/send#1474]
Drag & Drop feature works on https://send.firefox.com/
but doesn't work on https://send.firefox.com/login/
If D&D feature is featured in a web page it has to be supported.

Steps to reproduce:
https://youtu.be/iWSJzsZIs20

Expected: a file dropped successfully on any web page that announce this feature
Actual: the file is opened in browser

**Comment by dannycoates** [comment]
thanks, fixed here 55df0615672bb3b9f2eaaf84d257e2f630943c49
