### ISSUE TITLE
Add static asset revisioning?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#150]
I just remembered we use [**gulp-rev-all**](https://github.com/smysnk/gulp-rev-all) on [**mozilla/testpilot**](https://github.com/mozilla/testpilot/blob/02829d3d0c47cf23b94096d89835eb5a53a3cfb9/package.json#L79) to add SHAs to our assets (like converting /static/bundle.js into /static/bundle.098f6bcd.js).

**Comment by dannycoates** [comment]
done in #516
