### ISSUE TITLE
Redirect to 404 page is not performed if you click the "Download" button after file has expired

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#158]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://fileshare.dev.mozaws.net/" page.
2. Upload a file and open the download link in two different tabs.
3. Download the file in the first tab and then navigate to the second tab.
4. Click the download button and observe the behavior.

[Expected result]:
- The page is refreshed and the "Link expired" page is displayed.

[Actual results]:
- Nothing happens.

[Notes]:
- This issue is also reproducible on the stage page (https://fileshare.stage.mozaws.net). 
- If the page is manually refreshed, the "Link expired" page is correctly displayed.
- Here is a screen recording with the issue:
![404 page not displayed after clicking on the download button](https://user-images.githubusercontent.com/18304511/27834006-d343905e-60dd-11e7-898f-518d983a5af6.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page (https://fileshare.dev.mozaws.net/).

**Comment by pdehaan** [comment]
> The issue is no longer reproducible on the Dev page (https://fileshare.dev.mozaws.net/).

FWIW, that's an old site. The latest code is deployed to https://send.dev.mozaws.net/

**Comment by SoftVision-CiprianMuresan** [comment]
Crap, I copied an older comment. I did verify the issue on https://send.dev.mozaws.net/ though.

**Comment by pdehaan** [comment]
We also have an issue for deleting the old/dead servers (see #163). Hopefully we kill fileshare.* while we're at it, since I end up looking at those pages by mistake via autocomplete far too often.
