### ISSUE TITLE
[enhancement] Look into RFC 8188

### ISSUE THREAD

**Issue by clouserw** [mozilla/send#174]
Martin Thomson commented on our flow diagram about his work in RFC 8188 to chunk large encrypted files over HTTP.  Let's look into that here after we ship v1.  Benefits would be:

  - Client could start decrypting sooner
  - Client wouldn't need to download the entire file to learn the first byte was bad
  - We could do some more complex resume operations if a download is interrupted
  - Combined with P2P there could be some interesting scenarios and speedups

**Comment by ehuggett** [comment]
Would chunking (in theory) also make it possible for the receiver to start downloading before the upload has been completed by the sender? As files expire after 24 hours this might be useful for sending larger files when both parties have a slow connection.

**Comment by dannycoates** [comment]
Yes, this could (in theory) allow the download and upload to happen in parallel. Another advantage is that it uses less memory so would allow for larger files and more limited devices.
