### ISSUE TITLE
[Enhancement] User should be informed that canceling the file open/save flow will invalidate the download URL

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/send#175]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a file uploaded on https://send.dev.mozaws.net (download link for the file was generated).

[Steps to reproduce]:
1. Start the Firefox/Nightly browser and paste the link for the existing uploaded file into URL bar.
2. Click on "Download File" button and wait for the download to finish.
3. Click on "Cancel" button from the save file popup.

[Expected result]:
- The user should be informed that if the action is cancelled, the file and link will not be available anymore.

[Actual results]:
- If the save file popup is closed without saving, the file and download link are no longer available.

[Notes]:
- Here is a screen recording with the issue:

![save dialog](https://user-images.githubusercontent.com/9248513/28019270-166d61de-6589-11e7-8c54-212f6890302f.gif)

**Comment by himanish-star** [comment]
@dannycoates , Can I fix this ?

**Comment by dannycoates** [comment]
this doesn't apply to vnext since there aren't two phases anymore
