### ISSUE TITLE
Add FAQ.md file/wiki with some common questions/answers?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#186]
### /FAQ.md

> "How big of a file can I transfer with Firefox Send" (See https://github.com/mozilla/send/issues/176#issuecomment-314152786)

> "Why is my browser not supported?" (See https://github.com/mozilla/send/issues/101#issuecomment-314582822)

> "How long are files available for?" &mdash; One download or 24 hours, whichever comes first.

> "Can a file be downloaded more than once?" &mdash; No.

**Comment by wresuolc** [comment]
draft @ https://docs.google.com/document/d/1gk2Z2jw6CLivHld9gCGZzCX102d_G--20VHEX6CJ3zo/edit?usp=sharing

r? @pdehaan @johngruen

**Comment by pdehaan** [comment]
Sorry, I commented on the goog doc, but didn't follow up here...
The FAQ looks awesome 👍. Pending any further feedback from Mr. @johngruen, I think it's safe to PR it and we can merge+tweak as needed.
