### ISSUE TITLE
More bulletproof server meta validation

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#192]
Randomly spotted while trying to track down why my CLI file uploading was failing...

Re: [/server/server.js:191-199](https://github.com/mozilla/send/blob/52173bf6e79c35fbba7e3493fae94ebf9d53b4c0/server/server.js#L191-L199), I think we're doing some things out of order here, since we're trying to validate the `meta.id` value before checking if the `meta` object has an 'id' property:

```js
  if (
    !validateIV(meta.id) ||
    !meta.hasOwnProperty('aad') ||
    !meta.hasOwnProperty('id') ||
    !meta.hasOwnProperty('filename')
  ) {
    res.sendStatus(404);
    return;
  }
```

**Comment by abhinadduri** [comment]
fixed in #197
