### ISSUE TITLE
Don't send analytics if DNT is enabled

### ISSUE THREAD

**Issue by wresuolc** [mozilla/send#196]
When we add the GA code, let's make sure it doesn't load at all if DNT is enabled

**Comment by chuckharmston** [comment]
v0.1.2 of [`testpilot-ga`](https://github.com/mozilla/testpilot-ga) automatically handles this.

**Comment by dannycoates** [comment]
closing since we're using ^

**Comment by pdehaan** [comment]
Ref: #268 which adds GA code.
