### ISSUE TITLE
Upload and download progress bars are different colors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#205]
Found in https://send.dev.mozaws.net/__version__ (9735aa6):

```json
{
  "commit": "9735aa6",
  "source": "https://github.com/mozilla/send/",
  "version": "0.1.2"
}
```

---

<img width="632" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28294158-0a6a075a-6b0d-11e7-87c8-a973acd97fbb.png">

**Figure 1:** Upload circle progress bar. (Ref: [/frontend/src/upload.js:68](https://github.com/mozilla/send/blob/729f716e97b0045fbed222da4fa65a8f50da8329/frontend/src/upload.js#L68))

---

<img width="480" alt="download_your_file" src="https://user-images.githubusercontent.com/557895/28294174-2912fb1c-6b0d-11e7-9a2f-2970f708f75b.png">

**Figure 2:** Download circle progress bar. (Ref: [/frontend/src/download.js:18](https://github.com/mozilla/send/blob/729f716e97b0045fbed222da4fa65a8f50da8329/frontend/src/download.js#L18))

**Comment by dnarcese** [comment]
This was done according to the mocks

**Comment by wresuolc** [comment]
Let's use the in-progress blue

**Comment by MichaelKohler** [comment]
Looks like this has been done, at least I can't reproduce locally. Could somebody confirm?

**Comment by dannycoates** [comment]
@MichaelKohler indeed it has. We'll have some more "Good First Bug"s shortly :)

**Comment by MichaelKohler** [comment]
(oh, and I just noticed that this issue has been closed before my comment, had it open and didn't refresh, sorry!)
