### ISSUE TITLE
Download SVG is black and white on download page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#208]
Found in  https://send.dev.mozaws.net/__version__ (9735aa6):

```js
{
  commit: "9735aa6",
  source: "https://github.com/mozilla/send/",
  version: "0.1.2"
}
```

---

<img width="675" alt="download_your_file" src="https://user-images.githubusercontent.com/557895/28295215-f9b045da-6b13-11e7-8f46-3ec3a34da340.png">

<img width="646" alt="blank_skitch_document" src="https://user-images.githubusercontent.com/557895/28295271-66dfac4a-6b14-11e7-95c4-7a70ef5e46c2.png">

But oddly, this works for me in Chrome:

<img width="718" alt="download_your_file" src="https://user-images.githubusercontent.com/557895/28295262-5a103ac0-6b14-11e7-8e28-368cdac7da69.png">

**Comment by pdehaan** [comment]
In Firefox Beta (and Nightly), the SVG looks fine on the broken link page: https://send.dev.mozaws.net/download/abcde12345

<img width="718" alt="download_your_file" src="https://user-images.githubusercontent.com/557895/28295792-482d2800-6b18-11e7-8bc2-cb954183a2b8.png">
,

**Comment by dnarcese** [comment]
I'm aware of this issue and have looked into it. It seemed like it was getting blocked by the CSP, but since it works in Chrome, it is likely a Firefox bug. I have filed a bug for it ([Bug 1381127](https://bugzilla.mozilla.org/show_bug.cgi?id=1381127)), just waiting to see what happens.

**Comment by wresuolc** [comment]
You can get rid of classes and the style tag and add styles to the svg
