### ISSUE TITLE
TypeError: document.querySelector(...) is null

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#209]
Found in https://send.dev.mozaws.net/__version__ (9735aa6):

```js
{
  "commit": "9735aa6",
  "source": "https://github.com/mozilla/send/",
  "version": "0.1.2"
}

```

---

### Steps to reproduce:

1. Go to https://send.dev.mozaws.net/download/abcde12345
2. Open developer tools console.

### Actual results:

<img width="958" alt="download_your_file" src="https://user-images.githubusercontent.com/557895/28295938-7ac25622-6b19-11e7-875d-93c1ef6a7f14.png">

I _think_ this is coming from [/frontend/src/upload.js:344-351](https://github.com/mozilla/send/blob/5ce0846580d77251fe812054a554786bb8adb255/frontend/src/upload.js#L344-L351):

```js
  function toggleHeader() {
    //hide table header if empty list
    if (document.querySelector('tbody').childNodes.length === 1) {
      $('#file-list').hide();
    } else {
      $('#file-list').show();
    }
  }
```

Not sure if we need to do a check for the `document.querySelector('tbody')` result before trying to access `.childNodes.length`.

**Comment by dnarcese** [comment]
So this is happening because both the upload and download js files are running on each page, since they are bundled together. A couple solutions to only load the relevant file:
- setup two separate bundles with browserify: one for upload, one for download 
- wrap each js file in a check for the correct url

Any other ideas or suggestions?

**Comment by dannycoates** [comment]
I like the two bundle option. We should make upload.js and download.js be the entry points for each bundle and have a common.js that they each require for shared code (what's currently in main.js).
