### ISSUE TITLE
Asset & measurement for logo

### ISSUE THREAD

**Issue by Pekochen** [mozilla/send#212]
Please check the link as below.
https://mozilla.github.io/testpilot-assets/Send/Send_logo%20design/
Assets
https://github.com/mozilla/testpilot-assets/blob/master/Send/00_Assets/send%20logo.svg
https://github.com/mozilla/testpilot-assets/blob/master/Send/00_Assets/Send%20logotype.svg
Thank you~

**Comment by youwenliang** [comment]
https://mozilla.github.io/testpilot-assets/Send/Send_logo%20design/

**Comment by ChenMorpheus** [comment]
@ericawright I noticed you closed the ticket before we updated the assets. In case you don't know, Peko updated the measurement and assets to add subtitle for the logotype.

**Comment by ericawright** [comment]
Sorry about that. Daniela is working on getting the new one in right away.

**Comment by ChenMorpheus** [comment]
@ericawright No worries. I just realized you were so efficient that I was afraid you didn't notice the update. Thanks. ; )
