### ISSUE TITLE
File titles are not wrapped if they are very long and contain no spaces

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#216]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a file with a very long filename (>150 characters with no spaces) and observe the page.
3. Copy the link and navigate to the file download page.
4. Observe the page.

[Expected result]:
- Step 2 & 4: The filename is correctly displayed on the Upload and Download pages.

[Actual results]:
- Step 2 & 4: A horizontal scrollbar appears and the file name is not wrapped to a second row.

[Notes]:
- Here is a screen recording with the issue:
![long filename with no spaces](https://user-images.githubusercontent.com/18304511/28315355-b3c4f5a8-6bc6-11e7-9d90-47ca4e350232.gif)

**Comment by pdehaan** [comment]
+1 for just adding a cheap "..." truncation using `text-overflow: ellipsis;` as a quick, hacky solution.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page. Marking as verified.
