### ISSUE TITLE
Delete button does not bring up a confirmation dialog

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#217]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a file and click the "Delete file" button.
3. Observe the behavior.

[Expected result]:
- A confirmation dialog appears asking the user to confirm the deletion. 

[Actual results]:
- The file is deleted.

[Notes]:
- For an action as important as deleting something, I think it would be best to have a confirmation dialog to delete a file. Especially on the "Copy link" page.
- Here is a screen recording with the issue:
![no confirmation dialog for delete](https://user-images.githubusercontent.com/18304511/28315923-379ea016-6bc9-11e7-81f6-da10bc65c40a.gif)

**Comment by pdehaan** [comment]
**Proposal:** Make the button background color red, or something equally intimidating to possibly deter people from clicking it. Ref #270

**Comment by gene1wood** [comment]
Really just any indication as to whether or not the delete was successful would be great here.

**Comment by himanish-star** [comment]
@pdehaan , I'm on it

**Comment by shikhar-scs** [comment]
I guess we still are missing a pop-up for delete button on the set password page. May I work on that ?

**Comment by himanish-star** [comment]
@shikhar-scs , I have done that too !

**Comment by SoftVision-CiprianMuresan** [comment]
I have to reopen this issue, while the confirmation dialog does appear when the button is clicked, the buttons (Cancel, Yes) do not work and the dialog can't be dismissed by clicking away from it:

![delete dialog buttons do not work](https://user-images.githubusercontent.com/18304511/34717061-72b883e2-f53a-11e7-9a5e-aa9170d46604.gif)

**Comment by himanish-star** [comment]
@SoftVision-CiprianMuresan , you can see my PR all works fine.  It may be due to some small errors with new commits that it's not working. But don't worry I'll fix it in a while

**Comment by SoftVision-CiprianMuresan** [comment]
@himanish-star, it seems to work fine on Chrome, Safari and Opera, but it does not work on Firefox Release, Beta or Nightly.

**Comment by himanish-star** [comment]
@SoftVision-CiprianMuresan , OK I'll see to this

**Comment by himanish-star** [comment]
@SoftVision-CiprianMuresan , are you now satisfied with the changes.

**Comment by SoftVision-CiprianMuresan** [comment]
![image](https://user-images.githubusercontent.com/18304511/34774749-3db8b10a-f619-11e7-8d91-63121b83f763.png)

Yes. 

The dialog box and its buttons now work correctly on Firefox too. Thank you for all your hard work.

**Comment by shikhar-scs** [comment]
I'm laughing harder than I should :smile: :smile: :smile:
