### ISSUE TITLE
[Enhancement] Delete button should have a red background to help it stand out more

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#220]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a file and observe the "Delete" button.

[Expected result]:
- The button should keep the same aesthetic as the other action buttons from the site (Copy and Download buttons) and it would benefit from having a red background.

[Actual results]:
- The button has a clear background and black text.

[Notes]:
- Here is a screenshot with the issue:
![image](https://user-images.githubusercontent.com/18304511/28314661-2780e798-6bc4-11e7-92d8-5290ac0fb445.png)

**Comment by sevaan** [comment]
I don't think a red button is the right choice here. We don't use a solid red button for anything else in Firefox as it implies errors/warnings as oppose to a delete action.

Also, it's so bright it feels like it draws attention away from the most important element on the page: the copy URL button.

Maybe it is better if it is just red text.

**Comment by ehuggett** [comment]
If red is used at all, should the intensity of the red increase in #delete-file:hover ? I know buttons generally darken when you hover over them, but if red is being used to indicate caution i was wondering if it would make sense to disregard this convention in favour of reinforcing this message (currently decreases the intensity from `#d00000` to `#b80603` in :hover)

> I don't think a red button is the right choice here. We don't use a solid red button for anything else in Firefox as it implies errors/warnings as oppose to a delete action.
>Also, it's so bright it feels like it draws attention away from the most important element on the page: the copy URL button.

Deleting a file is not normally unusual but I think deleting a newly uploaded file deserves one, Would it "fit in" (and address the user attention concern) to leave the button white but change it to red when the mouse cursor hovers over it (leave #delete-file untouched but set a vibrant red in #delete-file:hover). 

Being a button is perhaps not ideal as it sits on the "mouse cursor path" between the "copy link" and "send another file" options if it doesn't request confirmation (there does not appear to be an issue for this but I'm not the first to comment on it, and it seems relevant here).

Any thoughts? (e.g. make it a link, make it smaller, make it red, move it, a dialogue like the upload page, ask them to click again to confirm, have the button "unlock" when you hover for half a second etc)
