### ISSUE TITLE
Delimit the "Delete Nevermind" pop-up so that the options are clearly separate

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#237]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Several files were already uploaded.

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Click the "X" button for one of the previously uploaded file.
3. Observe the pop-up.

[Expected result]:
- The two options are clearly separate from one another.

[Actual results]:
- The two options can be mistakenly interpreted as one.

[Notes]:
- It was brought to my attention that the "Delete" and "Nevermind" options can be interpreted as a single action in stead of two. We could either remove the whole pop-up and delete when the user clicks on the "x" button. Or we could just make it more obvious that they are two separate actions.
- Here is a screen recording with the issue:
![deletenevermind pop up](https://user-images.githubusercontent.com/18304511/28367120-416d1468-6c98-11e7-8019-808d93005d2f.png)

**Comment by pdehaan** [comment]
FWIW, I think [#269](https://github.com/mozilla/send/pull/269/files#diff-cb458696a7cf1f8badab576ac8ccc6afR332) splits the "Delete" and "Nevermind" links onto separate rows.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page. The options are clearly separate, marking as verified.
