### ISSUE TITLE
A vertical scrollbar is wrongly displayed in the right part of the page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#244]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://send.dev.mozaws.net/" page.
2. Observe the right margin of the page.

[Expected result]:
- There is no scrollbar displayed.

[Actual results]:
- An unneeded vertical scrollbar is displayed.

[Notes]:
- This is not reproducible on Mac OS.
- If the browser is horizontally resized, two scrollbars are displayed. 
- Here is a screen shot with the issue:
![scrollbar](https://user-images.githubusercontent.com/19226534/28374064-5267e824-6cac-11e7-8888-a3c7aabd8c3c.png)

**Comment by ericawright** [comment]
let's leave open till it's on the server and we can confirm it on a windows/linux machine

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Windows and Linux and is no longer reproducible. The scrollbar is no longer displayed. Marking as verified.
