### ISSUE TITLE
Dragging two or more files onto the page appears to work but only uploads one file

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#248]
There's no indication that this would occur.

## STR
* drag two files into send
* get download link
* download files

## Expected
* All files are downloaded

## Actual
* Only one file is downloaded

Fix: 
* the ultimate fix here is to handle multiple downloads, the immediate fix would be to not let people drag multiple files in and warn them about it.

**Comment by pdehaan** [comment]
Ref: #75
