### ISSUE TITLE
Add styling of "Delete file" button after uploading a file?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#270]
<img width="580" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28443979-9123a4e6-6d6e-11e7-8ad8-8c59bef47ef1.png">

**Figure 1:** Note how "Cancel upload" has some nice red text to make it stand out against the rest of the body text.

---

<img width="825" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28444023-e2bc3b92-6d6e-11e7-9477-b2d5c6086689.png">

**Figure 2:** Note that the "Delete file" button doesn't have any red background or any distinguishing features. Which is a bit scary since I don't believe that we have any confirmation challenge when clicking the button (ref #217).

**Comment by SoftVision-CiprianMuresan** [comment]
See also #220.

**Comment by pdehaan** [comment]
Duplicate of #220
