### ISSUE TITLE
[Windows] Trying to upload a folder does not trigger the "invalid action" dialog

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#274]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Drop a folder on the Drop area and observe the behavior.

[Expected result]:
- The "Uploading multiple files or a folder is currently not supported." dialog is displayed.

[Actual results]:
- The "Something went wrong" page is displayed.

[Notes]:
- The issue is not reproducible on Mac and Linux.
- Here is a screenshot with the issue:
![drag a folder](https://user-images.githubusercontent.com/18304511/28462014-f6274682-6e21-11e7-8e4d-5e489193ef89.gif)

**Comment by wresuolc** [comment]
Will probably be fixed by the same patch as #275

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page. Marking as verified.
