### ISSUE TITLE
"Something went wrong!" page is wrongly not shown after dropping text on the Upload page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#275]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Double click the "Private" word.
3. Drag and drop it on the Drop area.
4. Observe the behavior.

[Expected result]:
- The "Something went wrong" page is displayed.

[Actual results]:
- The drop area remains blocked in it's second form.

[Notes]:
- The issue is also reproducible if you drop links in the page.
- Here is a screenshot with the issue:
![upload text](https://user-images.githubusercontent.com/18304511/28461669-60d0fc46-6e20-11e7-986c-da38adbcae62.gif)

**Comment by pdehaan** [comment]
@SoftVision-CiprianMuresan Are there any errors in the console?

**Comment by pdehaan** [comment]
Ref: #271 and #272

**Comment by pdehaan** [comment]
Not sure what the correct action is here... But I was bored and this seemed to fix the issue in both Firefox and Chrome (basically by just ignoring an invalid text/link drop &emdash; taking me to a new page would just require one more click back to the upload page to retry).

```
    let file = '';
    if (event.type === 'drop') {
      const files =
        event.originalEvent.dataTransfer.files || event.target.files;
      file = files[0];
      if (!file) {
        return;
      }
      if (file.size === 0) {
        return;
      }
      if (files.length > 1) {
        $('.upload-window').removeClass('ondrag');
        return document.l10n
          .formatValue('uploadPageMultipleFilesAlert')
          .then(alert);
      }
    }

    if (file.size > MAXFILESIZE) {
      return document.l10n
        .formatValue('fileTooBig', { size: bytes(MAXFILESIZE) })
        .then(alert);
    }
```

**Comment by SoftVision-CiprianMuresan** [comment]
@pdehaan, the browser console shows:
![image](https://user-images.githubusercontent.com/18304511/28522919-b3217caa-7082-11e7-9cf8-bf0fbe0eb150.png)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page. Marking as verified.
