### ISSUE TITLE
Chrome crashes when trying to upload/download a 1 GB file

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#276]
[Notes]:
- When downloading a 1GB file the browser crashes right after the "Your download is complete" notification is displayed.
- I haven't tested Mac and Linux yet, but I will test and update this issue accordingly. However based on #170 it should work.

[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the Chrome browser and navigate to "https://send.dev.mozaws.net/" page.
2. Drag and drop a 1GB file in the Drop area.
3. Observe the behavior.

[Expected result]:
- Upload starts.

[Actual results]:
- Chrome crashes.

[Notes]:
- Here is a screenshot with the issue:
![chrome crash when uploading](https://user-images.githubusercontent.com/18304511/28467168-b1e881e6-6e37-11e7-84a5-1d12a3e5221a.gif)
![chrome crash when download is finished](https://user-images.githubusercontent.com/18304511/28467171-b42e3ac2-6e37-11e7-927d-54575f5c7a5b.gif)

**Comment by wresuolc** [comment]
This is kind of a known issue which is addressed a bit at https://github.com/mozilla/send/blob/master/docs/faq.md#how-big-of-a-file-can-i-transfer-with-firefox-send .  There isn't going to be anything we can do about it until we start chunking the files.  Closing this for now.  Thanks.
