### ISSUE TITLE
Filename not consistently displayed on Upload and Download pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#290]
Found in https://send.dev.mozaws.net/__version__ (85068e9):

```js
{
  commit: "85068e9",
  source: "https://github.com/mozilla/send/",
  version: "0.2.0"
}
```

---

### Steps to reproduce:
1. Go to https://send.dev.mozaws.net/ and upload a file.
1. Click the copy button/icon to copy the download URL.
1. Go to the download page and download the file.

### Actual results:
My 1.6kB file doesn't display the downloaded filename (which I believe it used to).
Without the filename, the brackets around the filesize seem out of place.

<img width="405" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28535527-8f932884-7059-11e7-8c23-c3f9af3fdf14.png">

### Expected results:
Display downloaded filename and filesize.

**Comment by pdehaan** [comment]
<img width="345" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28535671-12b9a81e-705a-11e7-9501-0fbc1f5e8caa.png">

versus

<img width="466" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28535704-2cd766d2-705a-11e7-9105-62cccc01ac88.png">

**Comment by pdehaan** [comment]
Actually, I guess the filename is in the header (along w/ total filesize) during download.

**Comment by abhinadduri** [comment]
@pdehaan Can we close this?

**Comment by pdehaan** [comment]
@abhinadduri: If @johngruen will sign off on the UI, I'm happy to close this.
