### ISSUE TITLE
set SENTRY_CLIENT environment variable

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#301]
`SENTRY_CLIENT` is the var that is used for the browser client (the DSN without the private key part I think)

example in https://github.com/mozilla/send/blob/master/docs/docker.md

@relud can we set this var to the fileshare-[dev|stage|prod] sentry projects? Also, I don't know `SENTRY_DSN` (for the server side) is already set or not.

**Comment by relud** [comment]
`SENTRY_DSN` should already be set. I'll add this rn.

**Comment by relud** [comment]
wait, I thought I saw that `SENTRY_DSN` was set yesterday, but it's not. I'll them both.

**Comment by relud** [comment]
fixed, deployed in dev, currently deploying in stage. can promote to prod on request.
