### ISSUE TITLE
Some UI issues need to fix

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/send#303]
We checked the current release from [here](https://send.dev.mozaws.net/), and we found several UI issues. Mark has fixed some issues, but we might still need some help for the rest. (I list the fixed ones as record.)

### 1. Feedback button should be collapsed as default <**FIXED**>
![group](https://user-images.githubusercontent.com/18019946/28568242-ab19bd2a-7167-11e7-9471-00f27574070a.png)

### 2. Favicon should be transparent background <**FIXED**>
![group 2](https://user-images.githubusercontent.com/18019946/28568252-b6099a48-7167-11e7-904e-9e68207ceb66.png)

### 3. Need wider gap and use regular font in the text input <**FIXED**>
![group 3](https://user-images.githubusercontent.com/18019946/28568255-c000887c-7167-11e7-9d0d-1baf9622ff61.png)

### 4. Copy and Delete should be collapsed for responsive
![group 4](https://user-images.githubusercontent.com/18019946/28568262-c82ae2fe-7167-11e7-818c-df3d0592de84.png)

### 5. Incorrect layout of footer for responsive <**FIXED**>
![group 6](https://user-images.githubusercontent.com/18019946/28568271-cf934b26-7167-11e7-988c-a31bfaf3b5a7.png)

### 6. The icons are not the same size
![group 8](https://user-images.githubusercontent.com/18019946/28568303-e89fb672-7167-11e7-814e-a55ecd7a1cf5.png)

### 7. A line between chrome and “Send_bg.svg” <**FIXED**>
![group 11](https://user-images.githubusercontent.com/18019946/28568326-027bc3b0-7168-11e7-9133-a39a554221da.png)

### 8. The background color for Download Firefox
![group 10](https://user-images.githubusercontent.com/18019946/28568332-06aede5e-7168-11e7-8fe5-bde86626dd8f.png)

**Comment by johngruen** [comment]
@youwenliang  @ChenMorpheus are those marked fixed handled in #302?

**Comment by youwenliang** [comment]
@johngruen Yes!

**Comment by youwenliang** [comment]
Number 5 is also fixed by the way.

**Comment by dannycoates** [comment]
closing in favor of #539
