### ISSUE TITLE
The text inside the Upload/Download progress bars is wrongly selected when clicking to the left or right of them

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#308]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net/.
2. While uploading a file, click the area to the left or right of the upload progress bar.
3. Observe the behavior.

[Expected result]:
- Nothing happens.

[Actual results]:
- The percentage inside the upload progress bar is selected.

[Notes]:
- The issue is also reproducible when downloading a file.
- Here is a screen recording with the issue:
![text should not be selected](https://user-images.githubusercontent.com/18304511/28580421-20a4bac2-7168-11e7-88fb-93a43c660b59.gif)

**Comment by pdehaan** [comment]
I _think_ we can fix this with something like this (which is also a great reason to add autoprefixer, because that looks gross):

```css
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
-o-user-select: none;
user-select: none;
```

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page. Marking as verified.
