### ISSUE TITLE
Expired link still accessible

### ISSUE THREAD

**Issue by ericawright** [mozilla/send#309]
Possibly related to  #159

STR: 
- Copy a link that is about to expire
- Visit the page after the time it should have expired

EXPECTED: 
- the link should display the expired page

ACTUAL:
- the link is still valid
- the file can still be downloaded!

Does the file actually get deleted from the server at 24 hours?

**Comment by wresuolc** [comment]
please double check!

**Comment by ericawright** [comment]
currently this is what we see from an expired link
![screen shot 2017-07-25 at 2 31 59 pm](https://user-images.githubusercontent.com/10803178/28587740-310ff6fa-7146-11e7-88c0-c3548f46af69.png)
and when clicking on that expired link (after #310), we see a flash, then the same thing
