### ISSUE TITLE
Translations mess up CSS

### ISSUE THREAD

**Issue by abhinadduri** [mozilla/send#315]
Some of the translated strings mess up our CSS (see attached)

<img width="1680" alt="screen shot 2017-07-25 at 3 57 49 pm" src="https://user-images.githubusercontent.com/4949139/28597325-21ed0102-7152-11e7-8414-968db43c2e7f.png">

**Comment by abhinadduri** [comment]
The upload button is also off.

<img width="1680" alt="screen shot 2017-07-25 at 4 08 10 pm" src="https://user-images.githubusercontent.com/4949139/28597577-7e0797da-7153-11e7-93db-be5dbb26735f.png">

**Comment by flodolo** [comment]
Poor title: layout is not designed for longer translation. Languages are not at fault here ;-)

**Comment by ericawright** [comment]
@abhinadduri it looks like there is a button missing. What page is this?

**Comment by flodolo** [comment]
@abhinadduri 
I think you hit a bug on our side (Pontoon), managing strings with both value and title attribute. 

We fixed the FTL files in the meantime for all locales
https://github.com/mozilla/send/commit/dccf3329caae6f345498f7f723eb2fb633c03c17

**Comment by dnarcese** [comment]
This doesn't seem to be reproducible anymore
