### ISSUE TITLE
File information table is not shown in new tabs of the same Private session

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#321]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net/ in a private window.
2. Upload a file and open a new tab.
3. Navigate to https://send.dev.mozaws.net/ and observe the bottom part of the page.

[Expected result]:
- The previously uploaded file is displayed.

[Actual results]:
- The File information table is not displayed.

[Notes]:
- Here is a screen recording with the issue:
![private session consistency](https://user-images.githubusercontent.com/18304511/28627313-17e6b5b2-722a-11e7-81f0-147e94953a51.gif)

**Comment by ericawright** [comment]
For a little more detail. If other private tabs are already open then they will get the record of the files, but if you open a fresh tab after uploading then it won't have the record.

**Comment by dannycoates** [comment]
private browsing disables localstorage. wontfix
