### ISSUE TITLE
[style] use async/await

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#325]
It might be fun to use `async/await` syntax on the server.

Here's a sample snippet:

```js
app.get('/download/:id', async (req, res) => {
  const id = req.params.id;
  if (!validateID(id)) {
    return res.sendStatus(404);
  }
  try {
    const filename = await storage.filename(id);
    const contentLength = await storage.length(id);
    const timeToExpiry = await storage.ttl(id);
    res.render('download', {
      filename: decodeURIComponent(filename),
      filesize: bytes(contentLength),
      sizeInBytes: contentLength,
      timeToExpiry: timeToExpiry
    });
  } catch (e) {
    res.status(404).render('notfound');
  }
});
```

**Comment by pdehaan** [comment]
💯 

Related, doing something like #64 to convert Redis calls to a promise style instead of callback style, would make it play much better w/ `async/await`.
As would switching to the already promise-based `fetch()` API, circa #32 (although that's more of a front end optimization).

**Comment by weihanglo** [comment]
I changed all promises into async functions in express at weihanglo/send@bbe111a.

However, in **storage.js**, methods on Redis client seem cannot be promisified by NodeJS 8 `util.promisify`. I thought this issue may be related to 424eb2c. Any idea?

**Comment by dannycoates** [comment]
@weihanglo thanks! Feel free to submit a PR and we can discuss the details there.

**Comment by pdehaan** [comment]
Awesome work, @weihanglo!

There are a few more Promise notes buried in #64 (most notably the https://github.com/mozilla/send/issues/64#issuecomment-310733702 which has a pointer to the official Redis+Promise documentation on using [**bluebird**](http://npm.im/bluebird) to promisify the entire RedisClient using something like:

```js
bluebird.promisifyAll(redis.RedisClient.prototype);
```

I only briefly played with their sample code, but I'm sure we could figure it out if you need a second pair of eyes.

**Comment by gautamkrishnar** [comment]
Can this issue be closed? I think it's fixed now...

**Comment by pdehaan** [comment]
@gautamkrishnar I think we're still keeping this open until we try and promisify the server/storage.js bits.
