### ISSUE TITLE
"Delete file" string is not displayed on the "Delete" button on French locale 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#330]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The French [fr] language was added on top of the list from Firefox Options>Content section.

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.firefox.com/" page.
2. Upload a file.
3. Observe the "Delete" button from the "Copy Link" page.

[Expected result]:
- The "Delete file" string is correctly displayed.

[Actual results]:
- "Delete file" string is not displayed in the "Delete" button.

[Notes]:
- This issue is also reproducible on dev website.
- Here is a screen shot with the issue:
![delete](https://user-images.githubusercontent.com/19226534/28673146-76cf0834-72ea-11e7-8421-bea0d352e0d5.png)

**Comment by dnarcese** [comment]
This is happening because the value fields for 'Delete File' and 'Send another file' are missing in Pontoon. 
I am not sure of the official way to add a translation, @TheoChevalier would you be able to correct this?

![screen shot 2017-07-27 at 10 07 24 am](https://user-images.githubusercontent.com/11432165/28674550-b6e2f98a-72b3-11e7-867f-ff2ebcce197a.png)
![screen shot 2017-07-27 at 10 07 14 am](https://user-images.githubusercontent.com/11432165/28674607-e16a14cc-72b3-11e7-919e-667fc1f30bb1.png)
(this will also fix #331)

**Comment by TheoChevalier** [comment]
@dnarcese Thanks for the ping! Strings added, will be pushed in ~10 minutes.
I noticed the value filed after the first translation, then missed those two when looking for places where I missed the value field :/
@flodolo Is it on our plans to warn for missing strings in those cases?

**Comment by flodolo** [comment]
I think that's a more a question for @mathjazz and the work they're doing on errors

**Comment by flodolo** [comment]
I'm going through a few locales and see how many we have with this kind of problem.

**Comment by mathjazz** [comment]
If the string ends up being valid FTL, I don't think we'll catch it with compare-locales (which we'll use for detecting errors). Is that a valid assumption, @Pike?

That said, I believe we should have at least warnings. If there are cases where we can be sure that the Value cannot be omitted, we should prevent translations without Value from being submitted.

**Comment by TheoChevalier** [comment]
FTR, it’s now there for French https://github.com/mozilla/send/commit/8214409ac5258935549992a0e414607dc3ab2fb3

**Comment by Pike** [comment]
Mismatches in message signatures are errors on missing value or attribute, and warnings on obsolete ones.

We should deploy the version that compare-locales returns as merge content, in this case, it would have removed the french message, and both the value and attribute would fall back to English.

**Comment by flodolo** [comment]
Fixed German directly, since it's not possible to fix it via Pontoon (maybe uploading the FTL there? Didn't want to mess with attribution)
https://github.com/mozilla/send/commit/462002d84bb4a908ef935ed8bb3a42cc976b45cb

**Comment by dnarcese** [comment]
Fixed in 8214409

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev page. Marking as verified.
