### ISSUE TITLE
"Send another file" link button is missing from all pages on French locale 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#331]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The French [fr] language was added on top of the list from Firefox Options>Content section.

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.firefox.com/" page.
2. Upload a file.
3. Observe the "Copy Link" page.

[Expected result]:
- The "Send another file" link button is displayed.

[Actual results]:
- The "Send another file" link button is missing from the page.

[Notes]:
- This issue is also reproducible on dev website.
- Here is a screen shot with the issue:
![send another file](https://user-images.githubusercontent.com/19226534/28673179-900cb760-72ea-11e7-8f6a-384c765c4e87.png)

**Comment by dnarcese** [comment]
Fixed in 8214409

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev page. Marking as verified.
