### ISSUE TITLE
Content Security Policy: Couldn’t process unknown directive ‘report-to’

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#342]
Spotted on dev and prod:

Firefox: `Content Security Policy: Couldn’t process unknown directive ‘report-to’`
Chrome: `Unrecognized Content-Security-Policy directive 'report-to'`

<img width="1280" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28686189-444c3894-72bf-11e7-88e6-2f89e6c8e3e0.png">

**Comment by dannycoates** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri

**Comment by pdehaan** [comment]
@dannycoates Cool, thanks! Feel free to close the issue if it isn't really actionable.
