### ISSUE TITLE
Use CODEOWNERS file to automatically request reviewers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#343]
In https://github.com/mozilla/send/pull/339/files#r129929227 @flodolo says:

> use the testpilot solution to ping automatically ;-)
> https://github.com/mozilla/testpilot/blob/master/CODEOWNERS

I didn't know that was a thing, but it's super cool.

> Use a CODEOWNERS file to define individuals or teams that are responsible for code in a repository.
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. When someone with admin permissions has enabled required reviews, they can optionally require approval from a code owner.
>
> &mdash; via https://help.github.com/articles/about-codeowners/

I'm guessing it's as simple as creating a docs/CODEOWNERS with the following sauce:

```
# flod as main contact for string changes
public/locales/en-US/*.ftl @flodolo
```

**Comment by ericawright** [comment]
very cool!

**Comment by flodolo** [comment]
It's a quite recent change (3 weeks)
https://github.com/blog/2392-introducing-code-owners
