### ISSUE TITLE
Download view improvement

### ISSUE THREAD

**Issue by youwenliang** [mozilla/send#347]
When a receiver download a file with the link and the download is completed, the download manager in your browser will pop up. If a user accidentally clicks "cancel" instead of "ok", there's no other way to re-download the file since the link is already expired.

![image](https://user-images.githubusercontent.com/8919308/28709032-193e18e6-73b1-11e7-86c9-09f48186fffb.png)

And if a user clicks "ok", the web page should have a visual feedback about it instead of freezing at the 100% view.

![image](https://user-images.githubusercontent.com/8919308/28709080-434e2810-73b1-11e7-9e61-fb1da680605f.png)

**Comment by dannycoates** [comment]
obsolete
