### ISSUE TITLE
l10n for .progress-text

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/send#349]
The variables order and "of" text.

**Comment by wresuolc** [comment]
Let's localize this! https://github.com/mozilla/send/blob/master/frontend/src/upload.js#L205

Would a / work fine instead of "of" ?

/cc @flodolo to tell us the best way to do this. :)

**Comment by yfdyh000** [comment]
https://github.com/mozilla/send/blob/109617d8172f998e470af7073b962be7c95d4149/frontend/src/download.js#L83 & https://github.com/mozilla/send/blob/07b9545b03ca5a02cf0a09250cb5a8a24c64254a/frontend/src/upload.js#L205.

Yes, "/" is fine.

**Comment by flodolo** [comment]
It should be fully localized to allow reordering, something like

```
// This message is displayed when uploading a file, e.g. "1,3 MB of 10 MB".
uploadStatusMessage = { $size_loaded } of { $size_totale }
```
