### ISSUE TITLE
add recipient to unsupported ping?

### ISSUE THREAD

**Issue by wresuolc** [mozilla/send#350]
https://github.com/mozilla/send/blob/master/docs/metrics.md#unsupported says the category (`ec`) is `sender` but shouldn't it also be `recipient`?

/cc @chuckharmston @ericawright

**Comment by chuckharmston** [comment]
Yeah, I suppose that makes sense. I'll PR a fix.

**Comment by chuckharmston** [comment]
Opening this back up for implementation.

**Comment by dannycoates** [comment]
already implemented

https://github.com/mozilla/send/blob/master/frontend/src/common.js#L14-L18
