### ISSUE TITLE
Transpile front end code into ES5?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#359]
I was playing around trying to replace browserify with webpack+babel, and failing quite spectacurly.
I think the latest error I was getting was re: `class` keyword in an imported ["testpilot-ga" module](https://github.com/mozilla/testpilot-ga/blob/master/.babelrc).

Looks like testpilot-ga publishes a babel version itself (yay) but targets a baseline env of "Firefox 54", whereas we're targeting older browsers. Not sure if that means we'd have to re-babel that dependency and set our `env.targets.browsers` to something like "> 2%,  ie 8, safari > 9".

**Comment by dannycoates** [comment]
done
