### ISSUE TITLE
add <meta> tags to support twitter cards

### ISSUE THREAD

**Issue by wanderview** [mozilla/send#370]
I tweeted about send.firefox.com today:

https://twitter.com/wanderview/status/892391157086527489

And I noticed it doesn't generate any kind of twitter card.  It might be nice to provide some kind of logo or something.  (Obviously a preview of the payload would probably be bad...)

**Comment by SoftVision-PaulOiegas** [comment]
In the mean time you can tweet the Test Pilot experiment link. That one generates one.

**Comment by pdehaan** [comment]
Duplicate of #153; _"Add OpenGraph and Twitter Card metadata to pages"_
