### ISSUE TITLE
Improve "Your browser is not supported" message 

### ISSUE THREAD

**Issue by miketaylr** [mozilla/send#377]
Using current Safari

```
Your browser is not supported.
Unfortunately this browser does not support the web technology that powers Firefox Send. You’ll need to try another browser. We recommend Firefox!
```

I assume we're doing some kind of feature detection here -- and that this isn't a bug? -- and without wanting to create a ton of work, would it be possible to show a message that is more descriptive?

c.f., https://twitter.com/jiaaro/status/892474085262991360

**Comment by miketaylr** [comment]
(or maybe this is a WONTFIX, i dunno, i don't run this show)

**Comment by pdehaan** [comment]
@miketaylr I think this is the relevant bit from the FAQ:
https://github.com/mozilla/send/blob/master/docs/faq.md#why-is-my-browser-not-supported

But yeah, a mention of GCM and a link to the FAQ would be :+1: on that /unsupported page.

**Comment by miketaylr** [comment]
A link to the FAQ for sure! Thanks!

**Comment by jdriscoll** [comment]
Included in Safari 11: https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html

**Comment by pdehaan** [comment]
I can confirm that it works in Safari 11 (Technology Preview) on macOS Sierra.

<img width="1440" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28854424-f3528b74-76eb-11e7-9520-3c7dc76097b9.png">

**Figure 1:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.32 (KHTML, like Gecko) Version/11.0 Safari/604.1.32

---

But I get the "Your browser is not supported." message on Safari 10 (current "Release" channel).

<img width="1440" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28854471-1f7e04e4-76ec-11e7-95ab-6be2dc40e44d.png">

**Figure 2:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by pdehaan** [comment]
I know I'm not a average user, but it may also be nice to show the user's User Agent string below that "Your browser is not supported" heading, although I guess I'm also not convinced that arming a user with that obscure string would solve any immediate issues.

**Comment by wresuolc** [comment]
Adding a link to the FAQ is a good idea

**Comment by OllyHodgson** [comment]
As someone [commented on Reddit](https://www.reddit.com/r/firefox/comments/6r5l3z/firefox_doesnt_support_send_please_try_firefox/), the message currently tells Firefox for iOS users to try using Firefox (due to the aforementioned limitations with Safari / webkit). Perhaps it could be worded a bit better in that scenario?
