### ISSUE TITLE
Send Firefox on Sidebar

### ISSUE THREAD

**Issue by ariestiyansyah** [mozilla/send#385]
This is just my experiment to allow user to use send firefox on sidebar by using `sidebar_action` key in manifest.json.

You can try it here https://github.com/ariestiyansyah/send-firefox-extension

![screenshot](https://user-images.githubusercontent.com/2667489/28875417-b0970010-77bf-11e7-884a-128a51443454.gif)

**Comment by pdehaan** [comment]
@ariestiyansyah This is a really cool idea! Great job!

**Comment by ariestiyansyah** [comment]
@pdehaan what is the status of `needs:product` flag of this issue? I think we should publish send firefox addons to quantum since it's really helpful.

If yes, I will do PR or you guys create new repo in mozilla github so this addons can be published on behalf of mozilla. let me know your feedback

**Comment by ehuggett** [comment]
From https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/sidebar_action
> Unlike a normal web page, JavaScript running in the panel can access all the WebExtension APIs (subject, of course, to the extension having the appropriate permissions).

The extension currently has the "tab" and "storage" permissions in addition to whatever is accessible by default, does this mean these permissions are also being granted to send.firefox.com? (as the extension loads this url directly into the sidebar)

**Comment by ariestiyansyah** [comment]
@ehuggett Indeed, I will remove that attribute.

**Comment by dannycoates** [comment]
since we have no current plans for an extension im closing this
