### ISSUE TITLE
Lint and auto-format code on a git precommit hook?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#405]
Ref: https://github.com/mozilla/send/pull/404#discussion_r131059177

I like how [**testpilot-ga**](https://github.com/mozilla/testpilot-ga/blob/c4119b6a98089c9f0c53b03feb9307bd3f1220a7/package.json#L25-L30) does it by using [**husky**](http://npm.im/husky) and [**lint-staged**](http://npm.im/lint-staged).

https://medium.com/@netczuk/your-last-eslint-config-9e35bace2f99

---

**Pros:**
- This would make sure that ESLint and prettier get run locally before each commit/push.
- Would make less of a burden on Circle-CI since I wouldn't have to wait for a build to fail just to see that I forgot a semi-colon because peter forgets to run `npm run lint` locally.

**Cons:**
- If we run prettier on a hook, unrelated code could get shuffled slightly. Not sure if `lint-staged` and our current globs would lint _only_ those staged files, or if Prettier would touch everything. Worst case is we try it and see, and can easily revert if we don't like it.

**Comment by dannycoates** [comment]
done at some point
