### ISSUE TITLE
Cannot download file

### ISSUE THREAD

**Issue by vladikoff** [mozilla/send#410]
Uploaded a screenshot from one machine. Tried to download on the other, but no luck!

![cannot-download](https://user-images.githubusercontent.com/128755/28926084-c2b09c64-7834-11e7-820b-9607542f3c19.gif)

**Comment by vladikoff** [comment]
Tried again with the same PNG screenshot file and got: 

![image](https://user-images.githubusercontent.com/128755/28926274-4e1ff8f8-7835-11e7-870b-819f74664973.png)

**Comment by dannycoates** [comment]
@vladikoff can you post that png somewhere or is it private?

**Comment by dannycoates** [comment]
This looks like the behavior you get when the link is truncated (a broken key). I just pushed a partial fix for that in #412

**Comment by vladikoff** [comment]
Thanks so much Danny!
