### ISSUE TITLE
"Select a file on your computer" looks weird on mobile

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#421]
Perhaps "Select a file on this device"?

Ref: [/public/locales/en-US/send.ftl:10-11](https://github.com/mozilla/send/blob/4ac07800c409f3c73e22b73b97ff5255d029e068/public/locales/en-US/send.ftl#L10-L11)

**Comment by gvanwaelvelde** [comment]
How about simply "Select a file to upload"?
That way we bypass the whole computer vs. device issue.
