### ISSUE TITLE
Please Support QRCode.

### ISSUE THREAD

**Issue by ousui** [mozilla/send#423]
I want download the send file by my phone.
But the url is too long to input.
Can Support QRCode?

**Comment by abdulhannanali** [comment]
@pdehaan This feature request seems good and useful. Any thoughts? I want to start working on this, If this feature is something mozilla people deem useful. I think it should be a hit with Chinese users.

**Comment by pdehaan** [comment]
@abdulhannanali It definitely sounds interesting, and I know we've considered it for other projects (https://github.com/mozilla/fxa-features/issues/47). I'd probably hold off on implementation until we hear back from product management on if this is something we'd like to try in A/B testing or as a new feature.

**Comment by pdehaan** [comment]
@vladikoff shane-tomlinson Did we ever implement QR code support in FxA in any way (intern project, etc)? I thought Sai was working on it at some point, but maybe I'm horribly mis-remembering.

**Comment by ehuggett** [comment]
It seems it was at least considered for pairing devices? https://wiki.mozilla.org/Services/Sync1_5/FxASyncPairing#Pairing_mechanisms

Firefox mobile appears to be able to read QR codes https://support.mozilla.org/en-US/kb/scan-qr-codes-firefox-android https://support.mozilla.org/en-US/kb/scan-qr-codes-firefox-ios , although any QR code reader would of course be suitable on mobile long long as it can pass the url to a browser.

**Comment by gvanwaelvelde** [comment]
Support for QR code sounds interesting, but since a file can be downloaded only once, I'm not sure it would be very useful?

**Comment by ehuggett** [comment]
You would have to decide you wanted the file on your mobile while the download page is displayed on another device, before you click download (you would click QR code instead).

I can't see any obvious way of sending a QR code without re-creating the "how do I send files securely" problem, but the receiver of a link has all the information required to create them.

**Comment by johngruen** [comment]
@ousui could you give a concrete example of when you would want a QR code? Is this sending to a friend or sending a file to yourself?

**Comment by ousui** [comment]
@johngruen 
In China, many people use PC with vpn/proxy to download files like apk, videos. 
When I have not  usb-cable, I'll download these files with send.firefox.com. But the url is too long to input.

**Comment by ehuggett** [comment]
I was about to suggest a firefox addon, but the first 3 i have looked at from the addons search results (including "JavaScript QR Code, Make QR Codes in pure JavaScript" and one marked "featured") rely on or expose the data to an external service (some of them over plain http!) and don't necessarily make this obvious to the user.

Might be worth considering? (Many QR addons don't seem to give any consideration the use case of private/sensitive data)

**Comment by ekanna** [comment]
Please show link as QRCode. We can altogether avoid WhatsApp or Email for sharing link to self.

**Comment by oliver-dvorski** [comment]
I made this [little guy](https://makeazip.com/) with a QR code render on the download page as the first feature of my service. To answer the question from August 2017 - this is awesome for sending files to myself. Since I can just extract them from any iffy machine and retrieve them later through the public link that I can save anywhere I'd like once I scan the code after the upload

**Comment by VADemon** [comment]
Real use case: share a document from PC to smartphone without self-emailing it (sic) or using a USB cable.
I don't care in the slightest whether or not Fx has native QR code scanner support, I've an app installed just for that.

**Comment by oliver-dvorski** [comment]
I just noticed that my stock camera app reads QR codes (s8+). So that makes
things even more convenient...

VADemon <notifications@github.com> schrieb am Mi., 17. Juli 2019, 19:52:
