### ISSUE TITLE
The l20n.js is not working with template /locales/{locale}/send.ftl . BUG

### ISSUE THREAD

**Issue by uname-yang** [mozilla/send#425]
When i try to change the meta data `defaultLanguage` to other language like below:
```
<meta name="defaultLanguage" content="zh-CN">
```
The language don't change to chinese as i want.

**Comment by wresuolc** [comment]
Are you changing the `<meta>` tag on the page in dev tools or changing the language in the browser?  Changing the value directly on the page wouldn't retrigger the JS, but I also wouldn't consider that a bug.

**Comment by uname-yang** [comment]
I change it in source code. Sometimes it works, sometimes is doesn't.

**Comment by dannycoates** [comment]
I'm not able to reproduce this. The displayed language depends on the "defaultLanguage", "availableLanguages" and your browser's language settings in `about:preferences`

If any of your browser languages is in "availableLanguages" it will use the first preference that matches. Only if none are available will it use the "defaultLanguage"

Here's a screenshot of my language preferences:
<img width="525" alt="screen shot 2017-08-08 at 12 23 26 pm" src="https://user-images.githubusercontent.com/87619/29090665-1c2d8ffa-7c35-11e7-9641-73fe9b6b248b.png">
