### ISSUE TITLE
If the "Download" button is clicked multiple times, the file is wrongly downloaded for each click

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#429]
[Notes]:
- The pregressbar and the percentage are also displayed for each download and are overlapped.

[Affected versions]:
- Firefox 54.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a file and copy the link.
3. Navigate to the file download page.
4. Multiple click on the "Download" button.

[Expected result]:
- You are redirected to the "Downloading" page and the file is downloaded once.

[Actual results]:
- You are redirected to the "Downloading" page, but the file is downloaded for each click.

[Additional Notes]:
- Probably this issue can be easily encountered when you have a bad connection.  
- The issue is only reproducible on dev and stage servers.
- Here is a screen recording with the issue:
![multiple downloads](https://user-images.githubusercontent.com/19226534/28974279-8c059a1a-793e-11e7-9334-674a88f2c337.gif)

**Comment by pdehaan** [comment]
I think the easiest solution is to set `disabled` attribute in the HTML after clicking the Download button.

**Comment by vhanla** [comment]
What if my connection drops before completing download. Does it count as download completed and file is removed?

**Comment by dannycoates** [comment]
@vhanla a partial download does not count as a download
