### ISSUE TITLE
Upload/Download does not work on Edge

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#430]
[Notes]:
- The page is rendered correctly, but the functionality is broken.

[Affected versions]:
- Microsoft Edge 40.15063.0.0

[Affected Platforms]:
- Windows

[Steps to reproduce]:
1. Start the browser and navigate to "https://send.dev.mozaws.net/" page.
2. Drag and Drop a file in the Drop area.
3. Observe the behavior.

[Expected result]:
- Upload starts.

[Actual results]:
- This issue is also reproducible on production.
- Here is a screenshot with the issue:
![img_04082017_183322_0](https://user-images.githubusercontent.com/19226534/28975748-de54230e-7943-11e7-94ab-14d369e889ce.png)

**Comment by johngruen** [comment]
Easiest thing would be to switch old edge to the "you need a new browser" page

**Comment by dannycoates** [comment]
should be fixed by #466

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible. Marking as verified.
