### ISSUE TITLE
Improve installation instructions in README

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#434]
A few people are struggling to get this installed locally (or self hosting, maybe). Me thinks we need a section in the README.md file about how to set up a server. I'm a bit lost on dependencies vs devDependencies since it seems like the package.json assumes a specific ops/docker flow...

Ref: #376 _"l20n.min.js and upload.js not loading on `npm run`"_.
Ref: #422 _"Move some devDependencies to normal dependencies"_.

**Comment by dannycoates** [comment]
fixed maybe
