### ISSUE TITLE
Link the filename to download page in download table?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#435]
As of #409, if you have `dom.allow_cut_copy=false` in your about:config, the copy functionality is disabled, and the Copy icon is disabled and 30% opacity. This pretty much prevents you from getting any download links or accessing your files.

We should maybe link the filename in the table to the download page, so even people whom have disallowed cut/copy in their about:config can still get at their uploaded files and send the links to their cohorts.

<img width="608" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28982041-1dc51ae2-7909-11e7-95e4-68f669eda212.png">

**Comment by bwinton** [comment]
For the record, I suggest we resolve this wontfix with a reason of "If you toggle a hidden pref that we intentionally kept hidden because it can break stuff and then stuff breaks, that's kinda on you".  😉

**Comment by dannycoates** [comment]
It'd be cool if the copy icon would pop up a dialog like the delete button with the url in it so you could manually copy it, but I'm also not opposed to a wontfix.

**Comment by wresuolc** [comment]
danny says this is done
