### ISSUE TITLE
Bad value “true” for attribute “hidden” on element “div”

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#441]
via #139 

```
line 75   col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
line 93   col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
line 106  col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
```

When fixing this, also make sure you search for Boolean instances of `.attr("hidden", ...)` in [/frontend/src/*.js](https://github.com/mozilla/send/tree/master/frontend/src) since we toggle the `hidden` attribute using jQuery as well. ❤️

**Comment by pdehaan** [comment]
After a bit of light Googling, I think we may want to switch from `.attr('hidden', ...)` and `.attr('disabled', ...)` to using jQuery's [`.prop()`](http://api.jquery.com/prop/) API, since that seems to play nicer w/ Boolean values.

> Examples include the `value` property of input elements, the `disabled` property of inputs and buttons, or the `checked` property of a checkbox. The `prop()` method should be used to set disabled and checked instead of the `.attr()` method.

**Comment by monkindey** [comment]
Hi, @pdehaan , Why not use `display: none` ?

**Comment by pdehaan** [comment]
@monkindey That could work. We are toggling the view states quite frequently in some places, so not sure if it makes a huge difference to toggle the HTML `hidden="hidden"` attribute versus toggling a CSS class that adjusts `display:none;` style.

**Comment by monkindey** [comment]
So what your consider is the performance between `hidden` and `display: none` ?
