### ISSUE TITLE
Links must have discernible text

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#442]
via #139 

```
line 112  col 7   Error  Links must have discernible text                       axe
line 120  col 7   Error  Links must have discernible text                       axe
line 121  col 7   Error  Links must have discernible text                       axe
```

Not sure what these alleged errors are, or how legit this is.
I have a suspicion that they are either icon links (Mozilla, GitHub, Twitter), or possibly links with localized strings injected at runtime using l20n.

**Comment by inondle** [comment]
I'd like to look into this.

**Comment by ericawright** [comment]
thanks @inondle

**Comment by inondle** [comment]
I'm unable to reproduce the "Links must have discernible text" error on https://send.dev.mozaws.net/ or https://fileshare.stage.mozaws.net. Is anyone else still getting those errors using the sonar tool?

**Comment by wresuolc** [comment]
Closing.  Please re-open if it's reproducible.
