### ISSUE TITLE
Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#443]
via #139 

```
line 49   col 7   Error  Elements must have sufficient color contrast           axe
```

I assumed this was the "Select a file on your computer" button...

<img width="264" alt="firefox_send" src="https://user-images.githubusercontent.com/557895/28985988-eeec04ae-7919-11e7-8706-27ec36529c3d.png">

... but [Contrast](https://usecontrast.com) is giving it a score of "AA+" (3.10), which should be sufficient.

> **AA Large** – The smallest acceptable amount of contrast for **_type sizes of 18px and larger_**. This is a score of at least `3.0`.
> &mdash; via https://usecontrast.com/guide

I'm guessing we are getting this warning because our `font-size` is 15px, not the 18 mentioned above.

<img width="419" alt="item-0_and_item-0_and_item-0_and_item-0" src="https://user-images.githubusercontent.com/557895/28986009-0ba53552-791a-11e7-840d-25585717c942.png">

**Comment by youwenliang** [comment]
For font-size 15px we should probably change the font weight from 200 to 500 to pass the contrast test. There's a same button for copy link by the way.

Here's what it looks like with font-weight: 500
![image](https://user-images.githubusercontent.com/8919308/29067968-6753bdd8-7c67-11e7-97d7-0a43e81e4a20.png)

![image](https://user-images.githubusercontent.com/8919308/29067988-7877111e-7c67-11e7-9d7e-6824a995759b.png)
