### ISSUE TITLE
Build a better 404 page for malformed URLs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#446]
I was trying to copy/paste a URL to myself and it went horribly wrong:
https://send.firefox.com/download/f392

Basically you're treated to a very terse 404 page that just says "Not Found" in plain text.
We should probably make some fancier, styled "404" experience with headers and footers.

<img width="811" alt="mozilla_firefox" src="https://user-images.githubusercontent.com/557895/28988906-11feb8d0-7927-11e7-96ff-0645072d07d4.png">

Ref: [/server/server.js:139](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L139)

Not sure if we can do something like this instead:

```js
res.status(404).render('notfound');
```

Or if we need a `res.status(404).render('404')` view which informs the user that the URL was just horribly malformed and not downloaded/deleted/expired.

**Comment by pdehaan** [comment]
In fact, here's a list of all the `res.sendStatus(404)` calls:

```
$ git grep -in "res.sendStatus(404);"
```

1. [server/server.js:124](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L124):    `res.sendStatus(404);` => `app.get('/exists/:id', ...)`
1. [server/server.js:132](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L132):    `res.sendStatus(404);` => `app.get('/exists/:id', ...)`
1. [server/server.js:139](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L139):    `res.sendStatus(404);` => `app.get('/download/:id', ...)`
1. [server/server.js:161](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L161):    `res.sendStatus(404);` => `app.get('/assets/download/:id', ...)`
1. [server/server.js:186](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L186):    `res.sendStatus(404);` => `app.get('/assets/download/:id',  ...)`
1. [server/server.js:194](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L194):    `res.sendStatus(404);` => `app.post('/delete/:id', ...)`
1. [server/server.js:201](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L201):    `res.sendStatus(404);` => `app.post('/delete/:id', ...)`
1. [server/server.js:211](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L201):    `res.sendStatus(404);` => `app.post('/delete/:id', ...)`
1. [server/server.js:232](https://github.com/mozilla/send/blob/86fbd2a4b5e5de0b2d17e2c1c1100d5918e487e4/server/server.js#L232):    `res.sendStatus(404);` => `app.post('/upload', ...)`

**Comment by varghesethomase** [comment]
Do we have a design here? In case I would like to take this up.

**Comment by sevaan** [comment]
WE could just use the "This link has expired or never existed" page.

**Comment by varghesethomase** [comment]
I guess all the `res.sendStatus(404;)` can be replaced with `res.status(404).render('notfound');` would fix this @pdehaan ? In that case i can send a PR.
