### ISSUE TITLE
Remove locales from production if they fall below 100% translation?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#458]
Apparently my script for linting production locales is "weak" at best, and only looked at l10n errors and not "missingEntity"...

Fixing my script locally and rerunning gives me the following output:

```sh
$ npm run lint-locales:prod

> firefox-send@1.0.4 lint-locales:prod /Users/pdehaan/dev/github/mozilla/something-awesome
> npm run lint-locales -- --production


> firefox-send@1.0.4 lint-locales /Users/pdehaan/dev/github/mozilla/something-awesome
> node scripts/lint-locales "--production"

compare-locales l10n.toml . az ca cs cy de dsb el en-US es-CL es-ES es-MX fr fy-NL hsb hu id it ja kab ms nb-NO nl nn-NO pt-BR pt-PT ru sk sl sr sv-SE tr uk zh-CN zh-TW --data=json

cs/send.ftl
- missing entity: notSupportedLink

cy/send.ftl
- missing entity: notSupportedLink

es-ES/send.ftl
- missing entity: notSupportedLink

kab/send.ftl
- missing entity: notSupportedLink

sv-SE/send.ftl
- missing entity: notSupportedLink
```

I don't know what our threshold for production locales is. Is 1-2 missing strings acceptable, or should we remove anything from [package.json's `availableLanguages` array](https://github.com/mozilla/send/blob/5ac013ca40c4625a70a7dc38d629a267f9a336a4/package.json#L51-L86) if it falls below 100%.

Ref: #414, which added the new `notSupportedLink` string.

**Comment by gvanwaelvelde** [comment]
While it may look unprofessional when a website isn't 100% translated, I'd suggest we still allow inperfect localizations. Good, but imperfect or incomplete localization is better than no localization.
Otherwise we may prevent many users from using the website in their own language. For some people the difference between a website being partially in their language or not at all makes a huge difference in whether they will be able to use the site.

**Comment by pdehaan** [comment]
Thanks @gvanwaelvelde. I'll see if I can build some sort of threshold into my `lint-locales` script to allow prod locales with 90%+ translations (which lets them be 1-3 strings below 100%) and I'll treat missing entries as warnings instead of failing errors.

**Comment by dannycoates** [comment]
I check the percentage before deleting. I've yet to remove one because our additions have been small, so none have ended up below 97%ish. So far it hasn't been trouble to manually check when I tag a release. @pdehaan improving the tool might be nice, but I'm not sweating it.
