### ISSUE TITLE
Integrate with the Share menu on mobile platforms

### ISSUE THREAD

**Issue by Caspy7** [mozilla/send#47]
When a "Share" menu on Android or iOS detects that the shareable content is a file, we should have an item appear in the share menu to send the file via the service.
(If "is this a file?" is not possible, consider a whitelist.)

Whatever the flow for uploading, we could conclude with the option to copy to clipboard (though consider autocopy) and another share option for the URL, allowing users to send the URL straight to someone via email/text/whatever.

**Comment by ehuggett** [comment]
Is there any way of going about this on Android (and iOS) without requiring a local app? (to register the Send service an an option for sharing files).

An app for iOS might be desirable anyway to address the usability issues with Safari on iOS. Namely the user being unable to save the file and being forced to preview or pass it to a app that can handle the files content, a little risky with only a single download limit (although you could argue that app already exists, its called Firefox!).

It would be possibly to "open" the app from the download webpages in mobile browsers and pass the URL to it? (but this would require a url-scheme such as firefox-send:// ?)

**Comment by dannycoates** [comment]
calling this done in the vnext android app
