### ISSUE TITLE
Add UI to message new features in product

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#475]
## User Stories

So that I can make sure to take full advantage of the send service, as a Send user, I would like to know when the service has changed or features have been added.

## Requirements

- [ ] It should tell users who visit the site about new features
- [ ] It should not materially hinder the users ability to upload files (UI should not block uploading)
- [ ] UX spec should include two versions of this UI for A/B testing

## Testing

We will implement two versions of this UI and test which leads to a higher conversion on the feature being described.

**Comment by youwenliang** [comment]
@johngruen Here are some quick proposals for displaying the new features.

Option A: a dialog with information about the new feature.
![file transfer - new feature dialog in-context](https://user-images.githubusercontent.com/8919308/29117150-c14b57f6-7d2f-11e7-802a-71f9394cfa3b.png)

Option B: a dismissable section with information about the new feature.
![file transfer - new feature section homepage](https://user-images.githubusercontent.com/8919308/29117148-be83b7a2-7d2f-11e7-8bbc-5182f8edbab3.png)

Any thoughts?

**Comment by sevaan** [comment]
How does Option A respond if the browser window shrinks?

**Comment by youwenliang** [comment]
@sevaan I was thinking something like this:
![mobileview](https://user-images.githubusercontent.com/8919308/29152320-6ccad3d4-7db9-11e7-9b7f-736d111b4752.png)

It'll block the main content temporarily though. We can A/B test these two options to get some feedback.

**Comment by sevaan** [comment]
That looks good to me.

One more thought: Maybe it should have a close X as well. That was the first thing I instinctively looked for. It could have the Got It button as well, or replace it.

**Comment by youwenliang** [comment]
Measurements here: https://mozilla.github.io/testpilot-assets/Send/Send_New_Features/

**Comment by wresuolc** [comment]
@youwenliang are we done with the UX here or is there more to do?

**Comment by youwenliang** [comment]
@wresuolc We are good to go!

**Comment by wresuolc** [comment]
Danny would like to do this after the passwords code lands.  Moving target to Hippo

**Comment by dannycoates** [comment]
old
