### ISSUE TITLE
On Microsoft Edge the filename has strange placeholder characters "FSI"/"PDI" 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#476]
[Affected versions]:
- Microsfot Edge

[Affected Platforms]:
- Windows 10

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.stage.mozaws.net" page.
2. Drag and Drop a file in the Drop area.
3. Observe the file name text.

[Expected result]:
- The file name is correctly displayed.

[Actual results]:
- The filename has strange placeholder characters FSI/PDI surrounding them

[Notes]:
- Here is a screen shot with the issue:
![edge](https://user-images.githubusercontent.com/19226534/29069873-6d4a6100-7c45-11e7-8b72-563f54cd6126.png)

**Comment by ehuggett** [comment]
Appears to be related to [Unicode bidirectional text support](https://en.wikipedia.org/wiki/Bi-directional_text#Unicode_bidi_support).

### explicit formatting
Explicit formatting characters, also referred to as "directional formatting characters", are special Unicode sequences that direct the unicode algorithm to modify its default behavior. These characters are subdivided into "marks", "embeddings", "isolates", and "overrides". Their effects continue until the occurrence of either a paragraph separator, or a "pop" character.

FSI | First Strong [Isolate](https://en.wikipedia.org/wiki/Bi-directional_text#isolates)
PDI | [Pop](https://en.wikipedia.org/wiki/Bi-directional_text#pops) Directional Isolate

Presumably the string is sent as Unicode but not interpreted as such?

**Comment by pdehaan** [comment]
I found this old l10n post about FSI and FDI markers and IE11 support: https://groups.google.com/forum/#!topic/mozilla.tools.l10n/BsoUcb19yOc

Wondering if this is potentially an issue w/ L20n or related to our recent font changes...

**Comment by johngruen** [comment]
"It's shitty" -@dcoates, August 2017

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page.

**Comment by johngruen** [comment]
@dannycoates was there an explicit fix here or did it just kind of go away?

**Comment by dannycoates** [comment]
It's a long story, but TLDR; With great effort and personal suffering... https://github.com/mozilla/send/blob/master/build/fluent_loader.js
