### ISSUE TITLE
On Windows, the stage website has a different font than production website

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#477]
[Notes]:
- On Mac OS and Linux, no differences can be observe between stage and production websites.

[Affected versions]:
- Firefox 54.0.1 and up

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.firefox.com/" page.
2. Observe the website font.
3. In a new tab navigate to "https://send.stage.mozaws.net" page.
4. Observe the website font.

[Expected result]:
- The websites has the same font.

[Actual results]:
- The stage website has a different and smaller font.

[Additional Notes]:
- Here is a screen recording with the issue:
![font](https://user-images.githubusercontent.com/19226534/29070312-781262e8-7c47-11e7-9993-b7f3e901397b.gif)

**Comment by pdehaan** [comment]
Possibly due to font changes in #427, _"Extended system font list"_.

**Comment by johngruen** [comment]
Closing in favor of #487
