### ISSUE TITLE
Add progress (%) to the title of upload page

### ISSUE THREAD

**Issue by pefimo** [mozilla/send#479]
# Overview
When a large file is being uploaded, it would be very nice to let the user change tab to another one and just peek at the title to check the progress.

# Explanation
Perhaps uploading a file is not a critically important activity and one doesn't want to observe the progress continuously. It is thus understandable that one might prefer to switch to another tab and do something else until the upload is finished.

Upload progress visible in tab's title would make it possible, esp. with scenarios similar to the following:
1. Upload a file to send.firefox.com.
2. Send a link via email to share it with a friend.

**Comment by johngruen** [comment]
Nice idea!

**Comment by johngruen** [comment]
this has a PR!
