### ISSUE TITLE
Add the ability to send multiple files

### ISSUE THREAD

**Issue by raymak** [mozilla/send#484]

**Comment by pdehaan** [comment]
Possible duplicate of #75, _"Drag & drop multiple files"_.

**Comment by ehuggett** [comment]
This issue could be interpreted explicitly as upload multiple files to share/send with a single link and the referenced issue as upload multiple files to receive multiple links(?)

For multi-file uploads an archive format similar to tar/zip etc  would avoid having to deal with multiple filenames (they would become part of the encrypted data) and avoids leaking to the server that its actually multiple files (once #69 prevents it from seeing the archive filename).

In theory we could allow the downloader to select individual files from the archive, or to download the entire thing (which I presume requires zip as the de-facto standard for compatibility?)

**Comment by johngruen** [comment]
Closing in favor of #75
