### ISSUE TITLE
Font is off on windows

### ISSUE THREAD

**Issue by youwenliang** [mozilla/send#487]
Some fonts are off when viewing in windows:
![fireshot screen capture 001 - firefox send - send_firefox_com](https://user-images.githubusercontent.com/8919308/29111172-d46470f2-7d1b-11e7-9adb-1c21f5c09b82.png)

Especially for the logo "Send", the font should stay the same, probably using an SVG image instead of using h1 title tag

**Comment by johngruen** [comment]
@youwenliang yeah we changed this to text for a11y. if you can add correct attributes, feel free to change back to an image.

**Comment by dannycoates** [comment]
old. fixed in vnext i guess
