### ISSUE TITLE
Unable to upload a zip-file

### ISSUE THREAD

**Issue by GMAF01** [mozilla/send#488]
I tried to upload a zip-file - and got an error message.

**Comment by pdehaan** [comment]
@GMAF01 I'm unable to reproduce on https://send.firefox.com on macOS using Firefox Beta or Chrome Release: https://send.firefox.com/download/440b6f15c0/#HeKoptkcKpy2S-uQeFdWNg

What browser/OS are you using, how big was your ZIP file, and are you seeing any errors in the Dev Tools console? What was the error message that you saw?

**Comment by GMAF01** [comment]
**@ pdehaan**,
Firefox 54.0.1 (32 bit)/Windows 7 Pro, Zip-file 199MB
Ein Fehler ist aufgetreten! Beim Hochladen der Datei ist ein Fehler aufgetreten!

**Comment by johngruen** [comment]
@dannycoates will investigate. This might be a file size issue given 32 bit FF on Win 7

**Comment by SoftVision-CosminMuntean** [comment]
I have also tested this issue on Windows 7 x64 using Firefox 54.0.1 x32 bits and I have managed to reproduce it, but only when I have tried to upload a 500 Mb zip file. 
Is not always reproducible, in most of the cases the file is successfully uploaded.

**Comment by GMAF01** [comment]
After renaming the zif file (avoiding blanks in the file name) it worked fine.

**Comment by dannycoates** [comment]
@GMAF01 thanks! We'll look into issues with file names.
