### ISSUE TITLE
Add support for Thunderbird

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/send#496]
Thunderbird is still in the Mozilla family. It would be nice to have Send as an option for sending large files, IMO preferably as an add-on, so we do not have to wait until next Thunderbird release. ;)

**Comment by ehuggett** [comment]
Great idea, not always suitable for email but if you know the receiver is waiting for the file it could be very useful indeed.

https://github.com/mozilla/send/issues/403 is somewhat related as Mozilla Thunderbird would be an excellent example of where it is not nessisary (and safer not to) execute JavaScript from Send. If both parties have a plugin, they only need the encrypted data itself. If the receiver does not have the plug-in, thunderbird would pass the url to a browser as normal.

But this would Rely on Send presenting a stable interface, so the plug-in does not need constant updates to function (a simple method to determine the "protocol version" would at least allow the plugin to tell the user it needs updating, even if no update plugin has been written)... but perhaps it will be "stable enough" without this once the current "rush" of idea's and changes ends.

**Comment by ehuggett** [comment]
related, probably a requirement (a stable interface) #431

**Comment by ehuggett** [comment]
https://support.mozilla.org/en-US/kb/filelink-large-attachments

two examples
https://github.com/meganz/filelink (MPL v2)
https://github.com/DownloadTicketService/dl/tree/master/client/thunderbird-filelink-dl (GPL v2)

Should the plugin also prompt to download send urls? Supporting privately hosted Sends would not be impossible but probably can't guarantee no false positives (http or https, hostname or ip or ip+port and it may not be on the root of the domain)
```regex
\/download\/[0-9a-f]{10}\/#[a-zA-Z\d-_]{22}$
```

How would non-english language support be handled? (can any the current strings in Send be reused?)

Not quite off topic(?): A Firefox addon would also have some benefits, I believe addons can 'hijack' urls (ie uBlocks [strict blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking)) which would make it possible to 'override' the entire send domain and replace it with a upload/download interface from the local addon? (anyone know how this would interact with the noscript addon, would it still need whitelisting?)

**Comment by ehuggett** [comment]
Thunderbird does not yet support webextensions https://bugzilla.mozilla.org/show_bug.cgi?id=1396172 but it does not seem that there are currently any plans to remove support for current extensions either

**Comment by wresuolc** [comment]
Thanks for filing this, but we have no plans to work on this in the near future.

**Comment by kewisch** [comment]
Thunderbird supports WebExtensions now, and if there is anything missing we are happy to add the neccessary APIs. From a brief read though I am not sure what specific WebExtension APIs are necessary? It seems to me that all that would be needed is WebCrypto and fetch/xhr. For adding a filelink provider there is an [API available](https://thunderbird-webextensions.readthedocs.io/en/latest/cloudFile.html) in Thunderbird.

If there is any guidance on how to programmatically send files to the API that would be a good start. It seems that some of the source code from send/app/ could be re-used.

**Comment by MarionMoseby** [comment]
Is there any progress here? Internal coherence at mozilla seems like a necessity

**Comment by timvisee** [comment]
The FileLink Provider might be a nice approach for adding it as 3rd party support.

I'm not familiar with these APIs though. Would it be possible to use the [`ffsend`](https://github.com/timvisee/ffsend) tool to achieve this, that's probably the easiest to implement?
