### ISSUE TITLE
Improve text of landing page

### ISSUE THREAD

**Issue by llagerlof** [mozilla/send#497]
The main page warns that the file expires, but does not say how long (24h). 

It also does not say that the file is deleted after the first download. I think this information should be there before the upload.

**Comment by sevaan** [comment]
I guess this depends on our roadmap, because I know eventually we want to test other expiry options (e.g. 48 hrs, or after 100 downloads). @johngruen What do you think?

**Comment by llagerlof** [comment]
I just want to add that should have a warning that the file will be deleted on download screen, before the user starts the download, or a download counter when the system supports more than one download.
