### ISSUE TITLE
Cannot connect to Send running in Docker: connection reset by peer

### ISSUE THREAD

**Issue by andreipoe** [mozilla/send#498]
Hello,

Trying to use the Docker image for Send, I cannot connect to it:

```
> curl localhost:1443
curl: (56) Recv failure: Connection reset by peer
```

These are the logs of the container:

```
> docker logs send_web_1
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm info lifecycle firefox-send@1.1.0~prestart: firefox-send@1.1.0
npm info lifecycle firefox-send@1.1.0~start: firefox-send@1.1.0

> firefox-send@1.1.0 start /app
> node server/server

FirefoxSend.CRITICAL: uncaughtException Error: Cannot find module '../public/version.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/server/server.js:12:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

I've tried `master`, `v1.1.0` and `v1.0.4`, and none of them seem to work. Every time, I've removed the old Docker image and built from scratch with `docker-compose build`. Is there any additional step I need to take when setting up that might not be documented? 

I'm happy to collect and provide further information if that helps.

Thanks!

**Comment by dannycoates** [comment]
the [circle.yml](https://github.com/mozilla/send/blob/master/circle.yml#L19) file gives a hint (but we need better instructions for building with docker in the readme) that you need to run `npm run build` before building the container.

On my local machine I do `npm run build` then `docker-compose up`

**Comment by andreipoe** [comment]
Thanks! Is this not done as part of the Docker build by choice?

**Comment by dannycoates** [comment]
> Is this not done as part of the Docker build by choice?

Yes, we end up with a smaller docker image this way
