### ISSUE TITLE
Begin metrics planning

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#5]
Let's get a `metrics.md` going.

**Comment by wresuolc** [comment]
Chuck has been working on these for the other projects, and is planning on doing this one next.  It's pretty nice to have them in a consistent style and voice.  If you have specific things you want to make sure it includes please work with Chuck to get them added.  Thanks!

**Comment by chuckharmston** [comment]
I don't have permissions to assign; would someone mind giving it to me? Thanks!

**Comment by dannycoates** [comment]
@chuckharmston also added you to the repo
