### ISSUE TITLE
Show file size limit in UI

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#50]
If a user chooses a file with a size > 2GB the upload currently silently fails. We should check the file size before loading it with the FileReader and tell the user the file is too big.

**Comment by dannycoates** [comment]
In light of #95 we should be able to have different limits based on the browser. We could base this off of `navigator.userAgent`. Does anyone have a better option to key off of?

**Comment by dnarcese** [comment]
#168 makes sure the upload doesn't silently fail and shows a generic error message... 
_specific size limit errors to come_
