### ISSUE TITLE
Send link to device

### ISSUE THREAD

**Issue by lamka02sk** [mozilla/send#511]
Hi, I really miss feature to send file link to another device. It would be nice to be able to share uploaded files between your devices.

**Comment by MikkCZ** [comment]
With [Firefox Sync](https://www.mozilla.org/en-US/firefox/features/send-tabs/) you can. Just visiting the download link does not start the file download (unless you click the button), so sending the tab with the download should work the usual way.

**Comment by ehuggett** [comment]
related #423?
