### ISSUE TITLE
Private Upload Page

### ISSUE THREAD

**Issue by LuFlo** [mozilla/send#526]
It should be possible to secure the upload page in a private area while the download pages are still available for everyone. This is when you want to run a "send"-server only for sharing your own files

**Comment by johngruen** [comment]
@LuFlo, are you trying to host your own send server? you could use htaccess or some other server config to password protect the upload page.

**Comment by LuFlo** [comment]
@johngruen Yeah, I forgot to mention that this is an idea especially for those who want to host their own servers. I know you can use htaccess but it is hard to figure out which URL to protect if you only want to protect the upload page. It would be kind of handy if you could use pluggable UserProvider or so to fetch credentials from a DB or LDAP. In addition it would be nice looking if the login page would be seemlessly embeded in the whole design :)
Thanks for the advise though!

**Comment by ehuggett** [comment]
You need to prevent access to /send from unauthenticated clients even if they cannot access the "upload webpage" (https://github.com/ehuggett/send-cli)

**Comment by LuFlo** [comment]
AFAIK the server doesn't serve any routes on /send, so my guess was to keep /upload and / (only page) private (see [](https://github.com/mozilla/send/blob/master/server/server.js))
. The other way around would be to keep everything but /download and /resources private but there are some js in the root folder.

I will do some testing in the next days and try to find other possibilities to abuse the API since mozilla send wasn't designed to have a private upload page, was it?

**Comment by ehuggett** [comment]
sorry, i completely missed the type and you trying to point it out to me. It is indeed /upload and not /send you need to restrict, sorry

**Comment by Forceu** [comment]
It would be great if there was an option to restrict the upload. Unfortunately denying /upload does not seem to work anymore
