### ISSUE TITLE
Send should have a webapp manifest

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#530]
Submitted to #TestPilot Slack channel via @snorp on Sat Aug 19 @ 12:10pm:

> Send should have a webapp manifest
> So it can be a pwa

**Comment by pdehaan** [comment]
<img width="1439" alt="lighthouse_report" src="https://user-images.githubusercontent.com/557895/29539480-dc0d59e2-867e-11e7-9764-97a504bace63.png">

**Comment by dannycoates** [comment]
vnext does
