### ISSUE TITLE
Move `<script>` tags into bottom of `<body>`

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#532]
Per https://github.com/mozilla/send/pull/516#discussion_r133370602

@pdehaan says:

> _Do these 3 `<script>` tags need to be in the `<head>`, or can we move them to the end of the `<body>` tag? In my very unscientific testing, this had a decent sized performance improvement when testing locally using Lighthouse, but that isn't always a great measure._

@dannycoates replies:

> _They shouldn't need to be in the head. worth a shot_

**Comment by pdehaan** [comment]
I'm struggling a bit with this one.
I copied the two `<script>` tags from webpack/layout.hbs from `<head>` into `<body>`, but the injected scripts still appear in `<head>`:

https://github.com/mozilla/send/blob/8f1c404724c5d586a6dca54b17b56c0b594d4b75/webpack/layout.hbs#L30-L31

---

If I inject the Webpack-ified `<script>`s into `<body>` instead of `<head>`, things get broken:

https://github.com/mozilla/send/blob/8f1c404724c5d586a6dca54b17b56c0b594d4b75/webpack.config.js#L108

I'm guessing things break because the _/resources/upload.[hash].js_ is defined in the `<body>` above the injected _/resources/runtime.[hash].js_ and _/resources/vendor.[hash].js_. I'm also assuming that the _/jsconfig.js_ file should probably be set in the `<head>` since it defines some GA and Sentry goodness.

Starting to second guess if this is worth it.

**Comment by dannycoates** [comment]
I'm rearranging some stuff that should fix this...
