### ISSUE TITLE
Copy link confirmation is too light

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#534]
I feel like the background of this confirmation checkmark button is either a) too light and should be greener, or b) should have the same green border around it as the rest of the field or c) both.

![screen shot 2017-08-23 at 12 41 54 pm](https://user-images.githubusercontent.com/473531/29627566-76704d6e-8800-11e7-9941-1c5e3c64eb56.png)

What do you think, @youwenliang?

**Comment by dannycoates** [comment]
It currently has `opacity: 0.3`

Here's 100%:

<img width="289" alt="screen shot 2017-08-23 at 10 15 08 am" src="https://user-images.githubusercontent.com/87619/29628969-18478e96-87ec-11e7-8239-d71779a20ae3.png">

**Comment by sevaan** [comment]
Let's make it full opacity (which also happens to be how the button is shown in Peko's visual design work). Thanks!

**Comment by youwenliang** [comment]
@sevaan I've changed it in my pull request #533 !

**Comment by sevaan** [comment]
Ah, awesome. Thanks!
