### ISSUE TITLE
Localize expire countdown?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#538]
Our expire countdown is currently hard coded to the form `12h 34m`, decreasing to 0 as time passes. 

@flodolo, is there a standard for localizing a timer like this? `Intl.DateTimeFormat` is the closest thing I could find, but the timer shouldn't be mistaken for a "wall clock" time.

<img width="598" alt="screen shot 2017-08-25 at 8 27 16 am" src="https://user-images.githubusercontent.com/87619/29720662-7e8a60f0-896f-11e7-82ac-9c8bc114982e.png">

**Comment by flodolo** [comment]
Intl.RelativeTimeFormat might help, but it's not there yet…
https://bugzilla.mozilla.org/show_bug.cgi?id=1270140

You could make this localizable with two strings and a detailed localization comment

```
expire_hours_mins = { $hours }h {$minutes}m
expire_mins = {$minutes}m
```
