### ISSUE TITLE
Copy and Delete should be collapsed for responsive

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#539]
The sole remaining issue from #303

**Comment by dannycoates** [comment]
Instead of collapsing, could we transform the table into something more like a "card" (more vertical space) for each file with nice big touch targets for mobile?

**Comment by johngruen** [comment]
So, let's resolve this by no-wrapping the file and using an ellipse to overflow, changing the second column to copy, and center aligning `td` elements

**Comment by dannycoates** [comment]
I left "Copy URL" to save an l10n cycle. The ellipsis seems like enough to me.
