### ISSUE TITLE
Sending the link from send using "Send Tab" is awkward.

### ISSUE THREAD

**Issue by thomcc** [mozilla/send#540]
This is a mouthful of an issue title. Sorry. I don't see an issue for this, but it's related to #511, sort of.

Currently, the URL only appears in `<input>` and so if you want to use it with Send Tab, a user has to copy the link, open it in a tab, and then send that tab. This is kind of annoying and would be relatively easy to make better:

If it appeared in an `<a>` (maybe below the `<input>`?), "Send Link to device" would be available in a context menu, and you could send it directly.

**Comment by ehuggett** [comment]
I can highlight a text that is not a link such as send.firefox.com and when I right click it I see "bookmark this link", "save link as" etc options, but when I highlight the send link (in the input box with the "copy to clipboard" button) I am not offered this option 

(I assume Send to tab options are offered in the same circumstances? I've never used it)

I just copied the input box into a blank page, same result. This seems to suggest using <input> affects anything (not just Send Tab) that depends upon the firefox detecting when text is in fact a url?

**Comment by thomcc** [comment]
@ehuggett Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1394158 for the same reason. It might be nice for that not to need to ride the trains to remove the awkwardness, though.

**Comment by johngruen** [comment]
@thomcc we definitely have not optimized for this usecase. I'll add this to stretch for now while we figure out our path forward here.

**Comment by ehuggett** [comment]
The bugzilla link shows this made it into Firefox 57 👍 (released yesterday)

I can see the "bookmark this link" etc options in Firefox 58.0b1 that I previous said were missing from the context menu for the send link

**Comment by kgbm3** [comment]
Hey, don't mean to spam; but, this issue is coming up in search query results for disabling send via userChrome.css - so, [here](https://github.com/mozilla-services/firefox-send-tab-to-device/pull/5#issuecomment-377666999)'s the gathered info and it's -still- functional w/latest release:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); /* only needed once */

/* Hide "Send Link to Device" and preceding separator */
#contentAreaContextMenu #context-sendlinktodevice, 
#contentAreaContextMenu #context-sep-sendlinktodevice {
  display: none !important;
}

/* Hide "Send Page to Device" and preceding separator */
#contentAreaContextMenu #context-sendpagetodevice, 
#contentAreaContextMenu #context-sep-sendpagetodevice {
  display: none !important;
}

/* Hide "Send Tab to Device" and separator */
#context_sendTabToDevice, #context_sendTabToDevice_separator  {display: none !important;}

/*
#context_sendTabToDevice, #context_sendTabToDevice_separator  {display: none !important;}

#context-sendpagetodevice, #context-sep-sendpagetodevice  {display: none !important;}

#contentAreaContextMenu #context-sendlinktodevice,
#contentAreaContextMenu #context-sep-sendlinktodevice {display: none !important;}
*/

/*
#context-sendaudio
#context-sendimage
#context-sendvideo
#context-sendpagetodevice
#context-sendlinktodevice
*/

/* place this code in userChrome.css in a chrome folder (lowercase) in the <xxxxxxxx>.default profile folder */
```

(Hope it helps, for anyone who may find it useful!..:))
