### ISSUE TITLE
Self hosting with local file storage

### ISSUE THREAD

**Issue by ehuggett** [mozilla/send#543]
https://github.com/mozilla/send/blob/182bde30fa3a5321e97dbe0a3480c6e40e531b7d/server/storage.js#L47

- a "random" local directory now appears to be used for storage? ie (`/tmp/send-EfYM9A` where `EfYM9A` changes every time i run `npm run build && npm run prod`), 
- /tmp is a risky location for data potentially wanted for 24 hours (reboot), but its unlikely to impact dev usage

**Comment by dannycoates** [comment]
We should add a config variable for this. The filesystem storage is mainly used for development, hence the change to temp, but I see how it's useful for self hosting.
