### ISSUE TITLE
Muliple download option 

### ISSUE THREAD

**Issue by abinabrahamanchery** [mozilla/send#544]
There should be an option to send multiple download links 
currently the link is valid only for 24 hours or Only 1 Download (which ever comes first) 
make the link active for 24 and multiple download option instead of one download option

**Comment by ehuggett** [comment]
duplicate?/related https://github.com/mozilla/send/issues/420 https://github.com/mozilla/send/issues/98 https://github.com/mozilla/send/issues/525

**Comment by pdehaan** [comment]
Yep, thanks @ehuggett!

Closing as duplicate of previously mentioned bugs.
