### ISSUE TITLE
"Send another file" is missing from the "Something went wrong!" page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#547]
[Notes]:
- The issue is not reproducible on the Prod and Stage pages.

[Affected versions]:
- Firefox Release, Beta, Nightly
- Chrome

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net/error.
2. Observe the page under the error image.

[Expected result]:
- "Send another file" link is displayed.

[Actual results]:
- "Send another file" link is missing.

[Additional notes]:
- Here is a screen shot of the issue on Dev:
![image](https://user-images.githubusercontent.com/18304511/29825785-19f60bc2-8cde-11e7-9fbe-688e2af7dfd1.png)

**Comment by dannycoates** [comment]
@sevaan I took "send another file" out because it doesn't make sense in all the areas we show this. The back button or logo link are how you'd recover. If we want more text here we'll need new strings since the current set only accounts for upload errors. Our error strings should be generic enough to work for any error.

**Comment by SoftVision-CiprianMuresan** [comment]
>The back button or logo link are how you'd recover.

I have to point out that the back button does not go back to the Upload page. Logo link works as expected and you can also refresh (F5) to get back to the Upload page.
That being said, I think we should at least have a more suggestive message like "Something went wrong, try again".

**Comment by dannycoates** [comment]
Thanks, I'll change it so the back button works

**Comment by wresuolc** [comment]
Let's make it "Send a file"

**Comment by shikhar-scs** [comment]
@SoftVision-CiprianMuresan @wresuolc @dannycoates if this issue is still up, can i work on it ?

**Comment by himanish-star** [comment]
@dannycoates , Can I take over this issue ?

**Comment by dannycoates** [comment]
@himanish-star yep!

**Comment by himanish-star** [comment]
Thanks, but I think @shikhar-scs asked for it first. So if it's okay with @shikhar-scs , only then will I tackle this

**Comment by shikhar-scs** [comment]
Thanks @dannycoates . I'll get started with it now and in case I dont manage to, @himanish-star can always take over :+1:

**Comment by dannycoates** [comment]
back button works. closing as wontfix
