### ISSUE TITLE
any possible way to integrate tus.io for resumable file upload?

### ISSUE THREAD

**Issue by hbakhtiyor** [mozilla/send#551]
[Open protocol for resumable file uploads](https://tus.io/)

[here's](https://github.com/psi-4ward/psitransfer) similar `send` project which used tus.

**Comment by ehuggett** [comment]
That looks really interesting, thanks, I've bookmarked it for future reference (/use in other projects).

This would be related to #18, as larger files take longer to upload (and the probability and consequences of network issues increase with filesize).

#174 would result in the file(s) being uploaded in "chunks", each of which could be retried individually should any of them fail to upload (most likely retransmitting the entire chunk for simplicity, the probability of failure should be low enough not to complicate it any further?).

**Comment by Acconut** [comment]
Hello, I am the project lead on the tus protocol and would like to offer my help. Even if I don't have much experience with Firefox Send, I am more than happy to answer your questions regarding tus. :)
Depending on your requirements, the tus-js-client (https://github.com/tus/tus-js-client) may already be usable for you.

**Comment by hbakhtiyor** [comment]
btw, reasonable also to integrate uppy here?

**Comment by ehuggett** [comment]
> btw, reasonable also to integrate uppy here?

(personal opinion) not yet at least? 

You can only upload one file and the the OS open file dialogues from any modern desktop (windows, osx, gnome, kde etc) will display content previews. Perhaps once the user can upload multiple files? As we would presumably wait for the user to say "done, now upload it" they could be displayed at this stage. But I think we should be careful how content-previews are used for perceptions sake (ie replace them all with a lock symbol or don't display them at all once encryption starts).

**Comment by Acconut** [comment]
> You can only upload one file and the the OS open file dialogues from any modern desktop (windows, osx, gnome, kde etc) will display content previews. Perhaps once the user can upload multiple files?

In case you are wondering, Uppy is capable of uploading multiple files at the same time. You can try out their demo: https://uppy.io/examples/dashboard/
