### ISSUE TITLE
I think you can integrate mzl.la short link service, make url more beautiful!

### ISSUE THREAD

**Issue by istrwei** [mozilla/send#552]
I think you can integrate mzl.la short link service, make url more beautiful!

**Comment by ehuggett** [comment]
I can't actually find a link shortening service from Mozilla? Perhaps I've misinterpreted, but the clear goal appears to be shorter URL's so I've outlined why the links are currently the length they are and what could potentially be done about it

`https://send.firefox.com/download/987baba32f/#hNYoNIbyxDm4F-1WByhwKA`

The following points are formatted as "[current length, potential minimum length] description"
- [8,8] `https://` is required, or the device may attempt to connect over http (making the initial connection vulnerable)
- [16,6]`send.firefox.com` any domain would work, this could be shorter, but we would lose the brand association with Firefox (and the domain would have to be only a variation of "send" to keep it short)
- [10,1] `/download/` is probably a good idea to keep as it tells the user what to expect, If/when the domain becomes known for transferring files perhaps it wouldn't be as necessary (but still useful).
- [11,8] `987baba32f/` this is the fileid, it must be unpredictable so its length is important (and may become longer as usage increases). the final '/' could in theory be removed.
  - Its actually hex encoded, 50% efficiency (as it takes two characters, 16 bits, to store 8 bits worth of data). We might be able to save 2 characters here
- [23,20?] '#hNYoNIbyxDm4F-1WByhwKA' is the base64 encoded encryption key. 
  - '#' is absolutely essential, it's what prevents the browser sending this secret to the server when the link is used. 
  - The encoded data cannot be any shorter, breaking the standard and using something other than base64 might save a couple of characters. 
  - In a perfect world it would be given to the downloader privately (ie via a secure chat service) as any security Send offers is utterly dependant upon it remaining secret. **Storing it on a mozilla link shortening service would utterly destroy any promises about Mozilla not being able to read the uploaded files.**

Ignoring the encoding in the last point, the links could be 20 characters shorter reducing them from 68 characters to 46 ie

`https://abc.de/-87J_Za3#hNYoNIbyxDm4F-1WByhwKA`

But I think most of those characters are worthwhile keeping for one reason or another, and the result doesn't look much better (there is nothing legible to read). The effort required to remove them would also not be trivial (+ the cost of acquiring such a domain)

**Comment by istrwei** [comment]
I thought the suffix is randomly generated string, the original is the key, understand, understand the principle, it is very cool!

**Comment by pdehaan** [comment]
Ref #87
