### ISSUE TITLE
Upload videos causes errors

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#560]
Noticing some survey feedback from users trying to upload video files and receiving errors. I just tried uploading an mp4 video and it didn't work.

**Comment by sevaan** [comment]
So I had trouble uploading a video, but now when I do it I can't reproduce the error. Sorry!

**Comment by johngruen** [comment]
Try to repro? @sevaan

**Comment by sevaan** [comment]
Tried with numerous video files and have been unable to duplicate my original issue. Recommend closing for now and see if it arises again.
