### ISSUE TITLE
Possible Italian localization correction

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#562]
From survey feedback:

> The translation of crypto in Italian shouldn't be "crittica" but crittografata 

@mathjazz @flodolo

**Comment by flodolo** [comment]
I have no idea where they found "crittica", but "crittata" is a specific choice.
http://www.apogeonline.com/webzine/2012/08/01/cifrare-o-crittare-questo-e-il-problema
https://forum.mozillaitalia.org/index.php?topic=67103.0
http://blog.terminologiaetc.it/2011/04/11/decifrare-decodificare-decrittare-decrittografare/
