### ISSUE TITLE
After cancelling an upload, the file should not appear on the homepage file list

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#564]
STR:

- Upload a file and cancel it before it completes.
- Refresh home page.
- File appears with the ability to copy the link to the file

If you visit the URL, it appears to be a valid download, complete with the full file-size.
You can download, but it freezes once it hits the point where you cancelled the upload.

**Comment by sevaan** [comment]
I put some STR here, but now I follow them again the file name isn't appear on the home page.

**Comment by johngruen** [comment]
@sevaan would be good to have console logs when you cancel and maybe video evidence.

**Comment by sevaan** [comment]
Tried with numerous video files and have been unable to duplicate my original issue. Recommend closing for now and see if it arises again.
