### ISSUE TITLE
The tooltip is no longer displayed when the "Select a file to upload" button is hovered

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#565]
[Notes]:
- The issue is also reproducible if you are on the "Beefy" experiment.
- The issue is not reproducible on production.

[Affected versions]:
- Firefox 55.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.stage.mozaws.net/" page.
2. Hover the "Select a file to upload" button and observe the behavior.

[Expected result]:
- "Select a file to upload" tooltip is displayed.

[Actual results]:
- No tooltip is displayed.

[Additional Notes]:
- Here is a screen recording with the issue:
![no tooltip](https://user-images.githubusercontent.com/19226534/30374311-2f9d999e-988d-11e7-8386-4ccd7b4b503c.gif)

**Comment by SoftVision-CosminMuntean** [comment]
It seems that all the buttons from "Copy Link"page, "Download" page and the "Cancel Upload" button do not have a tooltip.
Here is a screen recording with all buttons:
![tooltips send buttons](https://user-images.githubusercontent.com/19226534/30379243-7d1de60e-989e-11e7-99cd-351b3fc06225.gif)

**Comment by johngruen** [comment]
This is fixed on @dannycoates machine, will be merged soon
