### ISSUE TITLE
The upload/download percentage is no longer displayed as the tab title when the tab is not focused

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#566]
[Notes]:
- On production the upload/download percentage is correctly displayed on the tab title when it's not focused.

[Affected versions]:
- Firefox 55.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a large file.
3. Focus another tab and observe the the tab title of the Send page. 

[Expected result]:
- The upload percentage is displayed.

[Actual results]:
- The upload percentage no longer displayed.

[Additional Notes]:
- This issue is also reproducible on dev.
- Here is a screen recording with the issue:
![progress](https://user-images.githubusercontent.com/19226534/30384478-0ee2d302-98ad-11e7-9c9d-c0a148f1e224.gif)

**Comment by johngruen** [comment]
We may wind up pushing this up today

**Comment by dannycoates** [comment]
fixed
