### ISSUE TITLE
The blue progress bar is no longer displayed while uploading/downloading a file on Microsoft Edge

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#567]
[Notes]:
- This issue is not reproducible on production.

[Affected versions]:
- Microsoft Edge 25.10586.672.0

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the Microsfot Edge browser and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a large file.
3. Observe the progress bar.

[Expected result]:
- The progress bar is filling up with a blue color.

[Actual results]:
- The blue progress bar is no longer displayed.

[Additional Notes]:
- This issue is also reproducible on dev.
- Here is a screen recording with the issue:
![send_issue](https://user-images.githubusercontent.com/19226534/30387669-f14d1268-98b5-11e7-9d64-5e92c39a15d7.gif)

**Comment by johngruen** [comment]
"I hate edge" - @dannycoates

**Comment by johngruen** [comment]
Lemmie verify that we're not seeing a lot of traffic on edge

**Comment by dannycoates** [comment]
Works in Edge 16

**Comment by dannycoates** [comment]
Except the spinner because edge doesn't support svg css animations yet - https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6820655-add-css-transforms-on-svg-elements
