### ISSUE TITLE
Cancel button does not work when upload reaches 100%

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#568]
When an uploaded file reaches 100%, there is still an opportunity to hit the cancel button, showing the message "Your upload was cancelled", however it still goes to the URL page and the upload is visible on your home page.

**[Video showing issue](http://i.sevaan.com/3D3U3s0y1l0C)**

Solutions:
a) Hitting cancel even after the upload hits %100 should actually delete the file
b) Remove the cancel button when 100% is hit, so a user can't accidentally click it. They can delete it on the subsequent screen.

**Comment by johngruen** [comment]
b) seems easier

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev page. There still is a fraction of a second when the upload reaches 100% and the cancel button can be clicked, but if I click it, the upload is canceled.
