### ISSUE TITLE
Set max-width property on home page file list

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#569]
In Issue #555 @TemaSM showed us that with the updated Russian localization, the filename column on the homepage gets pretty squished. We should set some max-width properties to prevent this.

![image](https://user-images.githubusercontent.com/473531/30448340-890ac1e4-995c-11e7-97bb-814199d9ee73.png)

**Comment by dannycoates** [comment]
this was already done in fddc415c861e68e71bc050eab8d34942b5f3f63f
