### ISSUE TITLE
Set up a DMCA process

### ISSUE THREAD

**Issue by wresuolc** [mozilla/send#572]
- [x] Add a "Report IP Infringement" link to the footer which links to https://www.mozilla.org/about/legal/report-infringement/ (see Screenshots for an example)
- [x] We need the ability to remove a file based on a DMCA complaint.  Either disable temporarily or completely delete.
- [x] If a visitor tries to view a file that has been disabled/removed they see a regular not available page.
- [x] We need to document the process in our /docs/ somewhere

**Comment by wresuolc** [comment]
@dannycoates and I talked about this and he's going to write the doc based on https://github.com/mozilla-services/screenshots/blob/master/docs/takedown.md

**Comment by dannycoates** [comment]
doc added in 46f641aaec4d3fae636fdcbf0229e781a34e24e2

**Comment by wresuolc** [comment]
@dannycoates what happens to the file on disk?

**Comment by dannycoates** [comment]
updated https://github.com/mozilla/send/blob/master/docs/takedowns.md
