### ISSUE TITLE
The password field is displayed for a moment at page refresh, even if the file doesn't have a password

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#575]
[Affected versions]:
- Firefox 55.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to "http://54.190.37.119" page.
2. Upload a file and copy the download link.
3. Paste the link in a new tab and press enter.
4. Refresh the page and observe the behavior.

[Expected result]:
- The page is correctly refreshed.

[Actual results]:
- When the page is refreshed, the password field is wrongly displayed for a moment. 

[Notes]:
- If the issue is not reproducible refresh the page multiple times.
- Here is a screen recording with the issue:
![refreshing1](https://user-images.githubusercontent.com/19226534/30864740-32e85ce2-a2dd-11e7-89a2-c234b0d15ef3.gif)

**Comment by johngruen** [comment]
Fixed in the password branch

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Send dev page and the issue is no longer reproducible. Marking as verified.
