### ISSUE TITLE
"Try Firefox Send" button wrongly redirects to the "Uploading" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#576]
[Affected versions]:
- Firefox 55.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to "http://54.190.37.119" page.
2. Upload a file and copy the download link.
3. Paste the link in a new tab and press enter.
4. Click the "Try Firefox Send" button and observe the behavior.

[Expected result]:
- You are redirected to the Send homepage.

[Actual results]:
- You are redirected to the "Uploading" page.

[Notes]:
- Here is a screen recording with the issue:
![try firefox send](https://user-images.githubusercontent.com/19226534/30864762-4952370a-a2dd-11e7-9828-865d55fc7dc4.gif)

**Comment by johngruen** [comment]
This is fixed in the password branch...

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Send dev server and the issue is no longer reproducible. Marking as verified.
