### ISSUE TITLE
The "File size" error message is no longer displayed when uploading a file over 2GB

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#578]
[Affected versions]:
- Firefox 55.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to "send.stage.mozaws.net" page.
2. Upload a large file over 2GB.
3. Observe the browser behavior.

[Expected result]:
- An error message is displayed to warn you that the file size limit is 2GB.

[Actual results]:
- You are redirected to the "Something went wrong" page.

[Notes]:
- I recall that there was an error message that was displayed when you tried to upload a large file (over 2GB), but it was probably lost somewhere.
- Here is a screen recording with the issue:
![over 2b](https://user-images.githubusercontent.com/19226534/30918131-543a9c10-a3a6-11e7-9ec5-6c1cb3174035.gif)

**Comment by johngruen** [comment]
Let's add this back in soon.

**Comment by himanish-star** [comment]
@SoftVision-CosminMuntean , @johngruen . I would like to fix this issue

**Comment by himanish-star** [comment]
@SoftVision-CosminMuntean I face another issue as the page doesn't redirect me and moreover files of size more than 500MB also don't get uploaded in my case

![simplescreenrecorder-2017-12-24_11 19 16](https://user-images.githubusercontent.com/30361728/34324619-64eac66e-e89f-11e7-8fe3-327a12179bcf.gif)

**Comment by SoftVision-CosminMuntean** [comment]
@himanish-star this is a known issue. Chrome crashes when you try to upload a file larger than 1 GB, see issue #170. But, I suggest you to use Firefox x64 build.

**Comment by himanish-star** [comment]
Thanks @SoftVision-CosminMuntean , I will do this as soon as possible

**Comment by himanish-star** [comment]
@SoftVision-CosminMuntean , My firefox version is 57.0.1 (64bit) , even now the same problem persists and my firefox browser gets hanged up on uploading and then I got to restart my laptop

**Comment by shikhar-scs** [comment]
@himanish-star  you still working on this issue ??

**Comment by himanish-star** [comment]
@shikhar-scs , you can go ahead. My window crashes everytime I upload above 1GB

**Comment by SoftVision-CosminMuntean** [comment]
@himanish-star I think you encounter issue #391. If you have a machine that has < 4 GB RAM when you try to upload a large file > 1 GB the website will crash or the system will freeze.

**Comment by himanish-star** [comment]
@SoftVision-CosminMuntean ,yes I do have RAM less than 4GB

**Comment by shikhar-scs** [comment]
Thanx @himanish-star for handling me this. I'll work on it and file a PR soon. 
@SoftVision-CosminMuntean just wanted to confirm that only a warning is to be declared or do I also need to cancel the upload for >2GB.

**Comment by SoftVision-CosminMuntean** [comment]
After the warning is displayed the upload should be automatically canceled.

**Comment by shikhar-scs** [comment]
@SoftVision-CosminMuntean I've filed the PR, keeping all these things in mind. Please review it  #695

**Comment by SoftVision-CosminMuntean** [comment]
The issue is still reproducible on Send dev and stage servers. If you try to upload a file bigger than 2GB, you are redirected to the "Something went wrong!" page and no error message to warn you that the file size limit is 2GB is displayed.
Tested with latest Nightly 60.0a1 build on Windows 10, 7 x64  and Mac 10.12.

**Comment by dannycoates** [comment]
DRAG AND DROP!!!!
