### ISSUE TITLE
Files are no longer uploaded when dragged and dropped, after clicking the "Try Firefox Send" link from a download page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#584]
[Affected versions]:
- Firefox 56.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Receive a download link and navigate to it.
2. Click the "Try Firefox Send" link button. 
3. Drag and drop a file in the drop area.
4. Observe the behavior.

[Expected result]:
- The file is uploaded.

[Actual results]:
- The file is opened in the browser.

[Notes]:
- The issue is not reproducible on the Stage and Prod versions.
- The issue is also reproducible on other supported browsers.
- Here is a screen recording with the issue:
![files are opened instead of being uploaded](https://user-images.githubusercontent.com/18304511/31450367-ec551fd2-aeb1-11e7-8598-95a1cf3c3d22.gif)

**Comment by ericawright** [comment]
I can't seem to reproduce on production, but I CAN reproduce locally
