### ISSUE TITLE
Running in own server

### ISSUE THREAD

**Issue by Fastidious** [mozilla/send#585]
Could instructions on how to get it working on a private server be written? Or, can anyone submit them (PR)? Thanks!

**Comment by dannycoates** [comment]
Deployments can vary a lot based on your environment. App parameters can all be set with environment variables. We use docker so it's documented in https://github.com/mozilla/send/blob/master/docs/docker.md

Also our Dockerfile has some useful setup commands for reference https://github.com/mozilla/send/blob/master/Dockerfile

**Comment by ehuggett** [comment]
In addition to the provided documentation
- you will also need a reverse proxy to handle https 
   - **beware HSTS headers are set in Send itself** with an expiry of 1 year (not configurable)
   - you should configure HPKP here if you wish to use it
- If you don't want to use s3 (and i suspect private servers will prefer local storage) you should probably take a look at modifying the docker config to use a storage volume (if not using docker, just set file_dir in the config)
- beware send does not (yet, #536) delete files upon expiry (so they will accumulate and fill your storage)
   - If using s3, you will need to configure automatic deletion rules
   - If using local storage, you might be able to use a cron script to delete files based on their creation time from the file_dir (or include my patch and enable it in the send config by setting `redis_event_expire` to `true` after adding `notify-keyspace-events "xE"` to your redis config)

Is there any documentation on how to upgrade send while keeping your data?
- Data loss, you can't download a file uploaded on 1.4 from a 2.0 server
- Presumably you need keep the old server (container) running for 24 hours (/whatever expiry you have configured) and somehow route download requests for files uploaded before the upgrade to it

**Comment by zaksoup** [comment]
Hi @dannycoates, I am interested in potentially deploying send on a private server. I feel comfortable with the infrastructure requirements but I'm curious as to how Send uploads to an s3 bucked given only a named bucket. How does Send have access to the bucket without IAM keys?

**Comment by dannycoates** [comment]
@zaksoup we run the app server on EC2 and use an IAM role so we don't need to pass credentials to the app (its automatically handled by aws-sdk). See http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html

**Comment by unl1k3ly** [comment]
@ehuggett You mentioned important points. Is there a way to have a docker using file_dir rather than redis server? I haven't yet find a way to do such.
