### ISSUE TITLE
Incorrect 'Accept-Language' header handling

### ISSUE THREAD

**Issue by uncleyo** [mozilla/send#586]
When page is requested with `Accept-Language: en,uk;q=0.7,da;q=0.3` it should render in English and not Ukrainian.

**Comment by ericawright** [comment]
@uncleyo can you give me some steps to reproduce the issue here?

**Comment by uncleyo** [comment]
Sure,

`curl https://send.firefox.com -H "Accept-Language: en,uk;q=0.7,da;q=0.3"`.
`curl https://send.firefox.com -H "Accept-Language: en-GB,uk;q=0.7,da;q=0.3"`.

Please note that `curl https://send.firefox.com -H "Accept-Language: en-US,uk;q=0.7,da;q=0.3"` works correctly, so it's probably not a problem with parsing, but with actually handling some locale names.

**Comment by da2x** [comment]
Steps to reproduce the issue from within Firefox:

1.  Open `about:config`
2. Set `intl.accept_languages` to `en-US, en;q=0.8`
3. Try to upload or download a file from https://send.firefox.com
