### ISSUE TITLE
Able to upload files more than 1 GB

### ISSUE THREAD

**Issue by avinoth** [mozilla/send#588]
Tested on:

Chrome - 61.0.3163.100
Firefox - 55.0.3

OS - Mac OS Sierra 10.12.6

Expected - To throw File size exceeded, or redirect to `Something went wrong` page pertaining to this issue - #578 

Gif of the issue.

![exceeding-file-size](https://user-images.githubusercontent.com/7291330/31458913-11817a58-aedf-11e7-8a52-bde17167545c.gif)

**Comment by dannycoates** [comment]
Thanks for the report 👍 

The actual limit is currently 2GB. We recommend 1GB because performance can suffer on some devices with files that large at the moment but we don't want to be too strict about it.
