### ISSUE TITLE
Cancelling an upload while "encrypting" does not work.

### ISSUE THREAD

**Issue by avinoth** [mozilla/send#589]
Tested on:

Chrome - 61.0.3163.100
Firefox - 55.0.3

OS - Mac OS Sierra 10.12.6

[Steps to Reproduce]

1. Open https://send.firefox.com
2. Upload a big file (so the app will take a while for encrypting)
3. When the upload nears encryption (after couple of seconds `encrypting` message becomes visible), press `Cancel upload`

[Expected behavior]

The upload should be cancelled and the file uploader interface should be shown.

[Actual behavior]

It continues the upload.

Gif of the issue.

![cancelling-upload](https://user-images.githubusercontent.com/7291330/31459647-66c9a7ae-aee1-11e7-8c12-c31853765d76.gif)

**Comment by ericawright** [comment]
@avinoth I can't reproduce this using Mac: Firefox 57, nor Chrome 61. Can you still reproduce it? And, does it cancel properly during the importing and uploading phase?

**Comment by ehuggett** [comment]
Using Firefox ESR 52.4.0 (64-bit) on Debian, I can reproduce this on send.firefox.com (837747f) but not send.dev.mozaws.net (acbf9fc)

On send.dev.mozaws.net, when the message changes to "Encrypting" there is a slight delay after clicking cancel (not long enough that I think it finished encrypting the 1GB file, that takes longer if I  allow it to start uploading) but it does cancel the download, I can also cancel at the importing and uploading stages.

It may be worth noting that the cancel link lines up perfectly with the "upload a file button", an impatient user might click multiple times and inadvertently open the file upload dialog (I managed to do this... )

**Comment by dannycoates** [comment]
I was able to reproduce this on v1.2.3 but not v2.0.0 which is now in production. Please reopen if it's still broken for you.
