### ISSUE TITLE
Upload stops near completion on Firefox 50 & 51

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#590]
[Affected versions]:
- Firefox 50 & 51

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Open the Firefox 50 or 51 version and navigate to https://send.stage.mozaws.net/.
2. Upload a file.
3. Observe the browser behavior.

[Expected result]:
- The file is successfully uploaded.

[Actual results]:
- Upload starts, but before it's completed you are redirected to the "Something went wrong" page.

[Additional notes]:
- The issue is also reproducible on dev and production servers.
- Download is working as expected.
- Here is a screen recording with the issue:
![send firefox 50](https://user-images.githubusercontent.com/19226534/31504064-187f8656-af7a-11e7-8abe-254241eee8fc.gif)

**Comment by wresuolc** [comment]
ESR is 52, these are unsupported.
