### ISSUE TITLE
Inform the user that he cannot add a password for a previously sent download link

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#592]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net.
2. Upload a file and click on the "Copy to clipboard" button.
3. Open a new tab and navigate to the copied link.
4. Switch back to the "Copy link" tab.
5. Click on the "Require a password to download this file" checkbox and write a password.
6. Click the "Add Password" button and observe the behavior.

[Expected result]:
- A user friendly message is displayed informing the users that they cannot add a password anymore.

[Actual result]:
- The password is not added.

[Notes]:
- The first attempt to add the password fails and invalidates the sent download link. At the second attempt, the password is successfully added. Also, if the link is reaccessed the password field is displayed and the encrypted file can be downloaded.
- Here is a screen recording of this issue:
![send password](https://user-images.githubusercontent.com/31244235/31550177-2636c48e-b039-11e7-9716-f84da85e1732.gif)

**Comment by wresuolc** [comment]
This isn't a scenario we want to implement for this experiment. Thanks
