### ISSUE TITLE
The password field is not validated if it's empty

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#593]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to "https://send.dev.mozaws.net" page.
2. Upload a file and select the "Require a password to download this file" checkbox.
3. Leave the password field empty.
4. Click the "Add Password" button and observe the behavior.

[Expected result]:
- A error message is displayed to inform the user that the password field is empty.

[Actual result]:
- Nothing happens.

[Notes]:
- Here is a screen recording of this issue:
![empty field](https://user-images.githubusercontent.com/19226534/31550040-aacf6b5c-b038-11e7-983b-369ed342eacb.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is also reproducible for the "Unlock" button, when downloading an encrypted file.

**Comment by johngruen** [comment]
let's just use HTML 5 validation with a tool tip that says `Please enter a password`

**Comment by dannycoates** [comment]
I'd prefer this:
![pwd](https://user-images.githubusercontent.com/87619/32240965-03f09188-be2c-11e7-8a13-b3723689e91d.gif)

**Comment by ehuggett** [comment]
Some (alternative) examples reusing the "disabled button" style used for "Copy to clipboard" (and increasing the border px from 1 to 2).
![Disable the button and increase the border size](https://user-images.githubusercontent.com/8090731/32253520-459fccea-be93-11e7-9af1-cd697dcfc757.png)
[Disable the button (without increased border)](https://user-images.githubusercontent.com/8090731/32253522-45d7aaca-be93-11e7-876f-06355a255dcd.png)
[back to normal when not empty (no changes)](https://user-images.githubusercontent.com/8090731/32253521-45bc3272-be93-11e7-8392-0c0dde9a5064.png)
![screenshot-2017-10-31 firefox send 4](https://user-images.githubusercontent.com/8090731/32253960-c3001c56-be95-11e7-83dc-d52f70af3d92.png)
[homepage example (without increased border)](https://user-images.githubusercontent.com/8090731/32253915-7bacaa18-be95-11e7-891f-e0dbb9cdd112.png)

**Comment by johngruen** [comment]
Let's go with @dannycoates suggestion here
