### ISSUE TITLE
The "Password" and "Copy to clipboard" fields are misaligned

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#594]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net.
2. Upload a file and click on the "Require a password to download this file" checkbox.
3. Observe the "Password" field position in comparison with "Copy to clipboard" field.

[Expected result]:
- The "Password" and "Copy to clipboard" fields have the same alignment.

[Actual result]:
- The "Password" and "Copy to clipboard" fields are misaligned. 

[Notes]:
- Here is a screen shot of the issue:
![aliniament](https://user-images.githubusercontent.com/31244235/31552712-ef7c6dce-b040-11e7-8654-0276e23c7c50.png)

**Comment by sevaan** [comment]
The password box should be aligned to be underneath the checkbox. Also, it should be blue (same blue as the URL field outline) to show it as active.

<img width="653" alt="screen shot 2017-10-16 at 1 48 06 pm" src="https://user-images.githubusercontent.com/473531/31626697-bf2cb644-b278-11e7-8ddf-078c56693213.png">

**Comment by Softvision-CristinaBadescu** [comment]
I can confirm that this issue is not reproducible anymore on Send dev server, using latest Nightly build 58.0a1 (2017-10-23) on Windows 10x64, Mac 10.12 and Ubuntu 14.04 x64.
