### ISSUE TITLE
HKDF not supported - Chrome

### ISSUE THREAD

**Issue by unl1k3ly** [mozilla/send#595]
Last commit is causing an error on Chrome when upload files.

```app.b9d07081.js:1 Error: Algorithm 'HKDF' is not supported
    at r [as constructor] (cryptofill.a5d7e403.js:1)
    at new r (cryptofill.a5d7e403.js:1)
    at cryptofill.a5d7e403.js:1
    at new Promise (<anonymous>)
    at r.e.importKey (cryptofill.a5d7e403.js:1)
    at r.importKey (cryptofill.a5d7e403.js:15)
    at new t (app.b9d07081.js:1)
    at app.b9d07081.js:1
    at r (vendor.0a0831d6.js:1)
    at Generator._invoke (vendor.0a0831d6.js:1)
```

**Comment by ehuggett** [comment]
I was unable to reproduce this with Chromium on https://send.dev.mozaws.net/ (I had the console open expecting to see the error you provided, but the file uploaded successfully). 

Chromium - `Version 61.0.3163.100 (Developer Build) built on Debian 9.1, running on Debian 9.2 (64-bit)`
Send - {"commit":"402ab35","source":"https://github.com/mozilla/send/","version":"v1.2.4"} (this was the latest commit at time of writing)

**Comment by wresuolc** [comment]
@SoftVision-CosminMuntean @SoftVision-CiprianMuresan @Softvision-CristinaBadescu -- anyone seeing this?

**Comment by unl1k3ly** [comment]
It's funny because, when I run a prod env and access it from localhost it works... when I access it from an external interface or even internal interface it shows the "HKDF" error when using Chrome. It works as great on Firefox. Am I doing something stupid ?! Thanks for all support guys.

**Comment by unl1k3ly** [comment]
Steps to reproduce is simple as:
- git clone  https://github.com/mozilla/send/
- add .aws/creds
- add  s3 bucket name on server/config.js
- do npm install && npm run build && npm run prod
- access the $ip:1443 and upload anyfile using Chrome.

It works if i access it from localhost:1443

Cheers

**Comment by unl1k3ly** [comment]
Hi all, Ive found the issue...

It needs to run over TLS/SSL! Simple as that! I've created a selfsign cert, and deployed using a revproxy.... it works as great!

Thank you
