### ISSUE TITLE
TSL/SSL CERTS

### ISSUE THREAD

**Issue by unl1k3ly** [mozilla/send#596]
Hi all, this is more a questions rather than an issue... 

Would be possible to explain how to deploy a TSL/SSL built in on SEND application ?

Thanks

**Comment by wresuolc** [comment]
Are you trying to set up a copy of Send on your own server?  If not, can you explain more what you're wanting to know?  Thanks.

**Comment by unl1k3ly** [comment]
Hi @wresuolc, I'm sorry for the lack of information... Yes,  I'm setting a dedicate environment from a git fork. Do you have instructions or any idea on how to set the certs up ? Thanks a lot

**Comment by unl1k3ly** [comment]
In fact, I can do that by adding a rev proxy at the front. So, my question is if is there a way to add certs from send configs ? Thanks mate

**Comment by wresuolc** [comment]
Any certs you add will probably have to be done at the web server level.  Good luck!
