### ISSUE TITLE
nonce is overwritten by subsequent authentication attempts

### ISSUE THREAD

**Issue by ehuggett** [mozilla/send#597]
The nonce is overwritten by subsequent authentication attempts, this causes a user to be "deauthenticated" when a second (sucessful or otherwise) authentication attempt is made for that file.

server: https://send.dev.mozaws.net/
version: {"commit":"402ab35","source":"https://github.com/mozilla/send/","version":"v1.2.4"}

Steps to reproduce
1. upload a file, set a password. copy the Send link to your clipboard
2. Open two browser tabs
3. In tab A, load the URL and enter the correct password
4. In tab B, load the URL and enter an incorrect password
5. Attempt to download the file in tab A, you will receive an error.

edit: removed link to wrong file

**Comment by ehuggett** [comment]
I've just noticed I've linked completely the wrong file & a password isn't required to reproduce this (still present today in `{"commit":"490a1e8","source":"https://github.com/mozilla/send/","version":"v2.0.0"}` )

The original steps still reproduce the error, but it also be triggered without a password
1. Upload a file
2. Open the download link in two tabs (A and B)
3. Attempt to download the file in tab A, you will receive a "Something went wrong!" error

Or when entering the password
1. Upload a file
2. Open the download link in two tabs (A and B)
3. Type the wrong password into tab B and submit it
4. Type the right password into tab A and submit it, you will incorrectly receive the error "Incorrect password. Try again."
5. Type the right password into tab B and submit it, you will incorrectly receive the error "Incorrect password. Try again."
 
- Every attempt to retrieve the metadata will change the nonce for that file, so loading the link (/trying a password) in tab B means the nonce tab A received is no longer valid. https://github.com/mozilla/send/blob/490a1e88eb88798f7642345450f5d503e48d01f9/server/routes/metadata.js#L20-L21
- both `api/metadata` and `api/download` will respond with a status code of 401 if the Authorization header is not valid and will include the new nonce in the WWW-Authenticate header
  - The client could retry the request with the new nonce if this happens
      - If this happens before a unrelated request changes the nonce again it will succeed 
      - note an incorrect password will _always_ trigger a 401 but the second attempt to `api/metadata` failing doesn't guarantee the password is incorrect (but it does seem probable)

**Comment by ehuggett** [comment]
This could be triggered by #525 as your likely to have multiple users trying to download the file in short succession

No download limit (Unlimited) would allow posting links to twitter etc so simply retrying with the new nonce as i suggested could exasperate this issue (to the point where the round trip time could exceed the interval at which the nonce is changing).

**Comment by himanish-star** [comment]
So can I work on this ?

**Comment by dannycoates** [comment]
Since this was reported we've changed the nonce behavior to only change after a successful authentication, and added a retry on the frontend for authed requests. I think that's probably enough to consider this issue closed.

**Comment by himanish-star** [comment]
Ok, @dannycoates. I'll find another one :disappointed:
