### ISSUE TITLE
Password checkbox remains checked after restarting the browser

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#598]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net.
2. Upload a file and click on the "Require a password to download this file" checkbox.
3. Restart the browser using the Developer Toolbar and observe the behavior of the require password checkbox.

[Expected result]:
- The require password checkbox is unchecked.

[Actual result]:
- The require password checkbox is checked and the "Add Password" field is not displayed.

[Notes]:
- This issue is reproducible when restarting the browser with the "Show your windows and tabs from last time" preference enabled.
- This issue is also reproducible using the "Restart to update Nightly" option. 
- Here is a screen recording of the issue:
![require password](https://user-images.githubusercontent.com/31244235/31662839-a79fe412-b348-11e7-81c6-14c61b52cc4e.gif)

**Comment by wresuolc** [comment]
Since this is reloading the same page, this just seems like a feature of the browser (remembering form state).  We're going to close this.

**Comment by Softvision-CristinaBadescu** [comment]
I've tried to reproduce again this issue on Chrome but the behaviour is different than on Firefox. On Chrome, after restarting the browser, the password checkbox is no longer checked.
On Firefox the password checkbox is unchecked if the page is manually refreshed.

**Comment by wresuolc** [comment]
This is still a feature of the browser.  It remembers form state unless you hard-refresh.  Eg. https://stackoverflow.com/questions/7377301/firefox-keeps-form-data-on-reload for someone running into the same issue.  This is working as expected.
