### ISSUE TITLE
Password isn't wrapped if it is very long

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#599]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net.
2. Upload a file and click on the "Require a password to download this file" checkbox.
3. Type in the "Password" field an excessive number of characters (at least 75 characters) and click on "Add password" button.
4. Observe how the password is displayed.

[Expected result]:
- The password is wrapped.

[Actual result]:
- The password is displayed on a single row.

[Notes]:
- If the password has more that 150 characters, a horizontal scrollbar appears and the password is not wrapped to a second row.
- Here is a screen shot of the issue:
![very long password](https://user-images.githubusercontent.com/31244235/31664968-15832d3e-b350-11e7-9711-7130644abd37.png)

**Comment by wresuolc** [comment]
Lets cap passwords at 64 characters.

**Comment by Softvision-CristinaBadescu** [comment]
I can confirm that this issue is no longer reproducible and the password has a 64 characters limit, on Send dev server, on latest Nightly build 58.0a1 (2017-10-30) using Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
