### ISSUE TITLE
"NaNundefined of 1.0B" string is wrongly displayed for 1 second when uploading a small size file

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#601]
[Affected versions]:
- Firefox 56.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to "https://send.firefox.com" page.
2. Drag and drop a file in order to upload it.
3. Observe the string underneath the progress circle.

[Expected result]:
- The uploading progress of the file is updated constantly. 

[Actual results]:
- "NaNundefined of 1.0B" string is displayed for ~1 second before the uploading progress starts. 

[Notes]:
- This issue is intermittent, but I noticed there are better chances to reproduce it if there is no file in the uploaded list.
- Also, I managed to reproduce it using only small size files (0.99MB, 4.1 MB and 287KB). With 1GB and 200 MB files, this issue is not reproducible.
- I wasn't able to reproduce this on https://send.dev.mozaws.net, but I will investigate it more on the following days.
- Here is a screen recording with the issue:

![send nan](https://user-images.githubusercontent.com/26000308/31727688-e1d5b702-b432-11e7-9267-9d8faa7a0abc.gif)

**Comment by dannycoates** [comment]
old (wontfix)
