### ISSUE TITLE
Cohort Tests for Firefox Promos

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#602]
# Hypothesis

Non Firefox Users who have successfully downloaded a file on Send may be interested in downloading Firefox.

# Proposed Experiment

We should implement a series of FF download links on the `/completed` page in Send with CTAs to download firefox. Each button would be shown to a cohort of non-FF users who reach this page and we would measure their efficacy against one another.

here's a terrible example of what one such promo might look like:
![screen shot 2017-10-18 at 4 00 04 pm](https://user-images.githubusercontent.com/3323249/31742947-faa7deb8-b41e-11e7-8ddb-13306be5856a.png)

The following event will need to be added when users click a promo
```
ec: recipient
ea: promo-clicked
```

Additionally, we should use the following experiment code:
```
xid: promo
xvar: control/promo-1/promo-2/promo-n
```

Branches will be evaluated by CTR, in addtion we can add utm params to each branch to see how actual downloads are affected.

## Cohort Size

We can run this experiment on 100% of users with cohort sizes determined by the number of promos we test.

**Comment by sevaan** [comment]
Initial Designs:

- [Home Page](https://mozilla.invisionapp.com/share/W7E3CXRCE#/259876096_Home_Page)
- [Download Page](https://mozilla.invisionapp.com/share/W7E3CXRCE#/259876095_Download_Page)

**Comment by ehuggett** [comment]
- Suggest Firefox as a solution to users with unsupported browsers?
- Suggest Firefox as an improvement to users with browsers depending upon webcrypto-liner? (i would expect the native webcrypto api to be noticeably faster for larger files, i don't have an unsupported browser to compare... )

**Comment by sevaan** [comment]
More details:

**Option A:** Subtle link in the page footer throughout the site. Can try orange (#ff9400) and blue as a secondary option (#0297F8)

**Option B:** Notification Bars. Bars slide in 1 second after the page loads. For downloaders, the bar slides in once the user clicks the download button. If user clicks the close button, the bar is dismissed and is never shown to the user again (drop a cookie?)

**Option C:** In-page element. Match the width of the Drag & Drop box. The element sits 10px below the file upload box on the home page. On the download page it sits 30px below the "Try Firefox Send" link.

[Spec available here.](https://mozilla.invisionapp.com/share/T5E4TW0M7)

> Suggest Firefox as a solution to users with unsupported browsers?

We already do this

> Suggest Firefox as an improvement to users with browsers depending upon webcrypto-liner?

Not sure I understand. Where would the promo show up?

**Comment by johngruen** [comment]
We're going to start with a test of options B1 and C1. Neither should be animated. Both should persist across all all screens. C1 should almost always be the bottom-most UI element (besides the footer, or list of stuff)

**Comment by johngruen** [comment]
`xvar: control/promo-b1/promo-c1`

we'll need a new event action:
`ea: close-promo`

**Comment by ehuggett** [comment]
> > Suggest Firefox as an improvement to users with browsers depending upon webcrypto-liner?

> Not sure I understand. Where would the promo show up?

At 'startup' the browser is tested for [AES-GCM support](https://github.com/mozilla/send/blob/acbf9fc32f21773a35ee9f5babc37e93f5c16c1c/app/main.js#L31), If the test fails, a [polyfill is loaded ](https://github.com/mozilla/send/blob/e56d92334f822cbe2f8108ecafc6bda38a9ad7f2/app/utils.js#L64-L65)(webcrypto-liner / asmcrypto.js #411 ). The general idea was as Firefox does not require asmcrypto for AES-GCM it would be faster than browsers that do for encrypt/decrypt, and this could be used as a technical argument in a Promo to entice some users to try Firefox (who may not respond to other types of argument).

**Comment by johngruen** [comment]
@johngruen will provide UTM params

**Comment by wresuolc** [comment]
utm_campaign=send-acquisition&utm_medium=referral&utm_source=send.firefox.com
