### ISSUE TITLE
[Enhancement] A warning message should be displayed when typing inside the "Password" field with "Caps Lock" functionality enabled.

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#604]
[Affected versions]:
- Firefox 56.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "Caps Lock" function is enabled.

[Steps to reproduce]:
1. Open the browser and navigate to "https://send.firefox.com" page.
2. Upload a file.
3. Click on the "Require a password to download this file" checkbox.
4. Type some characters in the Password field and observe the behavior.

[Expected result]:
- A warning message should be displayed when typing with "Caps Lock" functionality enabled.

[Actual results]:
- There is no warning displayed.

[Notes]:
- Here is a screen shot  example with a "Caps Lock" warning message:

![password warning](https://user-images.githubusercontent.com/26000308/31778914-8eea7ea6-b4fa-11e7-8c6b-0f5b62221253.png)

**Comment by ehuggett** [comment]
note: The password does not appear to be masked when the uploader sets it, but the downloader cannot see the password they are typing

It seems some browsers do implement this functionality (adding our own may give a redundant warning?), but Firefox has a 13 year old open bug for it https://bugzilla.mozilla.org/show_bug.cgi?id=259059

Working example (for me at least) of caps lock detection http://jsfiddle.net/cvg3bnzf/1/ (found via [stackoverflow](https://stackoverflow.com/questions/31792106/how-to-detect-caps-lock-state-on-page-load-that-is-not-on-keypress-with-javas#comment51514346_31792106))

**Comment by johngruen** [comment]
Let's stretch this...

**Comment by dannycoates** [comment]
wontfix, sorry
