### ISSUE TITLE
Text in fields should be middle-aligned

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#609]
The text in the URL and the password fields are slightly higher than the text in the attached labels:

![image](https://user-images.githubusercontent.com/473531/31898474-49c7b7d6-b7e7-11e7-98b0-80915d065860.png)

They should all be middle-aligned.

**Comment by tulikavijay** [comment]
I would like to work on this.

**Comment by tulikavijay** [comment]
I am new to open source so please guide me a bit. I want to ask, Where should I make changes?

**Comment by ericawright** [comment]
Hi @tulikavijay, Thank you!
When you open the project you can find the styling in `/assets/main.css`, this can likely be fixed with a few css changes. Once you have it committed, push it up to your fork of the project and make a pull request to us.
You can ping me or @dannycoates if you get stuck.

**Comment by SoftVision-CiprianMuresan** [comment]
@sevaan, the text in the box and the text in the label are now aligned with each other, but the text from the label was moved up a bit instead of moving the text from the box down.
Is this a suitable solution?

**Comment by sevaan** [comment]
@SoftVision-CiprianMuresan No, it should be the opposite: The label is too high, and the button is correct.

**Comment by anavgupta** [comment]
Hi @sevaan, I am looking to contribute to my first Open Source Project. Could you please point out the issue after the previous merge so that I can try to fix it.

**Comment by sevaan** [comment]
@anavgupta Great! Welcome aboard and thanks for contributing. Could you provide a screenshot of the issue after the previous merge (I'm not set up to build at the moment), and I'll give you the details on the fix.

**Comment by shikhar-scs** [comment]
@sevaan If this issue ( bringing the fields down ) isnt fixed till now , then may I do that and file a pr?

**Comment by bmintz** [comment]
@shikhar-scs of course!

**Comment by shikhar-scs** [comment]
Actually I'm stuck upon another issue in mozilla send so I wouldn't mind @himanish-star taking over this issue

**Comment by himanish-star** [comment]
@bmintz , I'll take over this issue
