### ISSUE TITLE
"Copy to clipboard" and "Add Password" buttons are wrongly rendered when changing the page zoom level

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#613]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net.
2. Upload a file and click on the "Require a password to download this file" checkbox.
3. Zoom in or zoom out the page.
4. Observe how the "Copy to clipboard" and "Add Password" buttons render.

[Expected result]:
- The buttons are correctly rendered.

[Actual result]:
- The buttons are wrongly rendered, depending on the performed action: zoom in (it exceeds the field's lines) or zoom out (the button is smaller than the field's line). 

[Notes]:
- This issue is not reproducible on Chrome.
- The issue is easy to observe on the following zoom levels:

**Windows**: 30%, 50%, 67%, 80%, 90%, 133%, 150%, 170%, 240%.
 
 **Mac**: 30%, 67%, 80%, 90%, 110%, 120%, 133%, 170%.
 
 **Ubuntu**: 30%, 50%, 67%, 80%, 110%, 133%, 150%, 170%, 240%.
 - Here is a screenshot with the issue, on different zoom levels:
 
![90zoomlevel](https://user-images.githubusercontent.com/31244235/31939704-1490c2b4-b8c4-11e7-81b1-9007f80ce08b.png)
![150zoomlevel](https://user-images.githubusercontent.com/31244235/31939709-17dbc5ae-b8c4-11e7-8272-d9c300c362a2.png)

**Comment by johngruen** [comment]
@ericawright "that should be fixed" in a PR

**Comment by Softvision-CristinaBadescu** [comment]
I can confirm that this issue is no longer reproducible on Send dev server, on latest Nightly build 58.0a1 (2017-10-30) using Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
