### ISSUE TITLE
[Dev] Upload/ Download does not work on Safari

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#616]
[Notes]:
- When trying to download a non-protected password file, the "Download" button is not actionable.
- When you have a password protected download file link, after clicking the "Unlock" button, the "Download" button redirects you to the "Something went wrong!" error page.

[Affected versions]:
- Safari 10.1.2 

[Affected Platforms]:
- All Mac

[Steps to reproduce]:
1. Navigate to https://send.dev.mozaws.net and upload a file.
2. Observe the behavior.

[Expected result]:
- The file is successfully uploaded. 

[Actual result]:
- "Something went wrong!" error page is displayed.

[Additional Notes]:
- This issue is not reproducible on stage and production server.
- Here is a screen recording of the issue: https://goo.gl/Nq6LdT

**Comment by tdtgit** [comment]
I think it relate to Safari 10.1.2 but I can't test on it.

With MacOS High Sierra, Safari 11.0 works well, both upload and download.

**Comment by Softvision-CristinaBadescu** [comment]
Hello,
I can confirm this issue is not reproducible on Mac 10.13, using Safari 11.0. 

This issue is reproducible on older Safari versions. For example, on Safari 9.1.2, after you click on "Select a file to upload" button and select a file, the content disappears and nothing happens. 

See a screen recording with the behavior here:
![send](https://user-images.githubusercontent.com/31244235/32179513-3fa1531e-bd98-11e7-990b-6bb6fd7e3d1a.gif)

**Comment by wresuolc** [comment]
Newer versions of Safari work, I'm going to close this.
