### ISSUE TITLE
Set a default MIME type in metadata?

### ISSUE THREAD

**Issue by ehuggett** [mozilla/send#620]
I'm not aware of any problems this is causing (noticed by chance), but if I upload a file that does not have an extension then the "type" field in the (encrypted) metadata is empty.

Server version: 5211339
Browser: Firefox 52.4.0 (64-bit) on Debian

https://github.com/mozilla/send/blob/52113395db7ffd8c2b25804908743d68bfe8f0e5/app/fileSender.js#L195-L197

I added `|| 'application/octet-stream'` to L197 in https://github.com/ehuggett/send/commit/58555a6b85f90d8fbff0781d6bda9b7d43cbe906, and when uploading files with names that do not have an extension this "default" MIME type was used instead

**Comment by johngruen** [comment]
@g-k do you have any thoughts on this? Would adding a default type cause any problems here?

**Comment by g-k** [comment]
@johngruen I can't think of any problems this would cause.  Apache and Nginx default to `application/octet-stream` so that's a good choice.
