### ISSUE TITLE
Some pages missing X-Content-Type-Options

### ISSUE THREAD

**Issue by wresuolc** [mozilla/send#629]
Some pages are missing `X-Content-Type-Options`.  Examples:

> 	https://send.firefox.com/robots.txt
> 	https://send.firefox.com/main.4e1aaca5.css
> 	https://send.firefox.com/favicon-32.4efdbe5a.png
> 	https://send.firefox.com/favicon-96.a2ce7c6e.png
>      https://send.firefox.com/favicon-128.58447464.png

But some pages have them, like https://send.firefox.com .  We should send `X-Content-Type-Options` everywhere.

**Comment by dannycoates** [comment]
fixed in 2e233da16d1b62b569e99802b494a3765ef04d64
