### ISSUE TITLE
Some pages missing Strict-Transport-Security header

### ISSUE THREAD

**Issue by wresuolc** [mozilla/send#630]
Some pages are missing Strict-Transport-Security like

> 	https://send.firefox.com/robots.txt
> 	https://send.firefox.com/main.4e1aaca5.css
> 	https://send.firefox.com/favicon-32.4efdbe5a.png
> 	https://send.firefox.com/favicon-96.a2ce7c6e.png
>      https://send.firefox.com/favicon-128.58447464.png

But pages like https://send.firefox.com has it.  We should send it everywhere.

**Comment by ehuggett** [comment]
#109 set HPKP, a related/complementary header, in the nginx config. This could be done for HSTS, I think having both configured in the same place might be convenient.

**Comment by wresuolc** [comment]
that'd make sense.  @relud what do you think?

**Comment by relud** [comment]
yeah, it could be added here: https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/send/puppet/modules/send/templates/http_send.conf.erb#L36

**Comment by ehuggett** [comment]
That link 404's for me, I'd guess its a private repository.

Stopping Send from setting the header can de done by deleting these lines
https://github.com/mozilla/send/blob/f48159dc0b11597d459d4ad8fb50648e14b561c8/server/routes/index.js#L19-L24

**Comment by dannycoates** [comment]
fixed in 2e233da16d1b62b569e99802b494a3765ef04d64
