### ISSUE TITLE
Download button does not work in FFx

### ISSUE THREAD

**Issue by piatra** [mozilla/send#636]
Clicking the download button doesn't seem to do anything in latest FFx 57/58.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/810040/32553894-6506e824-c498-11e7-8b24-43be007b611d.png">

**Comment by SoftVision-CosminMuntean** [comment]
I cannot reproduce this issue on latest Nightly (58.0a1) build and latest Dev Edition (58.0b1). The download button works as expected. Tested on Windows and also on Mac OS.

@piatra can you please retest this issue in Safe Mode? Probably there is an add-on that cause this.

**Comment by piatra** [comment]
Upload fails in FFx 57 Safe Mode.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/810040/32555900-3ba87190-c49e-11e7-93d2-2e949fe82965.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/810040/32555909-407a27f4-c49e-11e7-8830-2dc4252abc49.png">

Similar download error.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/810040/32556071-a962cf14-c49e-11e7-995b-cd19438e5248.png">
This is all in safe mode
<img width="314" alt="image" src="https://user-images.githubusercontent.com/810040/32556086-bdeca02c-c49e-11e7-8102-9b45970b8d9a.png">

**Comment by ehuggett** [comment]
note: there were no replies when started (the extra confirmation can't hurt, but this comment doesn't seem to contain any new information)

Using Firefox Developer Edition `58.0b1 (64-bit)` I was unable to reproduce this on send.firefox.com (837747f) or send.dev.mozaws.net (837747f). I was also unable to reproduce this with Firefox Nightly `58.0a1 (2017-11-08) (64-bit)`. Both were run on Debian 9

**Comment by SoftVision-CosminMuntean** [comment]
@piatra is this also reproducible on a new clean profile? Also, do you use a different version than en-US build? Or do you have any different languages set in about:preferences than default ones?

**Comment by piatra** [comment]
Not reproducible on clean profile. Will try to see if I can find the about:config combination that made this happen.

**Comment by piatra** [comment]
[1 means reject all third party cookies](http://searchfox.org/mozilla-central/source/browser/components/preferences/in-content/privacy.js#643)

**Comment by SoftVision-CosminMuntean** [comment]
I set the "network.cookie.cookieBehavior" pref to "1", but I cannot reproduce the issue. Tested also with a clean profile with the pref set to "1", but Send website works as expected.
