### ISSUE TITLE
Uploads and downloads fail for Accept-Language headers with quality scores

### ISSUE THREAD

**Issue by da2x** [mozilla/send#637]
1. Open about:config
2. Set `intl.accept_languages` to `en-US, en;q=0.8`
3. Try to upload or download a file from https://send.firefox.com 

Error in console from  app.c3b20d92.js:1:32367:
RangeError: invalid language tag: en;q=0.8 

ORIGINAL ISSUE:

TL;DR: Please also tell people about failed downloads, and not just silently log it.

Firefox nightly, 58.0a1 (2017-11-09) (64-bit), macOS 10.13

I’ve received a file and when I click on Download nothing happens. No error message is displayed and the file doesn’t start loading. If I try to open the same link in another browser, I’m told it has expired.

Multiple points:
* Send should have displayed some form of error message.
* Link shouldn’t have expired when the download couldn’t even be started.

Console log indicates that the Ghostery extension may be involved, but disabling it and trying again with a different download makes no difference. I’ve got a bunch of other extensions, but none of them seem to be active on this page. Even if an extension is to blame, Send should have detected that the download would fail and display an error message.

Looks like the failure was actually detected and logged somewhere (“Sending 'recipient' 'download-stopped': ”), but no feedback is hsown to the user.

Console log (file identifier removed, regenerated cid):

    Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://send.firefox.com”). Source: ;!function(){var t=0,e=function(t,e){ret....
    FILEIDENTIFIER:1
    Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://send.firefox.com https://code.cdn.mozilla.net”). Source: @media print {#ghostery-purple-box {disp....
    FILEIDENTIFIER:1
    Content Security Policy: The page’s settings blocked the loading of a resource at data:image/png;base64,iVBORw0KGgoAAAANSU... (“img-src https://send.firefox.com https://www.google-analytics.com”).
    Sending 'recipient' 'visit': 
    Object { an: "Firefox Send", aiid: "testpilot", aip: "1", cd19: "dev", ds: "web", t: "event", tid: "UA-35433268-78", v: "1", cid: "37B70FF3-08E5-467F-B912-80707B175C1D", ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0", … }
    vendor.2c317b61.js:1:83488
    RangeError: invalid language tag: nb;q=0.8
    app.c3b20d92.js:1:32367
    Sending 'recipient' 'download-started': 
    Object { an: "Firefox Send", aiid: "testpilot", aip: "1", cd19: "dev", ds: "web", t: "event", tid: "UA-35433268-78", v: "1", cid: "37B70FF3-08E5-467F-B912-80707B175C1D", ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0", … }
    vendor.2c317b61.js:1:83488
    Sending 'recipient' 'download-started': 
    Object { an: "Firefox Send", aiid: "testpilot", aip: "1", cd19: "dev", ds: "web", t: "event", tid: "UA-35433268-78", v: "1", cid: "4a9810b8-3101-46dc-97f6-7217e52d0f4d", ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0", … }
    vendor.2c317b61.js:1:83488
    Error: notfound
    Stack trace:
    value/</o.onload@https://send.firefox.com/app.c3b20d92.js:1:15831
    r@https://send.firefox.com/vendor.2c317b61.js:1:54418
    EventHandlerNonNull*O@https://send.firefox.com/vendor.2c317b61.js:1:52070
    t@https://send.firefox.com/vendor.2c317b61.js:1:60909
    _instrumentBreadcrumbs/</<@https://send.firefox.com/vendor.2c317b61.js:1:61528
    value/<@https://send.firefox.com/app.c3b20d92.js:1:16121
    O@https://send.firefox.com/vendor.2c317b61.js:1:163176
    value@https://send.firefox.com/app.c3b20d92.js:1:15596
    e/<@https://send.firefox.com/app.c3b20d92.js:1:16646
    r@https://send.firefox.com/vendor.2c317b61.js:1:166062
    c/<@https://send.firefox.com/vendor.2c317b61.js:1:167184
    u/</t[e]@https://send.firefox.com/vendor.2c317b61.js:1:166238
    r@https://send.firefox.com/app.c3b20d92.js:1:11525
    r/<@https://send.firefox.com/app.c3b20d92.js:1:11623
    I/</<@https://send.firefox.com/vendor.2c317b61.js:1:162054
    I/<@https://send.firefox.com/vendor.2c317b61.js:1:161924
    c@https://send.firefox.com/vendor.2c317b61.js:1:121514
    MutationCallback*g36u/t.exports@https://send.firefox.com/vendor.2c317b61.js:1:121657
    y9m4@https://send.firefox.com/vendor.2c317b61.js:1:161438
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    4M2W@https://send.firefox.com/vendor.2c317b61.js:1:12657
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    j1ja/<@https://send.firefox.com/vendor.2c317b61.js:1:125679
    j1ja@https://send.firefox.com/vendor.2c317b61.js:1:125587
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    [0]@https://send.firefox.com/vendor.2c317b61.js:1:5921
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    window.webpackJsonp@https://send.firefox.com/runtime.924d9fe6.js:1:418
    @https://send.firefox.com/vendor.2c317b61.js:1:1
    vendor.2c317b61.js:1:83488
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    Unhandled promise rejection 
    TypeError: e.transfer is null
    Stack trace:
    r/<@https://send.firefox.com/app.c3b20d92.js:1:64108
    r@https://send.firefox.com/vendor.2c317b61.js:1:166062
    c/<@https://send.firefox.com/vendor.2c317b61.js:1:167184
    u/</t[e]@https://send.firefox.com/vendor.2c317b61.js:1:166238
    r@https://send.firefox.com/app.c3b20d92.js:1:58680
    r/</<@https://send.firefox.com/app.c3b20d92.js:1:58830
    O@https://send.firefox.com/vendor.2c317b61.js:1:163176
    r/<@https://send.firefox.com/app.c3b20d92.js:1:58628
    sFnF/t.a/</<@https://send.firefox.com/app.c3b20d92.js:1:64887
    hRUR/r.prototype._emit@https://send.firefox.com/vendor.2c317b61.js:1:124679
    hRUR/r.prototype.emit@https://send.firefox.com/vendor.2c317b61.js:1:123180
    /7bh/r.prototype.route/</</o<@https://send.firefox.com/vendor.2c317b61.js:1:2004
    n@https://send.firefox.com/app.c3b20d92.js:1:24674
    EventHandlerNonNull*Ksyw/e.exports@https://send.firefox.com/app.c3b20d92.js:1:25272
    Du9L/e.exports@https://send.firefox.com/app.c3b20d92.js:1:19112
    /7bh/r.prototype.route/</<@https://send.firefox.com/vendor.2c317b61.js:1:1980
    n@https://send.firefox.com/vendor.2c317b61.js:1:84966
    /7bh/r.prototype.start@https://send.firefox.com/vendor.2c317b61.js:1:3087
    /7bh/r.prototype.mount/<@https://send.firefox.com/vendor.2c317b61.js:1:3464
    r@https://send.firefox.com/vendor.2c317b61.js:1:54418
    setTimeout handler*t/<@https://send.firefox.com/vendor.2c317b61.js:1:59430
    r@https://send.firefox.com/vendor.2c317b61.js:1:48281
    /7bh/r.prototype.mount@https://send.firefox.com/vendor.2c317b61.js:1:3426
    akvE@https://send.firefox.com/app.c3b20d92.js:1:44068
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    [1]@https://send.firefox.com/app.c3b20d92.js:1:7191
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    window.webpackJsonp@https://send.firefox.com/runtime.924d9fe6.js:1:418
    @https://send.firefox.com/app.c3b20d92.js:1:1
    vendor.2c317b61.js:1:83488
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    Sending 'recipient' 'exited': 
    Object { an: "Firefox Send", aiid: "testpilot", aip: "1", cd19: "dev", ds: "web", t: "event", tid: "UA-35433268-78", v: "1", cid: "37B70FF3-08E5-467F-B912-80707B175C1D", ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0", … }
    vendor.2c317b61.js:1:83488
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    Unhandled promise rejection 
    TypeError: e.transfer is null
    Stack trace:
    r/<@https://send.firefox.com/app.c3b20d92.js:1:64108
    r@https://send.firefox.com/vendor.2c317b61.js:1:166062
    c/<@https://send.firefox.com/vendor.2c317b61.js:1:167184
    u/</t[e]@https://send.firefox.com/vendor.2c317b61.js:1:166238
    r@https://send.firefox.com/app.c3b20d92.js:1:58680
    r/</<@https://send.firefox.com/app.c3b20d92.js:1:58830
    O@https://send.firefox.com/vendor.2c317b61.js:1:163176
    r/<@https://send.firefox.com/app.c3b20d92.js:1:58628
    sFnF/t.a/</<@https://send.firefox.com/app.c3b20d92.js:1:64887
    hRUR/r.prototype._emit@https://send.firefox.com/vendor.2c317b61.js:1:124679
    hRUR/r.prototype.emit@https://send.firefox.com/vendor.2c317b61.js:1:123180
    /7bh/r.prototype.route/</</o<@https://send.firefox.com/vendor.2c317b61.js:1:2004
    n@https://send.firefox.com/app.c3b20d92.js:1:24674
    EventHandlerNonNull*Ksyw/e.exports@https://send.firefox.com/app.c3b20d92.js:1:25272
    Du9L/e.exports@https://send.firefox.com/app.c3b20d92.js:1:19112
    /7bh/r.prototype.route/</<@https://send.firefox.com/vendor.2c317b61.js:1:1980
    n@https://send.firefox.com/vendor.2c317b61.js:1:84966
    /7bh/r.prototype.start@https://send.firefox.com/vendor.2c317b61.js:1:3087
    /7bh/r.prototype.mount/<@https://send.firefox.com/vendor.2c317b61.js:1:3464
    r@https://send.firefox.com/vendor.2c317b61.js:1:54418
    setTimeout handler*t/<@https://send.firefox.com/vendor.2c317b61.js:1:59430
    r@https://send.firefox.com/vendor.2c317b61.js:1:48281
    /7bh/r.prototype.mount@https://send.firefox.com/vendor.2c317b61.js:1:3426
    akvE@https://send.firefox.com/app.c3b20d92.js:1:44068
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    [1]@https://send.firefox.com/app.c3b20d92.js:1:7191
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    window.webpackJsonp@https://send.firefox.com/runtime.924d9fe6.js:1:418
    @https://send.firefox.com/app.c3b20d92.js:1:1
    vendor.2c317b61.js:1:83488
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    TypeError: e.transfer is null
    [Learn More]
    app.c3b20d92.js:1:59922
    TypeError: document.getElementById(...) is null
    Stack trace:
    m@https://send.firefox.com/app.c3b20d92.js:1:32821
    r/<@https://send.firefox.com/app.c3b20d92.js:1:64376
    r@https://send.firefox.com/vendor.2c317b61.js:1:166062
    c/<@https://send.firefox.com/vendor.2c317b61.js:1:167184
    u/</t[e]@https://send.firefox.com/vendor.2c317b61.js:1:166238
    r@https://send.firefox.com/app.c3b20d92.js:1:58680
    r/<@https://send.firefox.com/app.c3b20d92.js:1:58778
    I/</<@https://send.firefox.com/vendor.2c317b61.js:1:162054
    I/<@https://send.firefox.com/vendor.2c317b61.js:1:161924
    c@https://send.firefox.com/vendor.2c317b61.js:1:121514
    MutationCallback*g36u/t.exports@https://send.firefox.com/vendor.2c317b61.js:1:121657
    y9m4@https://send.firefox.com/vendor.2c317b61.js:1:161438
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    4M2W@https://send.firefox.com/vendor.2c317b61.js:1:12657
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    j1ja/<@https://send.firefox.com/vendor.2c317b61.js:1:125679
    j1ja@https://send.firefox.com/vendor.2c317b61.js:1:125587
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    [0]@https://send.firefox.com/vendor.2c317b61.js:1:5921
    n@https://send.firefox.com/runtime.924d9fe6.js:1:96
    window.webpackJsonp@https://send.firefox.com/runtime.924d9fe6.js:1:418
    @https://send.firefox.com/vendor.2c317b61.js:1:1
    vendor.2c317b61.js:1:83488
    Sending 'recipient' 'download-stopped': 
    Object { an: "Firefox Send", aiid: "testpilot", aip: "1", cd19: "dev", ds: "web", t: "event", tid: "UA-35433268-78", v: "1", cid: "37B70FF3-08E5-467F-B912-80707B175C1D", ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0", … }
    vendor.2c317b61.js:1:83488
    Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://send.firefox.com https://code.cdn.mozilla.net”). Source: @media print {#ghostery-purple-box {disp....
    FILEIDENTIFIER:1
    Sending 'recipient' 'exited': 
    Object { an: "Firefox Send", aiid: "testpilot", aip: "1", cd19: "dev", ds: "web", t: "event", tid: "UA-35433268-78", v: "1", cid: "4a9810b8-3101-46dc-97f6-7217e52d0f4d", ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0", … }

**Comment by ericawright** [comment]
Hi @da2x , 
"download-stopped" - is not necessarily an error message, we use that just to indicate it ending, whether through success or cancelling. 
 "e.transfer is null" seems to be the problem here.
I can't reproduce. Do you have any other steps to reproduce, or things you are suspicious of? And does this happen consistently?

**Comment by da2x** [comment]
@ericawright, I identified the issue and updated the original issue with steps to reproduce that works from a clean Firefox profile.

**Comment by da2x** [comment]
This is a duplicate of issue #586.

**Comment by dannycoates** [comment]
@da2x thanks for digging into this. 😀

#586 is the next thing on my list to work on so it should get fixed within then next week or so.

**Comment by da2x** [comment]
Much appreciated, @dannycoates. 👍

We Europeans do like our long and complex Accept-Language headers. For testing purposes, my exact request header is: `en-US, en, nb;q=0.8, no;q=0.8, da;q=0.6, sv;q=0.5, de;q=0.4, es;q=0.4` (en-US is often the first for compatibility with websites running old versions of IIS).
