### ISSUE TITLE
The link for download can be selected and copied while it's greyed out

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#638]
[Affected versions]:
- Firefox 56.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.dev.mozaws.net.
2. Upload a file and click on the "Require a password to download this file" checkbox.
3. Triple click on the greyed out link and observe the behavior.
**_Bonus:_**
4. Press "Ctrl"+"C" keys and go to an editor/empty input field.
5. Press "Ctrl"+"V" keys and observe what happens next.

[Expected result]:
3. The link is not selected.
5. The link cannot be selected, therefore cannot be copied and pasted.

[Actual result]:
3. The link is selected.
5. The link is pasted in the editor/empty input field.

[Notes]:
- "Copy to clipboard" button is also greyed out, but it's not actionable.
- This is also reproducible with "Cut" option, through both context menu and shortcuts.
- Please see the following screencast of the issue:

![greyed out link](https://user-images.githubusercontent.com/26000308/32617398-95d85b00-c57d-11e7-9f61-a08dfa984e14.gif)

**Comment by ehuggett** [comment]
Two approaches that don't quite work perfectly (only tested in firefox)

I tried applying `user-select: none` when waiting for a password https://github.com/ehuggett/send/commit/3835b407df4e2d373927e2a7c0afae2216f2880a
- if the text is already highlighted before ticking the box you can still copy the link (but you have to click on the input/url box first to show that its still selected).

adding/removing the disable attribute to the link in `togglePasswordInput()`, https://github.com/ehuggett/send/commit/eb057d215840ef8c8ffcfd8ad79abb3b404b6b75
- the input/link border changed to green while it was disabled, not looked into why
- I was not able to copy (context menu or ctrl+c), even if the text was highlighted beforehand 
- I could not see that the text was highlighted, even after clicking as with user-select:none
- I was able to click and drag to 'highlight' the link (blindly/without feedback until it started scrolling) and then click and drag the (not visibly) selected text, but i'm having trouble working out how to reproduce it reliably (perhaps its relevant if it has focus before its disabled?)

They might work together (after fixing the colour change) if someone wants to try, but I think there should be a better way of doing this

**Comment by johngruen** [comment]
We should just not grey the link out since the URL doesn't change.

**Comment by ehuggett** [comment]
Greying out the link would make a lot of sense if 'require a password' was set by default (globally or perhaps remembering a users preference?). If you don't think the greying out is currently essential, but you want to keep this possible, I would just add `user-select: none`
- If require a password is set by default, it will prevent copying the link until either the password is set or disabled (where this issue would matter most, it fixes/prevents it)
- If no password is required by default, the user can copy the link before clicking on the checkbox anyway so I would suggest this is "good enough" (partial fix)

notes:
- It was added in https://github.com/mozilla/send/issues/606
- the url doesn't change but you might not be able to set a password if its been used https://github.com/mozilla/send/issues/592 .

**Comment by dannycoates** [comment]
Disabling the copy originated when we weren't sure if the link would change once the password was added. Since the link stays the same there's no harm in copying at any time.
