### ISSUE TITLE
There is no way to dismiss the Firefox Promo

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#642]
[Notes]:
- The issue is reproducible on both variants.
- The issue is not reproducible on the Prod page.

[Affected versions]:
- All Browsers - Stage and Dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.stage.mozaws.net.
2. Observe Firefox Promo.

[Expected result]:
- An "x" button is displayed in the right part of the promo.

[Actual results]:
- There is no "x" button.

[Additional notes]:
- Here is a screen shot of the issue on Dev:
![image](https://user-images.githubusercontent.com/18304511/32839130-11665fa4-ca1c-11e7-8a52-35704c63e257.png)

**Comment by dannycoates** [comment]
We talked about this on slack and decided to go without the close button.
