### ISSUE TITLE
C variant of the Promo is not displayed on all Send screens 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#643]
[Notes]:
- The issue is also reproducible on https://send.stage.mozaws.net/error/404, https://send.stage.mozaws.net/error and Link expired pages.
- The issue is not reproducible on the download page and while downloading a file. 
- The B variant is displayed on all of the Send screens.
- The issue is not reproducible on the Prod page.

[Affected versions]:
- All Browsers - Stage and Dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the C variant of the promo.

[Steps to reproduce]:
1. Open the browser and navigate to https://send.stage.mozaws.net.
2. Upload a file and observe the page.
3. Observe the link copy page.

[Expected result]:
- Step 2&3: The promo is displayed in the page.

[Actual results]:
- Step 2&3: The promo is not displayed in the page.

[Additional notes]:
- Here is a screen recording of the issue on Stage:
![c variant not displayed](https://user-images.githubusercontent.com/18304511/32839943-ce96dc5a-ca1e-11e7-9c47-9b69ef258ad4.gif)

**Comment by dannycoates** [comment]
This is as _I_ intended it. @sevaan may have other ideas.

**Comment by sevaan** [comment]
Yes, this is intended. If a user does not stop to interact with the promo on the homepage, they're probably going to ignore it in subsequent steps where they are doing something. The notification bar is kind of out of the way so it can carry through, but this element is a bit more in-your-face so we can just use it on the home page and keep the layout clean afterwards.

**Comment by johngruen** [comment]
Closing due to @sevaan
