### ISSUE TITLE
Firefox icon from the Browser not supported page is not rendered correctly on Edge and Firefox

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#644]
[Notes]:
- In Edge's case, the promo is also affected by this issue.
- The issue is not reproducible on the Prod page.

[Affected versions]:
- Firefox 52 and under - Stage and Dev
- Edge - Stage and Dev

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open an unsupported version of Firefox or Edge and navigate to https://send.stage.mozaws.net.
2. Observe the Firefox icon in the Download button.

[Expected result]:
- The icon is correctly rendered.

[Actual results]:
- The icon is black.

[Additional notes]:
- Here is a screen shot of the issue on Stage:
![image](https://user-images.githubusercontent.com/18304511/32842479-de2fa410-ca25-11e7-9c4e-5b64380cead6.png)

**Comment by dannycoates** [comment]
Same on firefox. The new logo svg has some style attributes that I didn't notice, which our CSP rules don't like. I'd prefer to allow inline styles in our CSP.
