### ISSUE TITLE
C variant of the promo is not in a fixed position in the page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#646]
[Notes]:
- On some browsers (Opera) the footer section is also moved.
- The issue is not reproducible on B variant.
- The issue is not reproducible on the Prod page.

[Affected versions]:
- All Browsers - Stage and Dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the C variant of the promo.

[Steps to reproduce]:
1. Open the browser and navigate to https://send.stage.mozaws.net.
2. Drag a file on the Drop area and observe the promo.

[Expected result]:
- The promo is fixed in the page.

[Actual results]:
- The promo is moved up as the Drop area is hovered.

[Additional notes]:
- Here is a screen shot of the issue on Stage:
![c variant moving the page](https://user-images.githubusercontent.com/18304511/32900485-40842c00-caf6-11e7-9d33-933a9800fe1c.gif)

**Comment by sevaan** [comment]
Yeah, that looks a bit broken and will be unavoidable for anyone seeing this variation.

**Comment by dannycoates** [comment]
not *unavoidable* @sevaan jeez 😉 

Only for the drag-droppers, not the button clickers... anyway I fixed it.

**Comment by dannycoates** [comment]
Looks like I forgot the issue number in the commit message... fixed in https://github.com/mozilla/send/commit/d78fcd3721df7cf114ba255513ea8f79af3d9864
