### ISSUE TITLE
Add banner color A/B test

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#651]
@sevaan we want to compare the grey top bar against a more colorful option...what colors should we use?

**Comment by sevaan** [comment]
Let's go with Photon blue: #0098F7 with white text.

![image](https://user-images.githubusercontent.com/473531/33330610-4b921c98-d42d-11e7-93cf-ed9aced676a9.png)

**Comment by dannycoates** [comment]
added b2c1daa6c7cd1ba3584eed29352631df62032a1c
