### ISSUE TITLE
The share link field is wrongly active when the "Require a password" checkbox is selected

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#659]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a file uploaded to https://send.stage.mozaws.net/.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to the Share file page.
2. Select the "Require a password" checkbox.
3. Observe the share link field.

[Expected result]:
- The share link field is inactive: the "Copy to clipboard" button is inactionable and has a lighter blue color.

[Actual result]:
- The share link field and "Copy to clipboard" button remain unchanged.

[Notes]:
- This issue is also reproducible on https://send.firefox.com/ and https://send.dev.mozaws.net.
- Here is a screen recording of the issue:
![link field active](https://user-images.githubusercontent.com/31244235/33725704-954d8d18-db7b-11e7-8180-802e531fad41.gif)

**Comment by dannycoates** [comment]
Since the link doesn't change by adding a password we decided it's ok to keep it enabled. It's working as we now intend it to.
