### ISSUE TITLE
The upload/download progress bar does not update itself while in a background tab

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#662]
[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a medium to large file (>100 MB).
3. Switch to a different tab and wait for the download to reach about 50%.
4. Switch back and observe the upload progress bar.

[Expected result]:
- The progress bar is at 50% when the tab is switched.

[Actual results]:
- The progress bar quickly goes from close to 0% to 50%.

[Notes]:
- The issue is also reproducible when downloading a file.
- Here is a screen recording with the issue:
![progress bar does not update in background](https://user-images.githubusercontent.com/18304511/33767754-c57fe07a-dc2b-11e7-9d01-249d52714f34.gif)

**Comment by dannycoates** [comment]
old / wontfix
