### ISSUE TITLE
Password is only set on the 2nd attempt if the file was already downloaded once

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#664]
[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a medium to large file (>100 MB) and set it to expire after at least 2 downloads.
3. Download the file on a different computer once.
4. Check the password checkbox and write a password.
5. Click "Add password" and observe the behavior.

[Expected result]:
- The password is set.

[Actual results]:
- The password checkbox is unchecked and the password is not set.

[Notes]:
- Here is a screen recording with the issue:
![password only set the second time if the file was downloaded once](https://user-images.githubusercontent.com/18304511/33767992-fdcefd84-dc2c-11e7-8481-955d73e7b612.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on latest Send 2.2.1 version.
