### ISSUE TITLE
Password should be hidden while typing

### ISSUE THREAD

**Issue by sukeesh** [mozilla/send#670]
After uploading a file, Password while typing is not hidden.

**Comment by johngruen** [comment]
...arguably :)

**Comment by sukeesh** [comment]
Hi @johngruen, Can I work on this issue?

**Comment by shikhar-scs** [comment]
As the previous pr has been closed, I'll soon post one to correct the issue

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible. Passwords are now hidden when typed and hidden after being set.

**Comment by Radhraj** [comment]
@SoftVision-CiprianMuresan Able to reproduce this on Firefox version 58.0.
The password entered does not seemed to be masked.

**Comment by shikhar-scs** [comment]
@Radhraj  could you please post a gif, screenshot of the same ?

**Comment by dannycoates** [comment]
@Radhraj this is not deployed to production yet. It will be in the next release.
