### ISSUE TITLE
Download not working on Safari for iOS

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#674]
![img_5456](https://user-images.githubusercontent.com/3323249/34161814-0bee7a22-e4d2-11e7-80fc-5fbe2cabd2e8.png)

**Comment by johngruen** [comment]
@dannycoates the problem here is that the failure happens AFTER download. If we can't support Safari for iOS, we should display the warning before we download and possibly trigger a blocking prompt for users to download FXiOS (for which downloads work).

@sevaan what do you think?

**Comment by dannycoates** [comment]
I think this is dependent on the file type. If it's something iOS knows what to do with, like an image, it should work, though I haven't done extensive testing. I don't imagine Firefox for iOS would be able to do any better than Safari

**Comment by johngruen** [comment]
Looks like this needs investigation :(

**Comment by johngruen** [comment]
Oh yeah, i investigated this further, but somehow never documented my findings.

Basically i can still repro this for files you'd think would open (gifs, jpgs etc)

Here's what i'm seeing

![img_6212](https://user-images.githubusercontent.com/3323249/36212132-7fc35672-11a3-11e8-8f9b-d600c5919c43.PNG)

BTW, this was for a .txt file that correctly rendered in fxios:
![img_6214](https://user-images.githubusercontent.com/3323249/36212176-973d3eda-11a3-11e8-9b07-cba6cc1f71de.PNG)

**Comment by johngruen** [comment]
This might be fixed on @dannycoates machine

**Comment by dannycoates** [comment]
calling this fixed as of c0ad7635f2864533226bb13a74e0cc0962b64b53
