### ISSUE TITLE
Download Firefox button fonts look wrong in Edge

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#676]
Should be Sans Serif

<img width="1083" alt="screen shot 2017-12-19 at 3 58 21 pm" src="https://user-images.githubusercontent.com/3323249/34162890-8fe82866-e4d5-11e7-8ada-ec563a19382b.png">

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Dev server using Edge.
