### ISSUE TITLE
The string 'Firefox Send' is hardcoded everywhere

### ISSUE THREAD

**Issue by bmintz** [mozilla/send#689]
I'm trying to make my own fork of Firefox Send that's more privacy/anonymity oriented (ie no Google Analytics, no "Experiments" code, etc). I also wanted to change the title of it. I'd think that just changing state.title to `SendCrew` would be enough, but alas, not enough stuff uses it.

Even though I removed metrics, I still thought you'd like to know. Also this one would be a real pain to change cause it has no access to server/state.js or server/config.js.
https://github.com/mozilla/send/blob/46a3933dbba92a0fb2c42c0f6faabb72cc3f3fb4/app/metrics.js#L11-L15
https://github.com/mozilla/send/blob/46a3933dbba92a0fb2c42c0f6faabb72cc3f3fb4/app/fileManager.js#L85-L92
https://github.com/mozilla/send/blob/46a3933dbba92a0fb2c42c0f6faabb72cc3f3fb4/app/routes/index.js#L16-L18

**Comment by wresuolc** [comment]
Thanks for the bug, but I'm going to close this -- that's the name of the product and since it's an experiment we're keeping the code simple and trying to move quickly on features.  Thanks!
