### ISSUE TITLE
Used memory takes too long until it's released, if an upload is cancelled before it reaches 5% 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#692]
[Notes]:
- This issue is not reproducible on Mac OS.
- The used memory is released after a few seconds if the Send tab is closed.
- Depending on your system, the issue can be reproducible even when you cancel the upload after 5%.

[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- The Task Manager/System Monitor is opened. 

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.firefox.com/" page.
2. Upload a large file >1 GB.
3. Wait until the upload reaches 1% and click the "Cancel" button.
4. Observe the Firefox memory usage in Task Manager over a couple of minutes.

[Expected result]:
- The the Firefox memory is released after a few seconds.

[Actual results]:
- The the Firefox memory is only released after ~10 minutes.

[Additional Notes]:
- Here is a screen recording with the issue: https://goo.gl/BjJcmC

**Comment by wresuolc** [comment]
We think this is just firefox garbage collection doing its thing.  If your computer is short on memory and it's not releasing, that's more concerning, but periodically cleaning up seems right.

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the firefox garbage collection is not working properly in Firefox 57 release. If an upload is cancelled before it reaches 5%, than the Firefox memory is only released if the page is closed or refreshed.
But, this issue is not reproducible on Beta 58 and latest Nightly 59.0a1 build. The memory is released in a few seconds after the upload is cancelled. So, probably this is a Firefox issue and it will be solved in the next release.

However, I will retest this after Firefox 58 will be released.
