### ISSUE TITLE
Protocol not taken into account in resulting URL

### ISSUE THREAD

**Issue by TwizzyDizzy** [mozilla/send#696]
Hi folks,

I use my send-instance via reverse-proxy in apache (proxying to 127.0.0.1:PORT). When uploading a file over https://my.send.instance, the resulting URL that is schon after that uses `http` as protocol.

This happens despite having set the `X-Forwarded-Proto "https"` header.

I would vote for the ability of send to take into account
* the HTTPS header
* or the X-Forwarded-Proto header in case of proxies

... and adjust the resulting URL accordingly.

Cheers
Thomas

![screen1](https://user-images.githubusercontent.com/179595/34672460-cae9455e-f47e-11e7-9850-35328481ad0d.png)

![screen2](https://user-images.githubusercontent.com/179595/34672465-ce5619a6-f47e-11e7-8f6e-855d0f233431.png)

**Comment by dannycoates** [comment]
Setting the `NODE_ENV` environment variable to `production` will force https

**Comment by TwizzyDizzy** [comment]
Argh... you're right, I could have looked that up. Sorry for that!

Cheers
Thomas
