### ISSUE TITLE
Gradient Firefox promotion banner test

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#697]
As discussed in our last Send meeting, the Grey Firefox promotion banner is performing better than the blue. Now we'd like to try some gradients to see if they are more or less noticeable.

[Mocks](https://mozilla.invisionapp.com/share/W7E3CXRCE#/272542748_Send_Promo_Gradients)

CSS for Orange-Pink: `background-image: linear-gradient(-180deg, #FF9400 0%, #FF1AD9 94%);`
CSS for Blue-Teal: `background-image: linear-gradient(-180deg, #45A1FF 0%, #00FEFF 94%);`

[White Firefox logo asset (Under Branding section)](https://design.firefox.com/icons/viewer/)

**Comment by shikhar-scs** [comment]
@sevaan The purpose of this issue is to generate different gradients and check whether they are more or less noticeable right ?

**Comment by sevaan** [comment]
Yes. Just want to compare the efficacy of this visual compared to say our regular grey bar.

**Comment by shikhar-scs** [comment]
Ok, I'll try over some designs and post the here
