### ISSUE TITLE
The Delete dialog from the Link copy page is not correctly displayed in mobile view

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#699]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Platforms

[Steps to reproduce]:
1. Open the browser and resize it's width to the minimum.
2. Navigate to https://send.dev.mozaws.net and upload a file.
3. Click the delete button and observe the dialog.

[Expected result]:
- The dialog is fully displayed.

[Actual results]:
- The left side of the dialog box is cut off.

[Notes]:
- Here is a screen shot of the issue:
![image](https://user-images.githubusercontent.com/18304511/34766829-66628722-f5fe-11e7-90bc-7bc9f0058866.png)

**Comment by shikhar-scs** [comment]
I'm working on it :+1:

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and it seems that is reproducible on latest version of Send (2.5.3) using latest Firefox (59.0.3) release and latest Nightly (62.0a1) build . Tested on Windows 7 x64, 10 x64, Mac 10.13 and Arch Linux.

**Comment by wresuolc** [comment]
This will be obsoleted by the new UI

**Comment by dannycoates** [comment]
old (wontfix)
