### ISSUE TITLE
"Download Firefox" banner is wrongly displayed on the homepage after using Responsive Design Mode

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#700]
[Notes]:
- The banner persists after exiting Responsive Design Mode, after the browser is restarted and will still appear if you visit the page in a different tab.
- The issue is also reproducible on Dev and Stage.

[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://send.firefox.com.
2. Press Ctrl+Shift+M (Alt+CMD+M) and select a device.
3. Observe the top part of the page.

[Expected result]:
- The page is correctly displayed. 

[Actual results]:
- The "Download Firefox" banner is displayed.

[Notes]:
- Here is a screen shot of the issue:
![download firefox banner displayed on firefox](https://user-images.githubusercontent.com/18304511/34773641-1e8ea1ee-f615-11e7-9dc7-8f975263a0bf.gif)

**Comment by dannycoates** [comment]
The experiment metadata is stored in `localStorage` so once you're in, you're in. The thing that's triggering it here is that changing the device in RDM changes the user agent.

I'd say this is a good find but a wontfix.
