### ISSUE TITLE
The revealed password font is too small

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#703]
[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to https://send.dev.mozaws.net/.
2. Upload a file and select the "Require a password" checkbox.
3. Type something in the password field and click "Add password" button.
4. Hover over the masked password and observe its font.

[Expected result]:
- The revealed password font is big enough to be visible from a normal distance.

[Actual result]:
- The revealed password font is too small.

[Notes]:
- The password seems to be bold on Mac 10.12.6 and Linux 4.12, but not on Windows 10 x64.
- Here is a screen recording of the issue:
![wrong font displayed for password](https://user-images.githubusercontent.com/31244235/34984523-e3468bca-fab9-11e7-81cf-dce516ce11d5.gif)

**Comment by shikhar-scs** [comment]
@Softvision-CristinaBadescu This functionality of masking the password was added by me in #686 .
I had ensured that the font remains the same (you can have a look at the gif files attached there).

However, later [here](https://github.com/mozilla/send/commit/1741b1c6866496e02c8ec4ccf11290e3ca069dc8#diff-46d5644ae6b8906c8a35d46be22427f9) it was chaged to `monospaceFont` by dannycoates( the main member ) himself. So, I guess this should not be an issue.

**Comment by dannycoates** [comment]
I did change the password font on purpose so that the masked password and revealed password take up the same amount of space. It does look a bit to small now so I can bump up the size, but I think it should remain monospaced.

**Comment by Softvision-CristinaBadescu** [comment]
@shikhar-scs, @dannycoates I'm sorry, somehow I've missed that.

I agree with Danny that we should make the revealed password font bigger so it will be more visible. Considering this, I'm going to edit this issue so that it suits our situation.
