### ISSUE TITLE
Metadata encryption static initialization vector possible security vulnerability?

### ISSUE THREAD

**Issue by lifenautjoe** [mozilla/send#706]
I've noticed [here](https://github.com/mozilla/send/blob/master/app/fileSender.js#L246) that the initialization vector for the metadata encryption is set to an Array of 12 zero's. 

Given that ([from Wikipedia](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Initialization_vector_.28IV.29))

> An initialization vector has different security requirements than a key, so the IV usually does not need to be secret. However, in most cases, it is important that an initialization vector is never reused under the same key. For CBC and CFB, reusing an IV leaks some information about the first block of plaintext, and about any common prefix shared by the two messages.

Can this in some way pose a risk to the encryption of the data? 

I do understand that the same key is never reused, so was this the reason why it was chosen to be static? That in order for it to pose a security risk the attacker would need 2 metadata files encrypted with the same key? (therefore getRandomValues spitting the same numbers twice which is highly unlikely )

Thanks!

**Comment by ehuggett** [comment]
> I do understand that the same key is never reused, so was this the reason why it was chosen to be static?

Yes it would appear so, it also piqued my interest when I first saw it and you seem to have come to the same conclusion; that it's not a problem as its still a unique value. 

It also conveniently avoids the need to submit the nonce to the server, have the server store it (etc).

> That in order for it to pose a security risk the attacker would need 2 metadata files encrypted with the same key?

Yes, An attacker would need two different messages encrypted with the same key and nonce.

> (therefore getRandomValues spitting the same numbers twice which is highly unlikely )

about 1 in 340282366920938463463374607431768211456 (the secretKey from which it is derived is a16 bytes / 128 bit value) so this is extremely unlikely to happen.

Does this help address your concerns?

**Comment by lifenautjoe** [comment]
Yes it does! 

Thanks! Closing issue now.
