### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#708]

**Comment by apoorvaagupta** [comment]
Hello, can I give this issue a try if no one is working on it?

**Comment by dannycoates** [comment]
Hi, @apoorvaagupta, thanks for your interest. Issues that have an assignee are usually being actively worked on already. As a new contributor the best issues to look for are ones labeled "good first issue". Unfortunately, we don't really have any of those right now. We may have some in the near future. It's ok to work on other issues, but they often require additional information / decisions before they're ready for implementation.

**Comment by apoorvaagupta** [comment]
thanks @dannycoates I will work on other issues!

**Comment by dannycoates** [comment]
done in #760
