### ISSUE TITLE
The download limits menu/the password filed is wrongly dismissed, if you quickly open the download limits menu or set a password

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#723]
[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a any file.
3. After the page is loaded, quickly click the "1 download" button link.
4. Observe the behavior.

[Expected result]:
- The download limits menu remains opened.

[Actual results]:
- After a fraction of a second the download limits menu is dismissed.

[Additional Notes]:
- The same behavior can be observe if you quickly type a password after the "Copy link" page was loaded.
- The issue is more visible on Windows.
- Here is a screen recording with the issue: https://goo.gl/FQv79r

**Comment by dannycoates** [comment]
old (wontfix)
