### ISSUE TITLE
The uploaded files wrongly disappear if you hold "F5" key on Send homepage for a few seconds

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#725]
[Notes]:
- I am not sure, but probably is related to issue: #724 

[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have multiple files uploaded.

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.dev.mozaws.net/" page.
2. Hold "F5" key for a few seconds.
3. Observe the file info table.

[Expected result]:
- The uploaded files are correctly displayed.

[Actual results]:
- The uploaded files disappear and are no longer displayed.

[Additional Notes]:
- This issue is also reproducible on production server.
- Here is a screenshot with browser console errors:
![hold f5 key](https://user-images.githubusercontent.com/19226534/35285780-f3644260-0066-11e8-8754-92565f1b7a28.png)
- Here is a screen recording with the issue:
![uplaoded files disappear](https://user-images.githubusercontent.com/19226534/35285795-f8771318-0066-11e8-9cf5-538c5a87d6dc.gif)

**Comment by dannycoates** [comment]
I can't reproduce this on dev after #737, so fixed, maybe?

**Comment by SoftVision-CosminMuntean** [comment]
Indeed the issue is no longer reproducible on latest Send dev version. So probably was fixed with #724.
