### ISSUE TITLE
feature request: upload files from the console

### ISSUE THREAD

**Issue by ghost** [mozilla/send#727]
Hi!
https://transfer.sh/ has the ability to upload files from the console. For example using curl:
`$ curl --upload-file ./hello.txt https://transfer.sh/hello.txt`

Is this possible to do the same thing with firefox send?

**Comment by ehuggett** [comment]
- I wrote a python client https://github.com/ehuggett/send-cli
- #737 seems(?) to be moving everything that would be important for a nodejs cli client into app/api.js

Files are encrypted client-side, so curl cannot be used as in your example (but could be used in a script to upload the file after it has been encrypted).
