### ISSUE TITLE
Feat: Add ability to change the expiration time.

### ISSUE THREAD

**Issue by publicarray** [mozilla/send#728]
When sharing files due to time-zones and busy life styles. It would be beneficial to allow us to extend the expiration time up-to a few days (say 3 or 5 ?). 

My specific use case was to share a coredump for a bug report on GitHub (19mb file) but due to the nature on open-source communities it might take a few days before someone is able to download the file.

**Comment by shikhar-scs** [comment]
Either we can change it and extend it to a default of 3/4 days OR maybe keep it on the lines of `download - limits`.
The default time limit can be changed here
https://github.com/mozilla/send/blob/91dc3aa5d2c8ac04c45cd1b3ccdc294c7fbebee2/server/config.js#L53-L57

OR again, we can build it on the lines of `download limits`

**Comment by publicarray** [comment]
I'm not sure what you are telling me. But on https://send.firefox.com/ where the text reads 

> The link to your file will expire after 1 download or 24 hours.

the "1 download" is a configurable drop-down. Why not do the same for the expiration time of the "24 hours"?

**Comment by shikhar-scs** [comment]
Yeah @publicarray 
> we can build it on the lines of download limits

meant 

> the "1 download" is a configurable drop-down. Why not do the same for the expiration time of the "24 hours"?

the other method I proposed was changing the time limit of `86400` seconds which is basically no. of seconds in a day :smile:

**Comment by maxschons** [comment]
+1

**Comment by filips123** [comment]
Please also add support to change settings of file (no. of downloads, time, password...) after uploading file.
Also add support to set download and time limit to infinity.

**Comment by chrisbra** [comment]
I would also welcome such a change.

**Comment by timvisee** [comment]
I do think 24 hours is a nice default, although making this changeable after uploading would be a nice addition yeah. 

Such a change may be implemented though file parameters, using the `/api/params` endpoint, in the same way a download limit can be set.

I don't think such a change would be hard to complement. I guess we've to wait for a response from a Mozilla developer, to confirm a feature like this would be allowed.

**Comment by dannycoates** [comment]
We will likely be adding more options for expiration this summer. It's currently in the project plan. We've temporarily slowed development for the moment but expect to resume full-time in June.

**Comment by chrisbra** [comment]
great to hear. Looking forward :)

**Comment by dannycoates** [comment]
done in vnext

**Comment by filips123** [comment]
@dannycoates When will this be available on website?
