### ISSUE TITLE
Password accpets no values

### ISSUE THREAD

**Issue by Radhraj** [mozilla/send#730]
Steps:
Go to https://send.firefox.com
Click on Select File to Upload
Upload any File
Click on Require a password to download this file
Enter white space to the Password Textbox
Click on Add Password

Actual Result:
White spaces must ideally not be allowed in Password field.

Expected Result:
The password gets added.

![passwordacceptsnovalues](https://user-images.githubusercontent.com/30893077/35373479-947483b4-01c4-11e8-87f2-5bb48daf8140.png)
![passwordacceptsnovalues1](https://user-images.githubusercontent.com/30893077/35373480-94b457dc-01c4-11e8-93ba-5b55548338f3.png)
![passwordacceptsnovalues2](https://user-images.githubusercontent.com/30893077/35373481-94ee450a-01c4-11e8-8796-804d5fca5a78.png)

**Comment by dannycoates** [comment]
whitespace is a valid password character
