### ISSUE TITLE
File Size shown different, if the file is too small.

### ISSUE THREAD

**Issue by Radhraj** [mozilla/send#731]
Steps:
Go to https://send.firefox.com
Click on Select File to Upload
Upload any small file (Txt/Word)
Check the size displayed on Upload

Version:
Firefox 58.0

Actual Result:

The size of the file displayed on upload must match with actual size

Expected Results:
For a very small file (Say 4B), the size is displayed incorrect.On download the actual size does not match with the one that was displayed on the UI.
In the below GIF for a 4B file the size is shown to around 219B

![filesizeshownincorrect1](https://user-images.githubusercontent.com/30893077/35375283-7f606bca-01cc-11e8-87f5-a43bbd5052e9.png)

![filesizedifferentonui](https://user-images.githubusercontent.com/30893077/35386425-0357315a-01f2-11e8-9dd3-e7a131c2f032.gif)

**Comment by himanish-star** [comment]
Can I take over this issue ?

**Comment by dannycoates** [comment]
The encrypted file is a few bytes larger than the original so for very small files there's a visible difference in the unecrypted size vs encrypted. I don't care if this doesn't get fixed.

**Comment by wresuolc** [comment]
Thanks danny
