### ISSUE TITLE
No error thrown if Empty file uploaded

### ISSUE THREAD

**Issue by Radhraj** [mozilla/send#732]
Steps:
Go to https://send.firefox.com
Click on Select File to Upload
Upload a empty file

Versions:
Firefox 58.0

Actual Result:
If empty files not allowed, then an appropriate error message must be displayed.

Expected Result:
No error is thrown.Nothing seems to happen on uploading the empty file.

**Comment by pdehaan** [comment]
Possibly related: #383; "Upload an empty file returns incorrect message"

**Comment by shikhar-scs** [comment]
That had been discussed once with @dannycoates but it is supposed to stay as it is as of now.
Visit [this](https://github.com/mozilla/send/pull/695#issuecomment-356038401) to verify. Also read the following comment.

**Comment by dannycoates** [comment]
Thanks for the report. I don't think we need a specific error message for this. Empty files is not a common problem that most people face and the action of doing nothing when it does happen is not unreasonable.
