### ISSUE TITLE
Download encrypted file displayed on downloading the file, and changes to Download "Filename" within seconds.

### ISSUE THREAD

**Issue by Radhraj** [mozilla/send#733]
Steps:
Go to https://send.firefox.com
Click on Select File to Upload
Upload a file.
Copy the URL
Hit the URL(Another browser)

Version:
Firefox 58.0.0

Expected Result:
The UI must display title as "Download Filename"

Actual Result:
The UI displays Download Encrypted File.
The title displayed above also changes back to Download File within few seconds.

![downloadencryptedfile_ondownload](https://user-images.githubusercontent.com/30893077/35381689-1846a492-01e3-11e8-9297-2f1db117697c.png)

**Comment by himanish-star** [comment]
@dannycoates , Can I fix this issue?

**Comment by dannycoates** [comment]
This is a side effect of the filename being encrypted. It gets fetched separately from the page and is then decrypted. While that's happening this generic message is shown.

There's a couple things I think we can do to make this better:

- change the message from "Dowload Encrypted File" to something else. @sevaan thoughts?
- don't show the download button until the filename is loaded

**Comment by dannycoates** [comment]
@himanish-star you can work on the download button part if you like

**Comment by himanish-star** [comment]
Thanks, I'll definitely do so

**Comment by wresuolc** [comment]
Sevaan is going to provide UX support here

**Comment by sevaan** [comment]
The "Download Encrypted File" is only up there for a split-second...plus, I noticed an additional issue, where the flying document image disappears and the word "Download" is flashed on the screen ([video](https://cl.ly/0u0X2E2a412Q)):

<img width="596" alt="image" src="https://user-images.githubusercontent.com/473531/35647256-f0e516d8-069f-11e8-8d3d-fd0a141541d1.png">

It's a lot of distracting movement. I think all of this could best be sorted by not showing any page content except an animated spinner/loader until the file name is fetched, then display everything at once. The footer and header and page background should still be shown, this is a quick loader for the content.

[Maybe one of these](http://samherbert.net/svg-loaders/)...I kind of like the second from the left on the bottom row (tailspin.svg). Or the far right in the middle (puff.svg). I think #000000 and centered in the page, right above where the flying envelope graphic is.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/473531/35648466-d825c8f0-06a3-11e8-9118-f5b69d6af537.png">

**Comment by sevaan** [comment]
Current implementation works fine for when there is a password.

**Comment by dannycoates** [comment]
fixed in 232911f72539a98001e0740fe687c3dc84960672 without spinner
