### ISSUE TITLE
Link gets expired after cancelling the current download.

### ISSUE THREAD

**Issue by Radhraj** [mozilla/send#734]
Steps:
Go to https://send.firefox.com
Click on Select File to Upload
Upload a file.
Copy the URL
Hit the Link
Click on Download
Cancel the option for saving the file
Hit the Link again

Expected Result:
Assuming that the number is set as 1 download/24 hours, if the download was cancelled, then on hitting the link again,the download option must be available for the second time , as the first time the file was not downloaded.

Actual Result:
The link gets expired as soon as the user clicks on Download , even if he cancels the download to his/her  local system later.

![linkexpiredifdownloadcancelled](https://user-images.githubusercontent.com/30893077/35386046-8550e068-01f0-11e8-9eea-fb88a671ee78.gif)

**Comment by himanish-star** [comment]
@dannycoates ,do you want to fix this issue? If yes, can I fix this ?
