### ISSUE TITLE
Make basic Send webextension

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#742]
This would basically just be a browserAction to start that would direct users to the Send site.
We would also need promo UI to let people know this exists and probably this UI should be different for Chrome and Firefox versions. 

Open questions:
1. is there a moz account in the chrome add-on store/ chrome add-on review and signing?
2. what will the promo look like for each?

**Comment by brainlulz** [comment]
The extension shoudn't do more than just redirect ? I imagine more than on clicking on the extension, it redirect you to the website but open the `upload file` modal ? So it requires less actions for the user ? However the user can't directly drag/drop his file on Send.

**Comment by dannycoates** [comment]
Now is probably not be a good time to start working this. We've got a bunch of new UI design work coming up that will probably affect our plans for an extension. https://mozilla.invisionapp.com/share/KTIN82A9SFR#/screens/297026849

**Comment by hellosct1** [comment]
Hi
I realized the web extension that is available 
https://addons.mozilla.org/fr/firefox/addon/send-to-fx/

best regard

Christophe
