### ISSUE TITLE
On download page the typing input cursor should already be in the password box

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#745]
STR:

1. Upload a file
2. Set a password. Notice when you check the box to add a password the typing input cursor is already in the box.
3. Copy the url and paste into another browser

The user has to manually mouse to the input form and click to start typing. Let's save them the step.

**Comment by dannycoates** [comment]
I added `autofocus` to the input element which seems to work on firefox but isn't on chrome for some reason.
