### ISSUE TITLE
Uploaded percentage using Latin digits instead of localized digits for Persian

### ISSUE THREAD

**Issue by afarsi** [mozilla/send#747]
Hi there.
This bug, is in countinue of https://bugzilla.mozilla.org/show_bug.cgi?id=1201232
If you reead Comment 44 on mentoined bug, you will understand what happened?

I attached the screen shots of Firefox Send that shows English Digits in Uploaded Percentage, in here.

For test, you can do these steps:
1-Install **Persian** Version of Firefox Nightly 60+
2-Goto Windows 10/8.1 Control Panel
3-Goto Clock, Language and Region
4-Click on Region
5-Set Format as **Persian**
6-Check Decimal symbol in Additional settings, it should / (It's default for Persian)
7-Check use native digis in Additiional settings, it should be on Context or National, not Never.
8-Goto Firefox Nightly
9-Goto https://send.firefox.com
10-Upload a file.
11-You will see all of digits are in Persian, except upload percentage.

![firefoxsendpercentageinlatin](https://user-images.githubusercontent.com/19834847/35668970-cdbf967a-0748-11e8-984f-2695b3ac6353.jpg)

Thanks.

**Comment by wresuolc** [comment]
This is hard because we're making the percentage sign a different size than the numbers.  Let's try using the built-in function and making them the same size (the size of the percent sign).

Also, check out this bad boy: ‱
