### ISSUE TITLE
The expiration time is wrongly displayed on two rows on Linux

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#749]
[Affected versions]:
- Firefox 58.0 and up

[Affected Platforms]:
- All Linux

[Steps to reproduce]:
1. Start the browser and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a file and and click the "Send another file" link.
3. Observe the file info table.

[Expected result]:
- The expiration time is displayed on a single row. 

[Actual results]:
- The expiration time is displayed on two rows.

[Notes]:
- Here is a screen recording with the issue:
![screenshot from 2018-02-02 15_05_51](https://user-images.githubusercontent.com/18304511/35734938-907358f4-082b-11e8-970a-e716ee5abf26.png)

**Comment by dannycoates** [comment]
@SoftVision-CiprianMuresan we need to get you a bigger screen my friend 😉

**Comment by SoftVision-CiprianMuresan** [comment]
I have verified that the issue is no longer reproducible the Dev server on Arch Linux and Ubuntu.
