### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by dnarcese** [mozilla/send#75]

**Comment by pdehaan** [comment]
One possible solution in https://github.com/mozilla/something-awesome/pull/71#discussion_r121024310.

**Comment by pdehaan** [comment]
Or maybe we just remove the "folder" reference here for V1:

<img width="213" alt="firefox_fileshare" src="https://user-images.githubusercontent.com/557895/27343820-fec643a2-5598-11e7-9fcb-209a035a88c1.png">

**Comment by ehuggett** [comment]
For multi-file uploads an archive format similar to tar/zip etc would avoid having to deal with multiple filenames (they would become part of the encrypted data) and as such avoids even telling the server its multiple files (once #69 prevents it from seeing the archive filename)

It is possible to create/handle zip archives with javascript (but its is sensible to do so?) so the downloaded does not necessarily have to save it as an archive, they could also have the option of saving each file separately (or not saving every file etc).

If it was an archive format, in theory the zip header (technically a ['tail'](https://github.com/corkami/pics/blob/master/binary/zip101/zip101.svg)) might be usable to attempt to only download the files the user wants (via HTTP range requests) but it would get complicated and would perhaps interact very badly with download limits (My question/proposed solution to #512 would make this impossible) and the server would only see range requests for "multi file uploads" (probably making it obvious to an observer it was not a single file, even if done over https)

**Comment by dannycoates** [comment]
done in vnext
