### ISSUE TITLE
The wrong Firefox icon is used for the pink gradient promo

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#750]
[Affected versions]:
- Chrome
- Opera

[Affected Platforms]:
- All Linux
- All Mac
- All Windows

[Prerequisites]:
- Be in the Pink variant of the promo banner.

[Steps to reproduce]:
1. Start the Chrome or Opera and navigate to "https://send.stage.mozaws.net/" page.
2. Observe the Firefox icon's color from the promo banner.

[Expected result]:
- The icon is white.

[Actual results]:
- The icon is colored.

[Notes]:
- Here is a screen shot of the Mockups:
![image](https://user-images.githubusercontent.com/18304511/35743786-3dc742d4-0847-11e8-9349-72f77aa34eaa.png)

- Here is a screen shot with the issue:
![image](https://user-images.githubusercontent.com/18304511/35743573-a9bc8fb8-0846-11e8-80aa-bf1686e0003d.png)

**Comment by dannycoates** [comment]
I know. I'm not going to change it
