### ISSUE TITLE
"Add password", circle animation and "Change" buttons do not have the same width

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#762]
[Affected versions]:
- Firefox 58.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start the browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a file and check the password checkbox.
3. Click the "Add password" button and observe the behavior.

[Expected result]:
- As it transitions from "Add password" label to the circle animation to the "Change" label, the button's width remains the same.

[Actual results]:
- The button becomes smaller as it transitions through each state.

[Notes]:
- The issue is also reproducible if you just change the password. The button becomes bigger during the loading animation and then smaller.
- Here is a screen recording with the issue:
![password button changes its width](https://user-images.githubusercontent.com/18304511/36480595-8de14f1c-1715-11e8-8140-9b0d2178a99d.gif)

**Comment by dannycoates** [comment]
Languages with very long translations will have a slight difference in size, but the current fix is large enough for most.

**Comment by SoftVision-CiprianMuresan** [comment]
This issue is no longer reproducible on the latest Dev version on Windows 10 x64, Mac 10.13 and Arch Linux x64.
Looks good on German, Russian, French and Italian too.
