### ISSUE TITLE
The progress bar is not correctly displayed when an upload actually starts

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#765]
[Affected versions]:
- Firefox 58.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start the browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a large file.
3. Observe the progress bar as it transitions from indefinite progress to actual upload.

[Expected result]:
- When the upload starts, the progress bar visibly starts from 1%.

[Actual results]:
- The upload bar shrinks down towards the 1% representation and then starts showing the current upload percentage.

[Notes]:
- Here is a screen recording with the issue:
![infinite loading transition](https://user-images.githubusercontent.com/18304511/36540996-22e20d98-17e5-11e8-97df-c6dea372f47f.gif)

**Comment by dannycoates** [comment]
I think #777 fixes this too
