### ISSUE TITLE
The "Send" logo from the top left side of the screen is stretched

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#770]
[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start Firefox browser and navigate to "https://send.stage.mozaws.net/" page.
2. Observe the "Send" logo from the top left side of the screen.

[Expected result]:
- The logo is correctly displayed.

[Actual results]:
- The logo is stretched.

[Notes]:
- This issue is not reproducible on https://send.dev.mozaws.net/ and https://send.firefox.com/.
- Here is a screenshot of the issue: 
![stretched](https://user-images.githubusercontent.com/26000308/36786311-a4ab208c-1c8e-11e8-9574-333b57ce6490.png)

**Comment by dannycoates** [comment]
Thanks! SVGO's default settings were a bit to aggressive here. I've fixed it in a2aca8955082a4bef5f63eb6f1420bb5093bfbdb

**Comment by SoftVision-CarmenFat** [comment]
I have verified that the issue is no longer reproducible on Stage server on Windows 10 x64, Mac 10.13 and Ubuntu 14.04.
