### ISSUE TITLE
[Enhancement] "Delete All" button should be displayed when there is a high amount of uploaded files

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#772]
[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

 [Prerequisites]:
 - Have a bunch of uploaded files. 
 
[Steps to reproduce]:
1. Start Firefox browser and navigate to https://send.firefox.com/ page.
2. Observe the options from the bottom part of the File Share card.

[Expected result]:
- "Delete All" button should be displayed when there are more than "x" uploaded files.

[Actual results]:
- There is no "Delete All" button, the user has to delete the uploaded files one by one.

**Comment by dannycoates** [comment]
old (wontfix)
