### ISSUE TITLE
[Enhancement] "Your upload was cancelled" warning is displayed for a second if upload is cancelled during import phase

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#773]
[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac
 
[Steps to reproduce]:
1. Start Firefox browser and navigate to https://send.firefox.com/ page.
2. Upload a large file.
3. Rapidly click the "Cancel upload" link while still in importing phase and observe what happens next.

[Expected result]:
- The upload is canceled.

[Actual results]:
- "Your upload was canceled" warning is displayed for a second.

[Notes]:
- The warning is not displayed when canceling the file upload during encrypting and uploading phases.
- Here is a screen recording of the warning: https://goo.gl/CW1kTq

**Comment by wresuolc** [comment]
There is a background worker we have to communicate with so it takes a second.  I'm going to wontfix this.
