### ISSUE TITLE
Old Firefox logo is displayed on the feedback survey

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#774]
[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start Firefox browser and navigate to "https://send.stage.mozaws.net/" page.
2. Click the "Feedback" button and observe the logo from the survey page. 

[Expected result]:
- The new Firefox logo is displayed.

[Actual results]:
- The old Firefox logo is displayed.

[Notes]:
- This issue is also reproducible on https://send.dev.mozaws.net/ and https://send.firefox.com/.
- Attached a screen recording of the issue:

![old logo ff](https://user-images.githubusercontent.com/26000308/36787602-61f09b78-1c93-11e8-82b7-30e3b8d8c053.gif)

**Comment by johngruen** [comment]
fixed
