### ISSUE TITLE
"Require a password to download this file" text is not selected if triple clicking it

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#775]
[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start Firefox browser and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a file and triple click the "Require a password to download this file" text.
3. Observe the behavior.

[Expected result]:
- The text is selected.

[Actual results]:
- The text is not selected since the last click opens and focuses the password field.

[Notes]:
- This issue is also reproducible on https://send.dev.mozaws.net and https://send.firefox.com.
- Attached a screen recording of the issue:

![triple click](https://user-images.githubusercontent.com/26000308/36793412-085af672-1ca6-11e8-8454-32348d3603d9.gif)

**Comment by dannycoates** [comment]
Maybe we should make this text never selectable?

**Comment by wresuolc** [comment]
Let's make this not-selectable.

**Comment by RCMainak** [comment]
I am interested.

**Comment by SoftVision-CosminMuntean** [comment]
I have retest this issue on latest Send (2.5.0) version and is no longer reproducible. The text can no longer be selected.
Tested on Windows 7 x64, 10 x64, Mac Os 10.12 and Arch Linux.
