### ISSUE TITLE
The upload wrongly remains stuck at "Encrypting..." state until the file is completely uploaded, on Edge

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#780]
[Affected versions]:
- Microsoft Edge 40.15063.674.0 (HTML version 15.15063) 
- Microsoft Edge 41.16299.248.0 (HTML version 16.16299)
- Microsoft Edge 42.17046.1000.0 (HTML version 16.17046)

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the Microsoft Edge browser and navigate to "https://send.dev.mozaws.net/" page.
2. Upload a large file.
3. Observe the upload process.

[Expected result]:
- After the file is encrypted, the upload starts and the progress is correctly displayed.

[Actual results]:
- The upload remains stuck in the "Encrypting..." state until the file is completely uploaded and only then the 100% percentage will be displayed.

[Notes]:
- This issue is not reproducible when you download a file.
- On Microsoft Edge 38.14393.2068.0 (HTML version 14.14393), the progress bar remains stuck at about 18% and the percentage is displayed according to the upload progress.
- Here is a screen recording with the issue:
![send - edge](https://user-images.githubusercontent.com/31244235/36894172-385c5028-1e13-11e8-8f12-6c344cdee94b.gif)

**Comment by dannycoates** [comment]
https://stackoverflow.com/questions/43942396/ajax-file-upload-progress-upload-event-does-not-fire-in-edge-browser

**Comment by dannycoates** [comment]
Though not a fix I've made it so the spinner gets stuck *after* encrypting and removed the indeterminate spinner from Edge.

**Comment by dannycoates** [comment]
old (wontfix)
