### ISSUE TITLE
Make the selectbox accessible

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#783]
Needs keyboard support, etc. If you're interested in working on this I'll be happy to provide specifications.

**Comment by RCMainak** [comment]
I am interested. Please share details & IRC channel name. @dannycoates, you can find in #services-dev

**Comment by dannycoates** [comment]
I'd like to change to a native `<select>` element. That way we won't need any fancy js logic. Lets try to keep the style of the closed state with the arrow: 

<img width="528" alt="screen shot 2018-03-12 at 10 50 26 am" src="https://user-images.githubusercontent.com/87619/37300671-c1658a38-25e3-11e8-9809-6d009bd5eb1b.png">

but let the options dropdown be native.

Here's one example of how to style a `select` that might be a helpful reference: https://codepen.io/raubaca/pen/VejpQP

The most important parts are that keyboard navigation / selection works and the `changed` function gets called correctly in https://github.com/mozilla/send/blob/master/app/templates/selectbox/index.js

**Comment by megrxu** [comment]
Is there anyone working on it? Maybe I can have a try. 
But what means "keyboard support"?

**Comment by dannycoates** [comment]
Thanks for you interest @megrxu. It's already being worked on in #791

**Comment by dannycoates** [comment]
done
