### ISSUE TITLE
Implement streaming encryption

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#785]
Streams combined with RFC 8188 style encryption should allow us to support larger file sizes.

- https://developer.mozilla.org/en-US/docs/Web/API/Streams_API
- https://trac.tools.ietf.org/html/rfc8188
- https://github.com/jimmywarting/StreamSaver.js

**Comment by dannycoates** [comment]
a stream that can slice blobs into chunks for encryption https://gist.github.com/dannycoates/99be55f18b0268241e01819f82f22a98

**Comment by dannycoates** [comment]
done in vnext

**Comment by hbakhtiyor** [comment]
@dannycoates did you consider about https://github.com/minio/sio/blob/master/DARE.md specification?

**Comment by dannycoates** [comment]
no
