### ISSUE TITLE
Pontoon unable to push to repository

### ISSUE THREAD

**Issue by mathjazz** [mozilla/send#787]
```
remote: error: GH006: Protected branch update failed for refs/heads/master.         
remote: error: Required status check "ci/circleci: test" is expected.         
To git@github.com:mozilla/send.git 
 ! [remote rejected] HEAD -> master (protected branch hook declined) 
error: failed to push some refs to 'git@github.com:mozilla/send.git' 
```

If you want to keep the branch protected, the recommended way forward is to create a dedicated `send-10n` repository for localizations only.

**Comment by dannycoates** [comment]
oops, sorry. FIXED. I thought I had it set so only PRs needed status checks not direct pushes. I think we can manage without the strict protection.

**Comment by mathjazz** [comment]
Thanks!
