### ISSUE TITLE
Firefox Android is sent an unsupported page

### ISSUE THREAD

**Issue by karlcow** [mozilla/send#790]
This is a spin-off of https://github.com/webcompat/web-bugs/issues/15972

## Steps to reproduce
0. With Firefox Android
1. Visit a site containing a Firefox Send download link. You may try to upload a content to https://send.firefox.com, then copy the share link to the address bar.

Results: "Unsupported browser" error in Firefox Android
Faking the UA to be chrome gets the right page.

**Comment by dannycoates** [comment]
This'll go out in v2.5.2

**Comment by dannycoates** [comment]
live on https://send.firefox.com
