### ISSUE TITLE
Send has trouble with relatively large file on Firefox

### ISSUE THREAD

**Issue by TempSpas** [mozilla/send#796]
I experienced this bug within the hour when trying to receive a file from Send. The file was 556.9 mb, an audio (aac) file. The first link I received was good for one download, and after reaching 100% the page flashed "Decrypting" for a second and then gave the "Uh oh, something went wrong" dialog, rendering the link unusable.

I received another link for this file, this time password-protected and good for five downloads. I tried to download it twice from this link with Firefox, and both times the issue as described above occurred. When I tried it on **Safari**, the file downloaded without issue.

I am using a handful of security extensions on Firefox, all of which are disabled for the Send website. Further, I have never experienced this issue in the past, and I have used the service many times to transfer smaller files (typically between 1-10 mb). Hence why I believe this to be related to the larger file size.

**System Info:**

Firefox 59.0.2
macOS 10.13.3
Safari 11.0.3

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this issue on latest Firefox (59.0.2) release and latest Nightly (61.0a1) build.

When you download a large large file (eg: 512 MB) after the progress reach 100% and the file enters in the "decrypting" state you are redirected to the "Something went wrong" page and the download is not completed. 

I have tested this issue on the following machines:
- iMac 10.13 (4 GB RAM, Processor Core 2 Duo 3.0 Ghz - reproducible
- Mac Book Pro on 10.12 and 10.13 (8 GB RAM, Processor 2.7 Ghz Intel Core i5) - reproducible
- Ubuntu 16.04 (4 GB RAM, Processor Intel Core i3 2120 3.30 Ghz) - reproducible
- Ubuntu 14.04 (8 GB RAM, Processor  Intel Core i5-3470 3.2 Ghz) - not reproducible
- Windows 10 x64(4 GB RAM, Processor Intel Core i5-4200U 1.6 Ghz, 2.6 Ghz)- not reproducible
- Windows 7 x64 (16 GB RAM, {rpcesspr A<D FX 83200 Eight Core 3.50 Ghz) - not reproducible
 
Here is a screenshots with browser console errors:
![browser console](https://user-images.githubusercontent.com/19226534/38040762-e05157b0-32b8-11e8-85e0-203f85f6ea89.png)

**Comment by wresuolc** [comment]
Hopefully the streaming decryption plan will help here.  @johngruen will investigate

**Comment by wresuolc** [comment]
The streaming stuff is targeted in 63, but we'll start on it with polyfills.  We won't be able to do large files until its native though, so, it'll be awhile.
