### ISSUE TITLE
"1 download" button and "Require a password" checkbox do not do anything when the "Enter" key is pressed while they are focused

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/send#797]
[Affected versions]:
- Firefox 59.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start Firefox browser and navigate to https://send.dev.mozaws.net/.
2. Upload a file.
3. Focus the "1 download" button using the "Tab" key.
4. Press the "Enter" key and observe the behavior.

[Expected result]:
- The drop down menu is displayed.

[Actual results]:
- The button remains focused but the drop down menu isn't displayed.

[Notes]:
- This issue is also reproducible on stage server.
- If the require a password checkbox is focused and the "Enter" key is pressed, it is not checked.
- Here is a screen recording with the issue:
![send](https://user-images.githubusercontent.com/31244235/38078552-57973b96-3345-11e8-98e6-c7c5a02e7010.gif)

**Comment by wresuolc** [comment]
Space is used for toggling elements in the form -- space works here, so we'll close this.
