### ISSUE TITLE
The bottom part of the "Downloads" button is not visible on Firefox

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#798]
[Affected versions]:
- Firefox 59.0.2 and up

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64

[Steps to reproduce]:
1. Start Firefox browser and navigate to https://send.dev.mozaws.net/.
2. Upload a file.
3. Observe the "1 Downloads" button.

[Expected result]:
- All sides of the button are visible.

[Actual results]:
- The bottom part of the button is not visible.

[Notes]:
- This issue is also reproducible on stage and prod servers.
- The issue is not reproducible on Chrome, Safari or Edge.
- Here is a screen recording with the issue:
![img_30032018_173710_0](https://user-images.githubusercontent.com/18304511/38141889-f34c580c-3442-11e8-9abc-70867a9f0715.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest version of Send (2.5.4) and the issue is no longer reproducible.  Tested using latest Firefox (60.0.1) release and latest Nightly (62.0a1) build on  Windows 7 x64 and Windows  10 x64
