### ISSUE TITLE
The font from the number of downloads dropdown is too large on other browsers than Firefox

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#799]
[Affected versions]:
- Chrome Version 65.0
- Microsoft Edge 41.16299.248.0
- Safari 11.03

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start Firefox and Chrome browsers.
2. Navigate to "https://send.dev.mozaws.net/" page on both browsers.
3. Upload a file and click the "1 download" button on both browsers.
4. Observe the font of the number of downloads dropdown on both browsers.

[Expected result]:
- The same font is displayed in both browsers.

[Actual results]:
- The font is larger on Chrome than on Firefox.

[Notes]:
- This issue is also reproducible on stage and production servers.
- Attached a screen shot of the issue:
![number of downloads panel](https://user-images.githubusercontent.com/19226534/38142601-a3b19318-3445-11e8-9089-1a9a41e185a3.png)

**Comment by dannycoates** [comment]
Not gonna happen. We have no control over those styles. Every browser does it differently
