### ISSUE TITLE
Puppeteer package should not download Chromium on a production setup

### ISSUE THREAD

**Issue by ElectronicWar** [mozilla/send#802]
After updating my Send instance, I noticed that puppeteer was added, which in turn downloaded a full Chromium package (almost 300 Mb) to work.

As puppeteer is only used as a unit test tool (in `test/frontend/runner.js`), I would like that it is moved as an optional npm dependency or to a "unit test" environment to avoid having random Chromium binaries laying around on a server.

**Comment by dannycoates** [comment]
puppeteer is a in the `devDependencies` so a production build should only install dependencies with `npm install --production` as our Dockerfile does https://github.com/mozilla/send/blob/master/Dockerfile#L10

**Comment by ElectronicWar** [comment]
Thank you for the link.
I have re-checked my deployment script and I had indeed a typo in there.
Sorry to have wasted your time on such a trivial issue.
