### ISSUE TITLE
I'm getting e.datatransfer null for firefox, but it's working for chrome

### ISSUE THREAD

**Issue by jayzerky** [mozilla/send#814]
![image](https://user-images.githubusercontent.com/38071618/39663083-453ab22c-508a-11e8-9237-b124cbe075b6.png)
![image](https://user-images.githubusercontent.com/38071618/39663093-561aa372-508a-11e8-9694-9eace1edb2fc.png)

In the second image when trying to get e.datatransfer it is undefiend.

**Comment by pdehaan** [comment]
@jayzerky what browser/version and OS are you using?

**Comment by dannycoates** [comment]
@jayzerky I don't recognize any of the code in your screenshots. Where is it from?

**Comment by jayzerky** [comment]
@pdehaan I'm using Firefox v59.0.3, and OS is Win 7 and 10

**Comment by jayzerky** [comment]
@dannycoates danny it's pure object oriented javascript, suggestions in any language is welcome :)

**Comment by dannycoates** [comment]
@jayzerky I'd like to know *where* the code is from. It is not from this project so I don't know how to how to help. Are you getting this error on https://send.firefox.com?
