### ISSUE TITLE
OAuth work for Firefox Accounts

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#819]
Implement the basic [OAuth flow for Firefox Account](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/Introduction).

No UI bits required.

**Comment by timvisee** [comment]
I'm wondering what this functionality would be for.

Is this possibly used for additional security, or to link file IDs and owner tokens to an account instead of storing them in the clients browser?

**Comment by dannycoates** [comment]
@timvisee we're planning on adding an optional account level service tier that will offer some additional functionality, for example being able to manage your uploaded files from multiple devices.
