### ISSUE TITLE
The "Downloads" button is too large on Firefox if the Telugu language is set

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#821]
[Affected versions]:
- Firefox 60.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the Telugu language set in "about:preferences" page on a new clean profile.

[Steps to reproduce]:
1. Start Firefox browser with the profile from prerequisites and navigate to https://send.stage.mozaws.net/.
2. Upload a file.
3. Observe the "Downloads" button.

[Expected result]:
- The button is correctly displayed.

[Actual results]:
- The button is too large.

[Notes]:
- On Chrome the button is displayed on a row, but the bottom part of it is not visible.
- Here is a screenshot with the issue:
![telugu](https://user-images.githubusercontent.com/19226534/40435741-017d722a-5eba-11e8-90a7-4d977673c091.png)

**Comment by brainlulz** [comment]
When you select the option of 20 downloads, you see that the text is closer to the bottom border.
I tried to managed something cleaner:
`.title`: changed line-height to `60px`;
`.select`: changed the padding to `8px 2px 4px 0`
`option`: added padding-top of `4px`

It look like this: 
![capture d ecran 2018-05-30 a 22 03 24](https://user-images.githubusercontent.com/27764502/40744938-5f11c1e2-6456-11e8-9780-1021d5ae8b0e.png)

If accepted I could make a PR

**Comment by dannycoates** [comment]
Thanks for looking @brainlulz 

`line-height: 60px` is too much for English and most other languages. With the changes from #820 I think we're at a pretty acceptable compromise now.
