### ISSUE TITLE
Implement the ability to sign in to a Firefox Account

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#823]
This is a tracking issue for FxA accounts integration engineering. 

In order to close this bug we should: 
1. Allow the user to interact with some page element to trigger an FxA auth flow
2. Upon completion of a sign in/up flow represent the user as signed in to Send
3. Demonstrate that a user's current active sends are displayable across more than one device.

**Comment by ExE-Boss** [comment]
See also #464
