### ISSUE TITLE
Implement time based expiration

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#825]
This issue is only applicable for FxA tier and does not cover final UI implementation.

When uploading, FxA tier users should be able to specify time limits of 5 minutes, 1 hour, 1 day, 1 week and 2 weeks. Default should always be 1 day.

**Comment by maverick74** [comment]
@emily-hou1 Isn't #728 a duplicate of this?

**Comment by emily-hou1** [comment]
Selectable time limits are implemented in #894, not integrated with FxA tiers yet
