### ISSUE TITLE
Password Failed

### ISSUE THREAD

**Issue by SaulMoonves** [mozilla/send#830]
I git pulled and set up my own server today. regular shared links worked, but I and a another person tried sending files with two different dictionary-word passwords, and the recipient could not get Send to accept the password so as to download the file.

**Comment by dannycoates** [comment]
This could be related to #831. The share link is also combined with the password to generate the password hash, so if the link displayed on the share page is different from the *actual* url, it will not work.

**Comment by SaulMoonves** [comment]
Thank you, this fixed the problem. I thought running

  `$ npm run prod`

would be enough, but 

 `$ NODE_ENV=production npm run prod`

as you suggested made it work.
