### ISSUE TITLE
In Reverse Proxy situation, use Proxy Headers

### ISSUE THREAD

**Issue by SaulMoonves** [mozilla/send#831]
Using Apache for reverse proxy, Send filled in the links with the app's domain, port and protocol e.g. "http://127.0.0.1:1443/whateverdownload" rather than https://send.mydomain.tld/whateverdownload.

Turned on ProxyPreserveHost in Apache config, which made the url  http://send.mydomain.tld/whateverdownload. I have a redirect on http to https, but if Send detected proxy headers X-Forwarded-Host and X-Forwarded-Proto then it could properly prepend https:// to the download link and use the correct domain name.

**Comment by dannycoates** [comment]
`ProxyPreserveHost` is the preferred way to do it. To ensure the the protocol for share links is https set the `NODE_ENV` environment variable to `production`.

**Comment by SaulMoonves** [comment]
Thank you, this worked!
