### ISSUE TITLE
Expires setting wrong in Vietnamese in upload success

### ISSUE THREAD

**Issue by abpvn** [mozilla/send#835]
**Wrong**: The link to your file will expire after [select] or giờ. 
Select label: lượt tải, lượt tải, lượt tải, lượt tải, lượt tải, lượt tải

**Correct**: Liên kết của bạn sẽ hết hạn sau [select] hoặc ? _giờ_ (I realy don't understand here. How many hour link will expires?)
Select label: 1 lượt tải, 2 lượt tải, 3 lượt tải, 4 lượt tải,5 lượt tải,20 lượt tải

**Comment by SoftVision-CiprianMuresan** [comment]
It looks like that sting is still waiting to be confirmed: https://pontoon.mozilla.org/vi/test-pilot-firefox-send/send.ftl/?string=174402.

**Comment by dannycoates** [comment]
Thanks, @abpvn. Pontoon will automatically commit the changes to the repo once they're confirmed.
