### ISSUE TITLE
Chromium revision is not downloaded error on frontend test

### ISSUE THREAD

**Issue by KancerEzeroglu** [mozilla/send#839]
When I run `npm run test:frontend` I get this error 
```
Kancers-MacBook-Pro:send kancergokirmak$ npm run test:frontend

> firefox-send@2.5.4 test:frontend /Users/kancergokirmak/Devel/send
> cross-env NODE_ENV=development node test/frontend/runner.js && nyc report --reporter=html

^C^CKancers-MacBook-Pro:send kancergokirmak$ AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Console.assert (console.js:188:23)
    at Function.launch (/Users/kancergokirmak/Devel/send/node_modules/puppeteer/lib/Launcher.js:97:15)
    at <anonymous>

```

I think we are getting this error because we don't have `puppeteer` in dependencies (package.json).
Do you agree?
If yes I can change package.json..

**Comment by dannycoates** [comment]
puppeteer is in the devDependencies. I don't get this error from a clean clone. Maybe try `npm install` again (and watch for install errors)?

**Comment by johngruen** [comment]
@KancerEzeroglu we are going to close this for now. If you have more questions feel free to reopen or file other issues.
