### ISSUE TITLE
GCP app error sh: 1: cross-env: not found

### ISSUE THREAD

**Issue by unl1k3ly** [mozilla/send#865]
Hi,

I'm currently trying to have it hosted at GCP APP and it seems to have a mishmash on versioning in the package.json file.

The error I'm getting is related to:

```
Updating service [default] (this may take several minutes)...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
> firefox-send@2.0.0 start /app
> cross-env NODE_ENV=development webpack-dev-server
sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! firefox-send@2.0.0 start: `cross-env NODE_ENV=development webpack-dev-server`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the firefox-send@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-22T03_45_53_207Z-debug.log
```

Steps to reproduce the issue are:
- From a Google Cloud Shell do all the above...
- git clone  --branch v2.0.0 https://github.com/mozilla/send
- create a `app.yaml` file with the following content:
```
runtime: nodejs
env: flex
```
- remove Dockfil so Google wont bother
- run, `gcloud app deploy`

Thank you very much

**Comment by dannycoates** [comment]
We don't deploy on GCP so I don't know how to make it work there. For the specific case of cross-env, it should be installed with `npm install` before running any npm scripts like `npm start`.
