### ISSUE TITLE
Docker Building errors sh: rimraf: not found

### ISSUE THREAD

**Issue by unl1k3ly** [mozilla/send#867]
Hi,

I'm not sure why but I'm having several issues using Docker and Send on a branch v2.0.0.

When building a Docker, it insists to use Redis rather than a local file system. Is there any thing I can do to use the filesystem rather than a Redis, S3 bucket ?

Alternatively, I've done a  Dockerfile which also fails when I pass production node environments.

The error:

```
> firefox-send@2.0.0 clean /app
> rimraf dist
sh: rimraf: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! firefox-send@2.0.0 clean: `rimraf dist`
npm ERR! spawn ENOENT
npm ERR! ```

Could you please help me out make this docker work with file system local storage, please?

Cheers

**Comment by dannycoates** [comment]
For more info on building and running the docker image see https://github.com/mozilla/send/blob/master/docs/docker.md

For the specific error on rimraf, ensure it's installed with `npm install` before running the npm script.
