### ISSUE TITLE
Ensure/verify that data expires

### ISSUE THREAD

**Issue by wresuolc** [mozilla/send#89]
This issue is to ensure that data expires after 24 hours, no matter if a client is involved or not (meaning, the server enforces this).  This issue may be possible to just close, but can you explain how expiration happens right now?

Similar question:  When someone downloads a file, is the file immediately removed from s3, or after the download is completed, or is it marked for deletion later, or...?

**Comment by abhinadduri** [comment]
Currently, when someone downloads a file it is immediately removed from s3. If the client is not involved at all, the reference to the file is removed from our servers after 24 hours, and it is deleted off s3 in three days (this was a default).

**Comment by wresuolc** [comment]
@dannycoates is going to follow up with @relud on the S3 policy

**Comment by relud** [comment]
I will add a 24 hour retention policy to s3, if it isn't already there, and then update this issue

**Comment by relud** [comment]
added to stage and prod
