### ISSUE TITLE
Remove google-analytics.com

### ISSUE THREAD

**Issue by beerisgood** [mozilla/send#897]
https://send.firefox.com use www.google-analytics.com
Why? If you care about privacy, remove it!

Testsite: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsend.firefox.com%2F

**Comment by clouserw** [comment]
We're not going to remove GA as it's instrumental in improving the service.  In an effort to balance it's usefulness with privacy concerns, we don't load it in private browsing or if you've enabled DNT -- both are good options if you'd like to avoid it.

**Comment by Hillside502** [comment]
Why is Mozilla using anything **closed-source**?

Open Source Google Analytics Alternatives - AlternativeTo.net
https://alternativeto.net/software/google-analytics/?license=opensource

**Comment by finn0** [comment]
@beerisgood @akuckartz , It seems like they are no longer using any analytics service. see[[1] ], **No third party requests**.

[1]: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsend.firefox.com%2F#requests
