### ISSUE TITLE
ERROR: Service 'web' failed to build:

### ISSUE THREAD

**Issue by johnjwatson** [mozilla/send#907]
Hello!

Firstly, thank you for this great `experiment`. I have been trying to deploy this on a standalone server (no S3, no Sentry, no redis). and I exceute the following cmd's:

`mkdir -p send && cd send && git clone https://github.com/mozilla/send.git && cd send && npm install && npm run build && docker-compose up`

and I get (for docker-compose):

`ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install --production && npm cache clean --force' returned a non-zero code: 1`

I am no docker expert, and I am wondering how I can fix this above issue.

best,

JW

**Comment by johnjwatson** [comment]
Turns out that restarting the machine and running the above commands again solved the issue - not surw how or why!

**Comment by dannycoates** [comment]
I'm glad it worked on a second try.

fwiw it looks like you ran into a transient error with the npm package manager, a failed network request maybe.
