### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by johnjwatson** [mozilla/send#908]
Hello!

I have tried to run Send on docker and used this command first:

`mkdir -p send && cd send && git clone https://github.com/mozilla/send.git && cd send && npm install && npm run build && docker-compose up`

.. all went OK i.e no errors. Now I do (pardon me if my docker skills are not upto scratch), I do:

`docker run --net=host -e 'NODE_ENV=production' -e 'FILE_DIR=/home/foo/send' -e 'BASE_URL=0.0.0.0' mozilla/send:latest`

and I get thrown:

`{"Timestamp":1534879535662000000,"Logger":"FirefoxSend","Type":"uncaughtException","Severity":0,"Pid":24,"EnvVersion":"2.0","Fields":{"error":"Error: EACCES: permission denied, mkdir '/home/foo'","stack":"\n    at Object.fs.mkdirSync (fs.js:885:18)\n    at sync (/app/node_modules/mkdirp/index.js:71:13)\n    at Function.sync (/app/node_modules/mkdirp/index.js:77:24)\n    at new FSStorage (/app/server/storage/fs.js:12:12)\n    at new DB (/app/server/storage/index.js:11:20)\n    at Object.<anonymous> (/app/server/storage/index.js:57:18)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/app/server/routes/index.js:4:17)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/app/server/prod.js:5:16)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Function.Module.runMain (module.js:693:10)\n    at startup (bootstrap_node.js:191:16)\n    at bootstrap_node.js:612:3"}}`

Not sure what it is that I am doing wrong - any pointers in the right direcction would be great.

best,
JW

**Comment by dannycoates** [comment]
If you plan on running standalone with the filesystem as your storage I suggest running the service without docker, since it'll probably be easier to manage. To do so you'd do something like:

```sh
npm run build
FILE_DIR=/home/foo/send BASE_URL=0.0.0.0 npm run prod
```

If you want to use docker, you can, but you'll probably want to use a volume to map a directory from your filesystem into the container. See https://docs.docker.com/storage/ for more info.

**Comment by johnjwatson** [comment]
It makes sense Danny - I should probably learn some Docker before I attempt it with docker. I now run Send via `pm2` and it seems to work fine. Thanks again for your fast reply.
