### ISSUE TITLE
filename when running send on personal server.

### ISSUE THREAD

**Issue by johnjwatson** [mozilla/send#910]
So, I have set up send and changed the data-dir in config like so:

  file_dir: {
    format: 'String',
    default: '/home/foo/send',
    env: 'FILE_DIR'
  }

Now, when I run the server in production mode and upload a file (say ab.pdf), I see on `/home/foo/send', something like:

`a613c3830f`

but, how do I get the original file ab.pdf off this?

**Comment by dannycoates** [comment]
You need the share url (next to the 'copy to clipboard' button) to get the original file.


<img width="738" alt="screen shot 2018-08-21 at 5 57 23 pm" src="https://user-images.githubusercontent.com/87619/44436779-f1b42980-a56b-11e8-8a7c-bf4d6c165b22.png">

**Comment by johnjwatson** [comment]
Hello Danny - yes, I can see the URL (and ofcourse I am able to download the file - I think it is doing some client side decryption) - but, I want to extract the file in a programmatic manner with something like wget or python requests. I want to do this because I eventually will move the file to other locations on my disk.

I guess my question os: Given the upload URL, how do I extract the file without using a browser?

**Comment by dannycoates** [comment]
> Given the upload URL, how do I extract the file without using a browser?

There's an unofficial command line client, but I don't know how up to date it is and we generally don't guarantee a stable API. https://github.com/ehuggett/send-cli

**Comment by johnjwatson** [comment]
> There's an unofficial command line client, but I don't know how up to date it is and we generally don't guarantee a stable API. https://github.com/ehuggett/send-cli

This is such a shame - if this download feature was officially supported, [atleast] everyone in the Django community will be using it!

Thanks again for your prompt response - it was great to try out Firefox Send - pure delight to use.

I leave it to you to close the issue or assign it someone.


-JW

**Comment by johnjwatson** [comment]
Danny, one question: is there a way to disable encryption in Send?
The problem I see is to decrypt the file on my server. I see this:
https://github.com/ehuggett/send-cli/blob/master/sendclient/download.py
..but, I am not able to figure out how I can extract the "keys" variable.

Would be great to just disable encryption for my use case.

**Comment by dannycoates** [comment]
> is there a way to disable encryption/decryption in Send?

The encryption is pretty deeply integrated and disabling it easily isn't a feature we're interested in having. You'd need to modify the code to skip over the encryption and authentication.

**Comment by fzzzy** [comment]
@johnjwatson I don't understand -- the encryption is the entire point of send. If you aren't interested in that, why are you using send? Surely there are other solutions that would be easier to use?

**Comment by dannycoates** [comment]
Closing since there's no new work here. Feel free to continue questions/comments.
