### ISSUE TITLE
Is Send French?

### ISSUE THREAD

**Issue by marniepw** [mozilla/send#923]
1. Was searching for the Test Pilot website: entered "test pilot firefox" in the awesomebar. 
2. First result was what I was looking for. Excellent.
3. But then I noticed that the link for Send appeared to be in French. See attached.
4. Same result when I search directly in the Google search bar.

Firefox Nightly 64.0a1 (2018-09-10)

<img width="973" alt="screen shot 2018-09-10 at 4 39 07 pm" src="https://user-images.githubusercontent.com/33703387/45330165-f17ace80-b518-11e8-9672-1591c2951930.png">

**Comment by johngruen** [comment]
@marniepw will file in test pilot
