### ISSUE TITLE
[GCP] The upload is interrupted after the "Privacy" and "Terms" links are opened

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#924]
[Affected versions]:
- Firefox 62.0 and up

[Affected Platforms]:
- All Windows
- All Linux

[Steps to reproduce]:
1. Start Firefox browser and navigate to "https://stage.send.nonprod.cloudops.mozgcp.net/" page.
2. Upload a large file (100 Mb).
3. From the footer of the page click the "Privacy" link.
4. Focus the "Uploading" page and click the "Terms" link.
5. Focus the "Uploading" page and observe the behavior.

[Expected result]:
- The upload is not interrupted.

[Actual results]:
- The upload is interrupted 

[Notes]:
- In certain cases the issue is only reproducible if the links are opened multiple times.
- The issue is not reproducible using the "https://send.dev.mozaws.net/" website.
- The issue is not reproducible using the Send v2 website: https://send2.dev.lcip.org/
- I haven't managed to reproduce the issue on Mac 10.13.
- I haven't managed to reproduce the issue on Chrome.
- Here is a browser console errors:
![browser console error](https://user-images.githubusercontent.com/19226534/45367008-e7280580-b5e8-11e8-830e-903755dccec9.png)

- Here is a screen recording with the issue:
![interrupted](https://user-images.githubusercontent.com/19226534/45367022-f0b16d80-b5e8-11e8-93c4-da25925d58f1.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
I have tested this issue and is no longer reproducible with the stage version [v.2.0.6](https://stage.send.nonprod.cloudops.mozgcp.net/) on Firefox 63 and up, on Windows 10 x64, Windows 7 x64 and Arch Linux.

Considering this I will close this issue.
