### ISSUE TITLE
[Send v2] You are wrongly redirected to the "Enter Password" page if you open a password protected expired link

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#928]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a link with an upload file that expires after 1 download.
- A password is added for the uploaded file.

[Steps to reproduce]:
1. Open the link from the prerequisites.
2. Enter the password and click the "DOWNLOAD" button.
3. After the download is completed open the same link in a new tab.
4. Observe the behavior.

[Expected result]:
- "The link has expired" page is opened.

[Actual results]:
- "The link has expired" page is briefly displayed then you are redirected to the "Enter Password" page.

[Notes]:
- Even if you enter the correct password you get the "Incorrect password. Try again." message.
- Here is a screen recording of the issue:
![expired file](https://user-images.githubusercontent.com/19226534/45692818-5f03ac00-bb64-11e8-81aa-b4797b7771e1.gif)

**Comment by dannycoates** [comment]
This should be fixed on send2

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the Senv v2 dev website and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
