### ISSUE TITLE
[Send v2] The "Sign In" promo is briefly displayed while you are logged in and the page is loaded

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#929]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- You are already logged with a valid account.

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://send2.dev.lcip.org" page.
2. Observe the page while is loading. 

[Expected result]:
- The page is correctly loaded and the "Sign In" promo is not displayed.

[Actual results]:
- The "Sign In" promo is displayed while the page is loading.

[Notes]:
- Here is a screen recording of the issue:
![sign in promo](https://user-images.githubusercontent.com/19226534/45694992-29ad8d00-bb69-11e8-83e1-59b1e7e7da0a.gif)

**Comment by dannycoates** [comment]
This should be fixed on send2

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the Send v2 dev website and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
