### ISSUE TITLE
Improving CSS Identifiers for Send v2

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/send#930]
Right now some of the identifiers for Send V2 are a bit crypic and harsh, especially when viewed from the page. According to @dannycoates, the naming convention losely follows [BEM](https://css-tricks.com/bem-101/). While this is good I still think it can be a bit better.

[addons.mozilla.org](https://www.addons.mozilla.org) has really great, easy to read/use identifiers. They don't quite follow a specific convention but they have a doc with their thoughts [here](https://github.com/mozilla/addons-frontend/blob/master/docs/css.md).

Example: ```uploadArea__clickMsg```, could be ```UploadArea--click-msg```.

This change would be awesome for integration testing specifically and would aide in those efforts quite a bit. 

Thoughts?

**Comment by jrbenny35** [comment]
@dannycoates I am ready to begin my work automating some Android tests and I noticed that its class names are pretty cryptic too. I can update them as I go, is that something that would work for you?

**Comment by dannycoates** [comment]
@jrbenny35 what do you think about the approach in #1087?
