### ISSUE TITLE
Web browser display an error msg 

### ISSUE THREAD

**Issue by hakkay** [mozilla/send#931]
Hi,

When I try to upload a file, error msg display on the web browser.
My configuration : 
- Backend : The app sendfirefox
- Frontend : Nginx as a reverse proxy with an LDAP authentication.

This issue occurs due to LDAP authentication because when I disable it, it works.
How can I resolve this issue ?

**Comment by clouserw** [comment]
Hi.  This is going to be a configuration issue on your end.  It's not something we can help with.
