### ISSUE TITLE
[GCP] DNSSEC

### ISSUE THREAD

**Issue by Darkspirit** [mozilla/send#934]
Problem: Missing DNS Security (authenticity + integrity) for mozgcp.net.
http://dnsviz.net/d/stage.send.nonprod.cloudops.mozgcp.net/dnssec/

Rationale: Mozilla tries to incrementally roll out DNSSEC. We should take advantage of the opportunity to do it at the beginning.

Solution:
Before you deploy a lot, please enable DNSSEC at Google Domains. Once enabled it will take care of itself. https://cloud.google.com/dns/dnssec
This should be the relevant page: https://cloud.google.com/dns/dnssec-config#enabling

Unaware of how you configured it at Google Domains:
You might need to enable it incrementally:
1. mozgcp.net
2. cloudops.mozgcp.net (+ You might need to add its DS record to mozgcp.net.)
3. nonprod.cloudops.mozgcp.net (+ You might need to add its DS record to cloudops.mozgcp.net.)

**Comment by jbuck** [comment]
Hi there, we do not intend to enable DNSSEC on mozgcp.net. We believe that that strong HTTPS combined with HSTS & HPKP headers are a sufficient level of security.

(I know it doesn't have HSTS & HPKP enabled at the moment - something we need to re-add after migrating to GCP. Soon!)

**Comment by Darkspirit** [comment]
Hey, awesome, thanks for your kind triage of both topics!
Please explain some present concerns as this is unexpected. I am sorry that I only just recently heard about the GCP project. If you hesistate to make this change at this point by your team, please consider filing a support request to get it done by Google, to minimize the risk of misusing their UI. I would be glad to have this as a strong argument for intensifying the use of GCP!

Strong HTTPS: Firefox supports TLS 1.2 with ECDHE-RSA-AES128-GCM-SHA256 since 2014 (Firefox 27). So would be a safe change to remove [all plain RSA](https://www.hardenize.com/report/stage.send.nonprod.cloudops.mozgcp.net/1537806224#www_tls) ciphersuites at first. Then it would be interesting when TLS 1.0 and 1.1 could be phased out. Could you make sure that port 80 always redirects to https://? Thanks!

**Comment by jbuck** [comment]
There is no practical benefit to us enabling DNSSEC in addition to using strong HTTPS. One of our security engineers goes into [more detail](https://bugzilla.mozilla.org/show_bug.cgi?id=1384613#c6) for another service we run. For that reason, we won't be enabling DNSSEC for mozgcp.net.

We don't plan on changing the [default google cipher suites](https://cloud.google.com/load-balancing/docs/ssl-policies-concepts#defining_an_ssl_policy) at the moment, but we are fixing the http -> https redirect this week.

**Comment by johngruen** [comment]
Closing. Feel free to open of SotA changes
