### ISSUE TITLE
[Send v2] The "Link has expired..." page is briefly displayed while the "Signin" page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#935]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open a new Firefox profile and navigate to "https://send2.dev.lcip.org" page.
2. Click the "Learn more" link from the "Sign In/Up!" yellow promo.
3. Refresh the page and observe the behavior.

[Expected result]:
- The page is correctly loaded.

[Actual results]:
- The "This link has expired or never existed in the first place!" page is displayed while the page is loading.

[Notes]:
- The issue is also reproducible on other browsers.
- Here is a screen recording of the issue:
![signin page](https://user-images.githubusercontent.com/19226534/45953412-aa113980-c012-11e8-8c0e-f9512c4d5fa4.gif)

**Comment by dannycoates** [comment]
fixed

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Send v2 dev website and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04x64.
