### ISSUE TITLE
[Send v2] Remove the "Send multiple files at once" strings from "Sign In" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#936]
[Notes]:
- Considering the fact that we decided that you can upload multiple files at once even if you are not logged in, we should remove the "Send multiple files at once" strings from the Send Sign In page.

[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open a new Firefox profile and navigate to "https://send2.dev.lcip.org" page.
2. Click the "Learn more" link from the "Sign In/Up!" yellow promo.
3. Observe the "With a free Firefox Account with Send you can:" list.

[Expected result]:
- There is no mention about you can send multiple files at once if you are logged in with a valid FxA.

[Actual results]:
- The "Send multiple files at once" info is displayed even if you can upload multiple files when you are not logged in.

[Additional Notes]:
- Here is a screenshot
![multiple files](https://user-images.githubusercontent.com/19226534/45958002-fe221b00-c01e-11e8-9e9b-010305e98ffa.png)
 of the issue:

**Comment by dannycoates** [comment]
fixed

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Send v2 dev website and the strings are updated. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04.
