### ISSUE TITLE
[Send v2] The previously logged in email is wrongly displayed if you try to log in with a new one from "Sign In" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#937]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- You are logged in with a valid FxA account.

[Steps to reproduce]:
1. Open a new Firefox profile and navigate to "https://send2.dev.lcip.org" page.
2. Click the "FxA" avatar and choose to sign out.
3. Click the "Learn more" link from the "Sign In/Up!" yellow promo.
4. Enter a different valid FxA email and click the "CONTINUE" button.
5. Observe the FxA Sign In page.

[Expected result]:
- The new entered email is already filled.

[Actual results]:
- The old email is filled even if you entered a different one.

[Notes]:
- Here is a screen recording of the issue:
![wrong email displayed](https://user-images.githubusercontent.com/19226534/45960102-1f393a80-c024-11e8-8a73-65fa85f3f734.gif)

**Comment by dannycoates** [comment]
fixed

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Send v2 dev website and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04x64.
