### ISSUE TITLE
modal dialog needs style

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#943]
Current:

<img width="732" alt="screen shot 2018-09-24 at 11 20 42 am" src="https://user-images.githubusercontent.com/87619/45970686-0319a700-bfec-11e8-8c40-c16d59eb4ca1.png">

**Comment by youwenliang** [comment]
Here:
https://mozilla.github.io/testpilot-assets/Send/Send_Modal/

**Comment by dannycoates** [comment]
you don't get the 'oops!' but the rest is done 307c9d3fa1b93bc0df778de5b6319ef9ef1caf3a
