### ISSUE TITLE
[Send v2] Send website lacks the CSS formatting

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#944]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://send2.dev.lcip.org" page.
2. Observe how the page elements are rendered.

[Expected result]:
- The Send website is correctly rendered.

[Actual results]:
- The Send website entirely lacks the CSS formatting.

[Notes]:
- Here is a screen shot of the issue:
![image](https://user-images.githubusercontent.com/19226534/46000446-41c56500-c0b1-11e8-811d-344703d2e2ca.png)

**Comment by johngruen** [comment]
<img width="1217" alt="screen shot 2018-09-25 at 9 11 50 pm" src="https://user-images.githubusercontent.com/3323249/46037189-c2af4b80-c107-11e8-94ed-66c4241eedfb.png">

**Comment by dannycoates** [comment]
i did a build on the dev server but forgot to restart the service. should be fixed now. sorry

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Send v2 dev website and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04x64.
