### ISSUE TITLE
[Send v2] "SELECT A FILE TO UPLOAD" string wrongly exceeds the button's area on German localization 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#945]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the preferred language set to German [de-de] in "about:preferences#general".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and  to "https://send2.dev.lcip.org" page.
2. Observe the "SELECT A FILE TO UPLOAD" button.

[Expected result]:
- The button is correctly displayed. 

[Actual results]:
- The "SELECT A FILE TO UPLOAD" string exceeds the button's area.

[Notes]:
- The "AUSWAHLEN" string is displayed under the button. It not very visible because of the website's background.
- Here is a screen shot of the issue:
![select file to uplod german strings](https://user-images.githubusercontent.com/19226534/46002631-3e34dc80-c0b7-11e8-85e1-f02df83ecf94.png)

**Comment by dannycoates** [comment]
fixed in #950

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Send v2 dev website and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04x64.
