### ISSUE TITLE
[Send v2] The end of the "Private, Encrypted File Sharing" string is displayed under the default FxA avatar on German localization

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#946]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the preferred language set to German [de-de] in "about:preferences#general".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and to "https://send2.dev.lcip.org" page.
2. Observe the "Private, Encrypted File Sharing" string from the top of the Send card.

[Expected result]:
- The string is correctly displayed. 

[Actual results]:
- The end of the string is displayed under the default FxA avatar

[Notes]:
- Here is a screenshot of the issue:
![german string](https://user-images.githubusercontent.com/19226534/46002981-201bac00-c0b8-11e8-90ad-d28d7a513dc9.png)

**Comment by dannycoates** [comment]
fixed in #950

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Send v2 dev website and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04x64.
