### ISSUE TITLE
[Send v2][Enhancement] The password and the expiry options should be grayed out until a file is selected

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#947]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and  to "https://send2.dev.lcip.org" page.
2. Observed the password and expiry options.

[Expected result]:
- The options are grayed out since no file is selected.

[Actual results]:
- The options can be set even if no file is selected.

[Notes]:
- In the current behavior, you can set a password or change the expiry options even if no file is selected.
- Here is a screen recording of the issue:
![password and expiry options](https://user-images.githubusercontent.com/19226534/46005382-d33ad400-c0bd-11e8-9fc9-09961ef1870e.gif)

**Comment by dannycoates** [comment]
you should be able to do it in whatever order you want :)

**Comment by dannycoates** [comment]
obsoleted by new ui
