### ISSUE TITLE
[Send v2] No error is generated on Send "Signin" page if you submit an invalid email

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#948]
[Affected versions]:
- Firefox 62.0 and up
- Sendv2 2.5.4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://send2.dev.lcip.org" page.
2. Click the "Learn more!" link from the "Sign In/Up!" promo.
3. Enter an invalid email (eg: test@test).
4. Click the "CONTINUE" button and observe the behavior.

[Expected result]:
- An error is displayed on the page that informs the user that he entered an invalid mail.

[Actual results]:
- You are redirected to the FxA "Bad Request" page.

[Notes]:
- If you enter an incomplete email (eg: test@) and you click the "CONTINUE" button, nothing happens only the entered characters are automatically deleted.
- Also, if the email field is empty and you click the "CONTINUE" button nothing happens.
- Here is a screen recording of the issue:
![email validation](https://user-images.githubusercontent.com/19226534/46013950-5e27c880-c0d6-11e8-8994-6ba4c5a606a3.gif)

**Comment by dannycoates** [comment]
wontfix. im not going to do any more validation on this field

**Comment by dannycoates** [comment]
submitted https://github.com/mozilla/fxa-content-server/issues/6584
