### ISSUE TITLE
Uploading doesn't start, if you try to upload a large file on Firefox x32 builds

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/send#95]
[Affected versions]:
- Firefox 54.0 x32 and up
- Beta 55.0b1 x32
- Nightly 56.0a1 x32

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]
- Have the latest Firefox release x32 bits version and create a new profile.

[Steps to reproduce]:
1. Start the Firefox browser with the profile from prerequisites. 
2. Navigate to "https://p2p.dev.lcip.org/" page.
3. Upload a large file (eg: a 1.0 Gb file).
4. Observe the browser behavior.

[Expected result]:
- The file start uploading after a few seconds.

[Actual results]:
- Nothing happens, the file doesn't start uploading.

[Notes]:
- On Firefox x64 builds the uploading starts after ~15-20 seconds.
- When I encountered this issue I have tried to upload a 1.4 iso file. I have also managed to reproduce this with a 1.0 Gb zip file.

**Comment by SoftVision-CosminMuntean** [comment]
I did more tests and it seems that the uploading is working for a 400 Mb file, but is not working if you try to upload a 500 Mb file.

**Comment by dannycoates** [comment]
I think this is wontfix for v1 :/

**Comment by SoftVision-CiprianMuresan** [comment]
I don't think we should close this issue if it's a valid one. If the plan is to release without it fixed in V1, then it should be moved in the milestone in which it will be fixed.

Reopening and removing the milestone for re-triage.

**Comment by dannycoates** [comment]
closing as fixed in vnext

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible on "https://send2.dev.lcip.org" on Firefox x32 builds.
