### ISSUE TITLE
Sign up promo modal

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#951]
When an anonymous user selects an option that's only available to account users we can prompt them to create an account (or cancel and use other options)

There's just a placeholder modal right now.

**Comment by youwenliang** [comment]
Something like this?
https://mozilla.github.io/testpilot-assets/Send/Send_Modal_2/

Might need some work on the copy though.
@johngruen what do you think?

**Comment by dannycoates** [comment]
done
