### ISSUE TITLE
follow up on server language negotiation

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#955]
from https://github.com/mozilla/send/pull/952/files#r220847230

**Comment by stasm** [comment]
I've been thinking about this a bit more. I re-read to code and I think I understand it better now. As far as I could tell, the translation always comes from the pre-baked `dist/public/locales/*.js` files built by `npm run prod`. This limits our options when it comes to negotiating the user-preferred languages on the runtime if the user is interested in more than two languages that are currently baked into the `.js` file: the main one and the default one (`en-US`). Unless it's possible to create more pre-baked `.js` files on demand, somehow.

There are two major scenarios in which it's beneficial for the user that the array of negotiated languages has more than two elements:

1. Multilingual users might specify their `Accept-Language` header as, say, _Turkish, German, English_.
2. Speakers of same-family languages might want to fall back to a related language first, e.g. _Mexican Spanish, Spanish Spanish, English_.

For the first group, build time solutions don't scale well. The combinations of languages are plenty. It might be worth supporting just the most common ones. We'd need to match the array of user's languages with one of the pre-baked arrays of language fallback chains.

For the second group, we could use the languages specified by each locale in [`toolkit/chrome/global/intl.properties`](https://transvision.mozfr.org/string/?entity=toolkit/chrome/global/intl.properties:intl.accept_languages&repo=gecko_strings) to build the most commonly encountered fallback chains.

It would mean that for some locales, the pre-baked `*.js` would include more than two serialized `FluentResources`. From skimming the `public/locales` directory, it looks like each additional language would add ca. 8 KB to the final web app bundle (uncompressed).

CC @flodolo
