### ISSUE TITLE
[SendV2] Ready to send button missing class names.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/send#958]
The "Ready To Send" button seems to be missing some identifiers. Currently, after selecting a file to be uploaded, the "Ready To Send" button loads with this attributes:
```class="btn  " title="Ready to Send"```.

Seeing as there is some space after ```btn``` maybe something went wrong.

The cancel button seems to have some identifiers though: ```class=btn--cancel uploadCancel noDisplay```.

**Comment by dannycoates** [comment]
this specific issue is obsolete. the more general #930 is still open
