### ISSUE TITLE
[Enhancement] "Cancel" button should be displayed while uploading files

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/send#96]
[Notes]:
- "Cancel" functionality is not described in the mockups.

[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://p2p.dev.lcip.org/" page.
2. Upload a large file.
3. Observe the items from the Uploading panel.

[Expected result]:
- The user should be able to cancel the uploading process.

[Actual results]:
- "Cancel" button/link is not displayed.

**Comment by abhinadduri** [comment]
@dannycoates This might be as simple as adding a button to the DOM (something that is blocked until we get the new designs), and on click calling "location.reload()" and sending a delete request to the server to delete the partially uploaded file. It might be good to also delete off S3 at the same time, what are your thoughts?

**Comment by pdehaan** [comment]
@abhinadduri @dnarcese I believe the new UI added a cancel button, but it doesn't seem to do anything currently (ref [/frontend/src/upload.js:83](https://github.com/mozilla/send/blob/5ce0846580d77251fe812054a554786bb8adb255/frontend/src/upload.js#L83)).

I'll file a new issue, but not sure if this issue can be closed or not.

**Comment by SoftVision-CarmenFat** [comment]
I can see the "Cancel Upload" link is now displayed while uploading files on https://send.dev.mozaws.net/
