### ISSUE TITLE
Add support for GCS storage

### ISSUE THREAD

**Issue by jbuck** [mozilla/send#962]
This will require adding a new storage provider for GCS

**Comment by kylie-a** [comment]
I would be willing to do the work on this if this is something that would be useful for the community.

**Comment by jbuck** [comment]
Hi @kylie-a! Thank you for offering to work on this. @dannycoates has got a [pull request in progress](https://github.com/mozilla/send/pull/963) that's currently blocked on me deploying it

**Comment by dannycoates** [comment]
Done in #963
