### ISSUE TITLE
Request Data Review

### ISSUE THREAD

**Issue by marniepw** [mozilla/send#967]
Please answer the questions in this: [https://github.com/mozilla/data-review/blob/master/request.md](https://github.com/mozilla/data-review/blob/master/request.md)

Answer them in/by filing a bugzilla ticket. See full instructions here (look at section Step 1: Submit Request): [https://wiki.mozilla.org/Firefox/Data_Collection](https://wiki.mozilla.org/Firefox/Data_Collection)

NI Rob Rayborn (rrayborn) in the bugzilla bug.

**Comment by marniepw** [comment]
@dannycoates we should get this going, especially with the holidays and All Hands creeping up.

**Comment by clouserw** [comment]
Depends on amplitude changes now

**Comment by clouserw** [comment]
The amplitude conversion is https://github.com/mozilla/send/pull/1091

**Comment by clouserw** [comment]
bug filed at https://bugzilla.mozilla.org/show_bug.cgi?id=1520322

**Comment by johngruen** [comment]
It looks like we have our R+ here

**Comment by johngruen** [comment]
@clouserw can you verify and close this?

**Comment by clouserw** [comment]
Looks good.  I closed the bug
