### ISSUE TITLE
Login Page and session tokens

### ISSUE THREAD

**Issue by nadav123** [mozilla/send#968]
Hi
I have a server with Nginx to do a reverse proxy for the mozilla project i have on my server.
i have a PHP login page with mysql server behind it and once the user is authenticated they are redirected to xxxxxx.xxx/send/  where the application is located.

the problem is that the external user can directly go to xxxx.xxx/send/ and get inot the application since it didnt pass/checked if it is logged in.

How / is there a way to add somewhere (i guess in the welcome/index.js ) some sort of code to verify that the user was logged in ? if so can you assist how ? 

THanks

**Comment by dannycoates** [comment]
this isn't a deployment setup we can support, sorry.
