### ISSUE TITLE
Production site shows old translation

### ISSUE THREAD

**Issue by bidaian** [mozilla/send#973]
While uploading a file the es-ES text says "Imporando…" instead of "Impor**t**ando…" (en-US: "Importing…").

That was fixed about a year ago in Pontoon, and this is the commit to the repository: dfea1e96fb472e5b4a427a9bb223b4ab84003989

To reproduce, set 'es' as your browser language and try to upload a file.

**Comment by dannycoates** [comment]
The most recent update to production was Nov. 14
