### ISSUE TITLE
Change uploading file to modal view

### ISSUE THREAD

**Issue by youwenliang** [mozilla/send#999]
One proposal for the Send web version is to change the uploading view into a modal view instead of a split view. 

Like this:
![send_home with files modal](https://user-images.githubusercontent.com/8919308/48119046-1b4a3a80-e2a9-11e8-8dda-53519f61ad77.png)

what do you think? @johngruen

**Comment by dannycoates** [comment]
I don't like

**Comment by youwenliang** [comment]
The reason behind this proposal is that the file list on the right panel could be confusing during the uploading actions. Here's another proposal: (disabling the right panel during uploading actions)

![send_ready_to_send copy](https://user-images.githubusercontent.com/8919308/48174153-bbec3900-e341-11e8-8190-5c6a6e268c04.png)
![send_sending copy](https://user-images.githubusercontent.com/8919308/48174152-bbec3900-e341-11e8-80a4-e7c1e572508f.png)

Any thoughts?

**Comment by johngruen** [comment]
I think it would be nice to do something more graphical...just a loading screen or something

**Comment by dannycoates** [comment]
The thing that would impact the code the least is to keep it within the left half. Bigger or whatever else to make it not look like the items on the right is all ok.
